- docs/tutorial/tutorial-1.rst
- docs/tutorial/tutorial-2.rst
- docs/tutorial/tutorial-3.rst
Various E302, E225 and E226 and E501 across the 3 files.
Not 100% sure that `buttons[i - 1]` is actually better than `buttons[i-1]` but I've added it to quieten the tool.
> Made tutorials compliant with pep8

- README.rst
- docs/tutorial/tutorial-0.rst
I broke out the Ubuntu and Fedora specifics in the various sections as appropriate.  I thought I'd include the Fedora specific path for the symlinking of the gi module until issue #43 is resolved, just to make it easier for new comer in the meantime.
> Added details for installing on Fedora

- README.rst
- docs/index.rst
- docs/tutorial/tutorial-0.rst
Same typo is also on http://pybee.org/toga/
> 'symlinking' typo

- docs/tutorial/tutorial-1.rst
Simple spelling error, probably due to our author having some other weird unit measure preference.
> Updated tutorial-1.rst with Celsius

- docs/conf.py
- docs/reference/core.rst
- toga/__init__.py
- toga/interface/app.py
This patch adds the ability to document the UI toolkit using
base abstract classes, and includes those docs in the reference
doc section.
There should be a related patch generated for each of the
implementations which bases their concrete UI components
off of the abstract provided here.
Signed-off-by: Richard Jones <r1chardj0n3s@gmail.com>
> Add extracted reference docs

- src/iOS/toga_iOS/widgets/label.py
If you add a Label in iOS, the application crash with the exception:
```
File "/Users/marc/Library/Developer/CoreSimulator/Devices/294E285B-2221-460A-B009-B2FFF9DB83D4/data/Containers/Bundle/Application/B2E6BC5C-4ECC-447D-810D-ACD19EFFE87D/Hello World.app/Library/Python.framework/Resources/lib/python3.5/site-packages/colosseum/layout.py", line 174, in _set_dimension_from_style
if not self._dimension_is_defined(axis):
File "/Users/marc/Library/Developer/CoreSimulator/Devices/294E285B-2221-460A-B009-B2FFF9DB83D4/data/Containers/Bundle/Application/B2E6BC5C-4ECC-447D-810D-ACD19EFFE87D/Hello World.app/Library/Python.framework/Resources/lib/python3.5/site-packages/colosseum/layout.py", line 110, in _dimension_is_defined
return value is not None and value > 0
TypeError: unorderable types: …
```
> Toga Label not working on iOS

- docs/tutorial/tutorial-1.rst
The order of f_input and f_label in the example code of tutorial-1.rst does not match the screenshot. This is what it looks like as is on Ubuntu:
This is what it looks like after swapping:
> Swap order of f_input and f_label in tutorial-1.rst

- src/gtk/toga_gtk/container.py
- src/gtk/toga_gtk/widgets/base.py
- src/gtk/toga_gtk/widgets/box.py
- src/gtk/toga_gtk/widgets/splitcontainer.py
(toga-demo:23072): Gtk-WARNING **: Allocating size to GtkButton 0x558d3783fa40 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
> Fixed rehinting on GTK to get rid of:

- docs/requirements.txt
Currently, the RTD autodoc build fails for two reasons: a) because the build uses Python 2.7 and `builtins` import fails, and b) because the `colosseum` import fails.
The first problem can be fixed by editing the RTD `Advanced Settings` and changing the Python **Python interpreter** setting to **CPython 3.x**.
The second problem can be fixed by adding a `requirements.txt` with the `colosseum` dependency (this PR), and editing the RTD `Advanced Settings`, enabling *Install your project inside a virtualenv using setup.py install* and setting **Requirements file** to `docs/requirements.txt`.
> Fix autodoc in the RTD builds

- README.rst
- docs/conf.py
- docs/tutorial/tutorial-2.rst
1. Add links to the classes in the text at the bottom of the second tutorial
2. Update conf.py to use the sphinx-rtd-theme if can be imported so the documentation can built and tested locally.
3. Fix the headers in the Readme to not be beyond the header text.
> Minor documentation fixes

- src/core/toga/interface/window.py
On toga_cocoa/dialogs requires content and retry status to create the dialog window, so I add on the interface to allow the passage of them.
> Content and retry status on the window interface

- src/cocoa/toga_cocoa/__init__.py
- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/widgets/switch.py
- src/core/toga/interface/__init__.py
- src/core/toga/interface/widgets/switch.py
- src/iOS/toga_iOS/__init__.py
- src/iOS/toga_iOS/libs/uikit.py
- src/iOS/toga_iOS/widgets/switch.py
@freakboy3742 I know we talked about not including the switch widget as a normal widget but only through the settings api. But on my settings-api-journey I found out that for macOS and iOS you have to (if you don't manage all the settings in the settings app what basically every normal app does) provide your own settings and therefor you need to be able to create your own switch widget.
- macOS work
- iOS switch has no label by default this is because it should only appear in a UITable​View​Cell with a label. I found some apps that use a switch with a label in a single UITable​View​Cell without a UITabelView wrapped around it and they say it is no problem. If I get your ok I would try to implement this into the iOS switch integration. The iOS switch functionality works already. 
Here a …
> Switch implementation for core, cocoa and iOS(label not working on iOS)

- src/cocoa/toga_cocoa/app.py
The issue is discussed [here](https://github.com/pybee/rubicon-objc/issues/46) and leads to the following error:
~~~
File "_ctypes/callbacks.c", line 234, in 'calling callback function'
File "/Users/Jonas/Documents/Programming/PyBee/rubicon-objc/rubicon/objc/objc.py", line 1069, in _objc_method
result = f(py_self, *args)
File "/Users/Jonas/Documents/Programming/PyBee/toga/src/cocoa/toga_cocoa/app.py", line 53, in application_openFiles_
for i in range(0, filenames.count):
TypeError: 'method' object cannot be interpreted as an integer
~~~
> fix for getting the length of the filenames array

- src/cocoa/toga_cocoa/widgets/progressbar.py
> Fixed  #189 cocoa.progressbar with rehint

- src/cocoa/toga_cocoa/widgets/base.py
- src/core/toga/interface/widgets/base.py
> Hide/show widget [Core] [Cocoa]

- src/cocoa/toga_cocoa/widgets/webview.py
- src/core/toga/interface/widgets/webview.py
Cocoa binding uses the webview's document model to retrieve the DOM as a string. Other platforms NYI. on_load event notifies the event listener but it is up to the listener to retrieve url/DOM from the widget.
> Adds an on_load listener and method to retrieve DOM.

- .gitignore
To prevent accidentally adding files from developer tools.
> Add virtual exclude for project local virtualenv and PyCharm

- src/android/toga_android/dialogs.py
Signed-off-by: Elias Dorneles <eliasdorneles@gmail.com>
This adds the `info` dialog for Android, inspired on https://github.com/pybee/toga/blob/master/src/cocoa/toga_cocoa/dialogs.py .
The next dialogs will need a bit more thinking, since the functions need to return the a boolean indicating the user decision, and the Android Dialog API is async (one gotta register listeners to execute actions when a button is clicked).
> Add simple info dialog for Android app

- src/core/toga/widgets/numberinput.py
- src/core/toga/widgets/selection.py
Reference documentation was not generating properly because they were missing indentation
> Fix Widget Args format

- src/core/tests/test_font.py
- src/core/toga/font.py
- src/dummy/toga_dummy/factory.py
- src/dummy/toga_dummy/font.py
- src/gtk/toga_gtk/font.py
As my first contribution to the BeeWare Toga project, I was planning on writing some tests to increase coverage as suggested by the [contribution guide on Read The Docs](http://toga.readthedocs.io/en/latest/how-to/contribute.html).
I decided that `core/toga/font.py` looked like an easy place to start (its a single class with two getters), but when I ran my tests I got some errors coming from `gtk/toga_gtk/font.py`, saying that `self.family` and `self.size` were undefined. This is because those properties are defined on the core Font class (which the GTK Font class keeps an instance of thru `self.interface`). I can see how a person might have been confused by the two similar-ish Font classes and forgot which class the properties belong to.
If this commit looks good, I plan on also writing …
> Fix interface error in GTK Font

- src/gtk/toga_gtk/app.py
> Give Window on_close method the correct arguments for GTK+

- src/core/toga/widgets/table.py
- src/gtk/toga_gtk/widgets/button.py
- src/gtk/toga_gtk/widgets/table.py
I have a linux environment, so I plan on working with `toga_gtk`. 
These changes allow GTK Tables to render row data. 
A small change would also made to the Core API Table class; see the commit for details.
> Implement refresh() for GTK toga.Table

- examples/detailedlist/detailedlist/__init__.py
- examples/detailedlist/detailedlist/__main__.py
- examples/detailedlist/detailedlist/app.py
- src/core/tests/widgets/test_detailedlist.py
- src/core/toga/widgets/detailedlist.py
- src/core/toga/widgets/table.py
- src/dummy/toga_dummy/factory.py
- src/dummy/toga_dummy/widgets/detailedlist.py
- src/iOS/toga_iOS/widgets/detailedlist.py
* added on_select functionality
* refresh is now only possible when a on_refresh handler was set.
* added documentation.
> Upgrade of DetailedList core and iOS

- examples/selection/README.rst
- examples/selection/selection/__init__.py
- examples/selection/selection/__main__.py
- examples/selection/selection/app.py
- examples/selection/setup.py
- src/core/toga/widgets/selection.py
- src/gtk/toga_gtk/widgets/selection.py
See the  example app to view `on_select` in action.
I made another change to the GTK Selection: the first item will be selected by default. I think this is fairly expected behavior; I know that HTML5 `<select>` does this, for example. Previously, the Selection widget was blank when the app opens.
> Implement GTK+ Selection `on_select` + Create example app

- src/gtk/toga_gtk/widgets/tree.py
The Issue: selected row is always None
Reason: the `Gtk.TreeIter` returned by `get_selection()` was never the same one returned by `self.store.insert()`. Therefore, a lookup with `self.nodes.get(treeiter)` always failed.
The solution I chose was to store a tree path in `self.nodes` string instead of Gtk.TreeIter so `self.nodes.get(treeiter)` finds a result.
I should note that I haven't tested `Tree.change` yet since the example app only performs `insert`.
> Fix GTK+ Tree row selection

- src/android/toga_android/widgets/button.py
- src/cocoa/toga_cocoa/widgets/button.py
- src/core/toga/widgets/button.py
- src/dummy/toga_dummy/widgets/button.py
- src/gtk/toga_gtk/widgets/button.py
- src/iOS/toga_iOS/widgets/button.py
- src/win32/toga_win32/widgets/button.py
- src/winforms/toga_winforms/widgets/button.py
Only for widgets/button
- changed `set_label` in src/core/toga/widgets/button.py to pass down literal argument
- changed each implementation (Cocoa, Gtk+, etc) to use `self.interface.label` instead of `label` so that they use values from interface
- passes all testcases
> Ref #299 - Correct usage of arguments on Button.set_label

- examples/tutorial3/tutorial/app.py
- examples/tutorial4/tutorial/app.py
- src/cocoa/toga_cocoa/widgets/base.py
- src/cocoa/toga_cocoa/widgets/splitcontainer.py
- src/cocoa/toga_cocoa/window.py
- src/core/toga/widgets/base.py
- src/core/toga/widgets/scrollcontainer.py
- src/gtk/toga_gtk/widgets/base.py
- src/gtk/toga_gtk/widgets/box.py
- src/gtk/toga_gtk/window.py
- src/winforms/toga_winforms/widgets/base.py
- src/winforms/toga_winforms/window.py
@danyeaw pointed out that viewport was being exposed at the interface layer, which lead to some cleanups around assigning viewport.
However, the real fix was around the native widget behind Box - since it's a toga widget, *every* box was getting a Gtk resize signal, leading to a redraw. However, only the top level widget needs to recompute the layout, so the layout can be ignored for every box *except* the one that has a viewport (which flags it as the top-level widget).
> Fixes #314 - Clarified handling of viewport and sublayouts.

- src/gtk/toga_gtk/widgets/table.py
- src/gtk/toga_gtk/widgets/tree.py
Note that several "empty" methods that wrap `super()` are included in order to
make the tests happy (since the tests do not look for inherited methods). Look to line 37, `create()` for an example of one such method.
I'd be great to have the tests realize that the methods are implemented by the base class, so that these empty wrappers can be removed. (Gtk Table would then be only ~30 lines long!) I dug around a bit in `toga_dummy/test_implementation.py` and found `methods_of_class()`, which finds methods in a class by syntax. I quote a comment: "Warnings:
Does not return inherited methods. Only methods that are present in the class and the actual .py file."
Is it a desirable feature to have the tests go deeper than syntax and find inherited methods? If it is, I'll gladly take a stab at it. …
> Make Table a subclass of Tree [GTK]

- src/android/toga_android/widgets/label.py
- src/cocoa/toga_cocoa/widgets/label.py
- src/core/toga/widgets/label.py
- src/django/toga_django/widgets/label.py
- src/dummy/toga_dummy/widgets/label.py
- src/gtk/toga_gtk/widgets/label.py
- src/iOS/toga_iOS/widgets/label.py
- src/win32/toga_win32/widgets/label.py
- src/winforms/toga_winforms/widgets/label.py
For widgets/label
- changed set_text in src/core/toga/widgets/label.py to pass down literal argument
- changed each implementation (Cocoa, Gtk+, etc) to use self.interface._text so that they use values from interface
> Ref #299 - Correct usage of arguments on Label.set_text

- docs/conf.py
- docs/how-to/contribute.rst
- docs/requirements.txt
- docs/requirements_docs.txt
- docs/requirements_rtd.txt
Code samples that are slightly different on multiple platforms (e.g., macOS/Linux/Windows command lines) needed a slightly better markup to avoid confusion in the text.
> Added tabs for multi-platform code samples.

- examples/slider/slider/app.py
- src/gtk/toga_gtk/widgets/slider.py
- src/gtk/toga_gtk/widgets/switch.py
Closes #340. Fixes AttributeErrors in the slider and switch widgets in the rehint methods. Updates the slider example to ensure that Slider widgets are getting a Pack style applied.
> Fix slider and switch widget attribute errors in Gtk+

- docs/tutorial/tutorial-0.rst
Changed pip install in tutorial to use the `--pre` flag per @freakboy3742 in order to solve an issue where the current PyPy doesn't work on OSX High Sierra (`TypeError: 'ObjCInstance' object is not callable`).
> Recommend Installing Pre For Tutorial

- src/core/tests/style/test_pack.py
- src/core/toga/style/pack.py
This adds tests for setting style properties to a node.
While adding tests, we found that `hidden` property for Style did not work. So, this PR also renames `hidden` style property to `visibility` and adds necessary logic to map from `visibility` style prop value to `hidden` value.
> Add tests for setting style properties to a node

- src/iOS/toga_iOS/widgets/button.py
The `UIControl` constants will be undefined unless we import them from libs/uikit.py
> UIControl constants are undefined

- src/core/tests/sources/test_list_source.py
- src/core/tests/sources/test_tree_source.py
- src/core/toga/sources/list_source.py
- src/core/toga/sources/tree_source.py
Changes:
- implement index() for ListSource and TreeSource
- simplify a few list/dict compressions using `dict` constructor
Use cases:
*Fetching items relative to a given item*
```python
def on_select(table, row, **kw):
i = table.data.index(row)
prev_row = table.data[i - 1]
next_ row= table.data[i + 1]
print("Adjacent rows: {}, {}".format(prev_row, next_row))
```
*Inserting before/after a given item*
```python
def insert_after(table, new_row, ref_row):
i = table.data.index(ref_row)
table.data.insert(i+1, new_row) # i - 1 for insert_before, for example.
```
The implementation is based on my discussion with @freakboy3742 on Gitter on Dec. 21 concerning data sources and handler content.
---
As far as documentation goes, the index() methods belong to ListSource and TreeSource, which, at the …
> Implement data source `index()` method

- examples/.template/{{ cookiecutter.name }}/{{ cookiecutter.name }}/app.py
Current cookie cutter template raises a Window is already associated with an App exception.
> Fix example cookiecutter template

- src/winforms/toga_winforms/widgets/base.py
- src/winforms/toga_winforms/widgets/table.py
Winforms table implementation updated:
- native.ListViewItem assignment with an asterisk didn't show up, so I deleted the asterisk `(*[])` -> `([])`. Will it break anything?
- `clear() `method updated, so it clears the data but not the column names. Is this implementation correct?
- added `multiple_select` implementation and selection of the full row. 
- added `update_data` method that updates data from the interface.data and is called when '`remove`' method is called.
- implemented `widget.set_hidden()` method.
Now `examples/table` works on Windows. Although the handler is not implemented (I believe it's not implemented for any platform yet, as I couldn't find examples). There are also problems with layout in the example
Refs#155: One step closer …
> Updated Table implementation in Winforms. examples/table almost works

- examples/canvas/README.rst
- examples/canvas/canvas/__init__.py
- examples/canvas/canvas/__main__.py
- examples/canvas/canvas/app.py
- examples/canvas/canvas/resources/README
- examples/canvas/setup.py
- src/core/toga/widgets/canvas.py
When I was initially creating the canvas widget, I tested support for drawing simple things without calling the on_draw handler. But, there seems to be some regressions in this actually working. This PR fixes a TypeError when no on_draw handler parameter is passed, and also adds an example to help ensure that simple canvas calls work in the future and will help with final completion of the cocoa implementation of canvas.
I'm not sure if it is related to the changes to support Pack, but I can't get the canvas to display with this example. It looks like the canvas is getting size allocations ok to me when I uncomment the debug statements in the Pack module. I could use some help or direction on further troubleshooting.
> Create canvas without on_draw handler

- src/core/toga/widgets/numberinput.py
- src/gtk/toga_gtk/widgets/numberinput.py
Completed the documentation for NumberInput widget in core file and also audited it.
The value from the user was directly getting passed to the platform implementation layer without getting checked as in case when a value of type integer should be passed rather than of type string. Therefore, I instead of passing the value from the user passed the property' value to which the original value passed by the user is getting assigned to after the check.
> Added documentation and audited NumberInput

- src/core/toga/widgets/numberinput.py
- src/gtk/toga_gtk/widgets/numberinput.py
An error is getting encountered in core tests related to NumberInput widget which is basically the max and min values being set to None in case of no input for them which is consistent with the definition of the NumberInput. So to fix this the max and min values are being set to None now in the core package and the gtk implementation has also been made consistent with the interface now.
> Fixed core test errors and gtk implementation for NumberInput

- examples/.template/{{ cookiecutter.name }}/{{ cookiecutter.name }}/app.py
The example cookiecutter template requires updates to support Travertino / Pack instead of Colosseum / CSS. It also fixes the on_press call for the clear button and NameErrors caused by the labels being undefined.
> Update example cookiecutter to support Pack

- src/cocoa/toga_cocoa/widgets/base.py
In Cocoa when running any example I was getting an AttributeError caused by applying a style that then sets the visibility attribute on subviews. These subviews are being search for on a container that does not yet exist. This change checks that the container is not None first.
> Fix AttributeError: Nonetype object has no _impl in Cocoa

- src/iOS/toga_iOS/app.py
- src/iOS/toga_iOS/widgets/base.py
- src/iOS/toga_iOS/widgets/button.py
Signed-off-by: Moises Aranas <moises.aranas@gmail.com>
This fixes some missing imports:
- objc_method reference being used in toga-iOS's app.py
- UIButton reference in toga-iOS's Button implementation
> toga-iOS: Added missing imports in app.py and the Button widget

- docs/reference/widgets/progressbar.rst
- src/core/toga/widgets/progressbar.py
Signed-off-by: Drew Meier <darius.montez@gmail.com>
This PR fixes some docs from #291 and adds several docstrings in core/ProgressBar.
I initially used a Markdown style table (oops!) in the `progressbar.rst` docs page instead of an RST table, so it did not render correctly. I've cut out the old markdown code and replaced it with RST.
I also added some docstrings to the new progress bar properties and methods.
> docs/ProgressBar: replace Markdown table with RST table

- docs/how-to/contribute.rst
Small fix to make coverage's `--include` flag to do pattern matching rather than zsh globbing `*`.
> Make command compatible to other shells especially zsh

- src/cocoa/toga_cocoa/widgets/numberinput.py
- src/core/toga/widgets/numberinput.py
- src/gtk/toga_gtk/widgets/numberinput.py
- src/gtk/toga_gtk/widgets/selection.py
- src/iOS/toga_iOS/widgets/numberinput.py
Number inputs are much more useful if they can handle floating point values, not just integers; but integers have a precision problem. This change allows Numberinputs to use any numeric value (including string versions of numbers) as their min/max/step/value, and preserves the precision of the step value.
>  Modified NumberInput to use Decimals.

- src/cocoa/toga_cocoa/widgets/imageview.py
Imageview in toga-cocoa was broken with the following error:
```
File "easy_weather/.venv/lib/python3.6/site-packages/toga_cocoa/widgets/imageview.py", line 61, in rehint
self.interface.style.hint(
AttributeError: 'Pack' object has no attribute 'hint'
```
This change just passes the rehint method of the imageview class for toga-cocoa
I realize there might be a better fix, but this seems to work without any known side effects. A working imageview seems better than a broken one...
> Fix toga-cocoa imageview (bypass rehint)

- README.rst
This PR is related to issue #371 and PR #374. That PR removes the workaround that links the virtualenv libraries to the system libraries for PyGObject. This README update documents the extra dependencies and other info needed to successfully pip install PyGObject.
I have tested these dependencies on the 3 platform. I also posted my [Vagrant files](https://github.com/danyeaw/vagrant-dev-toga) if anyone is interested in looking at what was installed or testing it themselves.
I also cleaned up some of the other parts of the README to stay at 80 lines.
> Update optional extras in README to install pygobject using pip

- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/libs/appkit.py
- src/core/toga/app.py
When trying to run podium from source I got the following error:
File "/~/.virtualenvs/podium/lib/python3.6/site-packages/toga_cocoa/app.py", line 33, in applicationOpenUntitledFile_
for filetype in self.interface.document_types:
AttributeError: 'App' object has no attribute 'document_types'
and
File "/~/.virtualenvs/podium/lib/python3.6/site-packages/toga_cocoa/app.py", line 36, in applicationOpenUntitledFile_
ObjCInstance(NSDocumentController.sharedDocumentController().runModalOpenPanel(panel, forTypes=fileTypes))
TypeError: 'ObjCInstance' object is not callable
This fix properly points document_types to the implementation so that it can be accessed across the interface. It also stops calling the type property as a function to access the …
> Fix AttributeError: 'App' object has no attribute 'document_types'

- src/core/tests/widgets/test_table.py
- src/core/toga/widgets/table.py
I'm altering toga.widgets.Table so it initialises the ._selection attribute. 
In #401 I noticed if a user hasn't made a selection in a table, but you check the Tables selection a AttributeError is thrown. The documentation says None should be returned.
> Table selection issue 401

- src/cocoa/toga_cocoa/app.py
Properly call back to the `App` object to get access to `_menu_items` to run menu commands.
Fixes #409
> Properly traverse back to the App object for selecting menu items on cocoa

- docs/reference/supported_platforms/Label.rst
- docs/reference/supported_platforms/TextInput.rst
For the supported_platforms record files for Label and TextInput, I changed the file contents that read `no` for the `android` column to `yes`, as these widgets are supported on android.
This solves #420 for the widgets Label and TextInput on android.
> Fixed missing checkmarks for support for Label, TextInput on Android

- src/winforms/toga_winforms/window.py
The issue of secondary window not showing up on Windows came up on gitter. Due to the difference in app/ window handling on different platforms, non-main window didn't show up. So, I added a check if the window is main/secondary, and a call to show the native window if it's not main.
> Show secondary window on Winforms

- examples/imageview/setup.py
- examples/scrollcontainer/setup.py
- examples/switch/setup.py
Cleanup - This removes the relative paths in setup.py for the examples
Signed-off-by: Moises Aranas <moises.aranas@gmail.com>
> toga-iOS: Removed relative paths in setup.py for examples

- src/winforms/toga_winforms/window.py
The dialogs are implemented. I tested them using the demo app without the tree. Error dialog even has the native windows error sound :)
> Implemented info, question, confirm and error dialog

- src/core/tests/widgets/test_progressbar.py
- src/gtk/toga_gtk/window.py
There is no function for `set_full_screen` in any of the backends but the function is being used in the core module. To solve this, I have implemented the `set_full_screen()` for the Gtk module as a start.
I have also increased the coverage of ProgressBar by using `self.progress_bar.value` instead of `self.progress_bar._value` in all the assert statements since ideally the former one should be used to access the value attribute of the progress bar. This, in turn, has also increased the coverage of Progress Bar as well.
> Increased coverage for ProgressBar and implemented Window.set_full_screen in Gtk

- src/winforms/toga_winforms/widgets/box.py
- src/winforms/toga_winforms/window.py
When a box is the outer-most container, vertical shift of the frame (window, in this case), should be added to the box layout. 
Also, the error raised when a toolbar item didn't have an icon, is handled in this PR.
> Edit Box vertical shift calculations if it's outermost widget

- docs/reference/api/app.rst
Delete `startup=build` arg in the docs. (`build` is not defined in this example and the `startup` method is used anyway.)
> DOC: fix little bug

- src/cocoa/toga_cocoa/widgets/multilinetextinput.py
- src/core/tests/widgets/test_multilinetextinput.py
- src/core/toga/widgets/multilinetextinput.py
- src/dummy/toga_dummy/widgets/multilinetextinput.py
- src/iOS/toga_iOS/widgets/multilinetextinput.py
- src/winforms/toga_winforms/widgets/multilinetextinput.py
MultilineTextInput widget the “value” doesn’t change even if user types in the text box. The problem is that the interface layer (src/core/widgets/multilinetextinput.py) doesn’t make a call on the implementation layer (src/cocoa/widgets/multilinetextinput.py) on the value property.
Signed-off-by: Stanton Xu <xjiefeng@gmail.com>
> Updated value property of MultilineTextInput, implemented in cocoa. Updated dummy and test case.

- src/winforms/toga_winforms/color.py
- src/winforms/toga_winforms/libs.py
- src/winforms/toga_winforms/widgets/numberinput.py
- src/winforms/toga_winforms/widgets/textinput.py
I added proper handling for `on_change` event for TextInput in Winforms, and tested it on my example app.
Issue#467 reported the problem with `on_change` handler in GTK, and apparently Winforms had the same problem.
Also, I added text_align handling for TextInput, and edited a mix up of Windows native colors: green value was sent to blue and vice versa.
> Update on_change for TextInput in Winforms

- src/android/toga_android/widgets/base.py
- src/cocoa/toga_cocoa/widgets/base.py
- src/core/tests/widgets/test_base.py
- src/django/toga_django/widgets/base.py
- src/dummy/toga_dummy/widgets/base.py
- src/gtk/toga_gtk/widgets/base.py
- src/iOS/toga_iOS/widgets/base.py
#299 
Updated base widget backends to use interface value when setting 'enabled'. Adds a test case to assert this happens in the dummy base widget using a dummy box widget.
> Audit backends for consistency in "set_attribute()" pattern for base.enabled

- src/gtk/toga_gtk/factory.py
- src/gtk/toga_gtk/widgets/detailedlist.py
This PR adds stubs for detailedlist for gtk interface
When using the detailedlist widget on linux, the user gets:
```
AttributeError: module 'toga_gtk.factory' has no attribute 'DetailedList'
```
This PR continues the work done in https://github.com/pybee/toga/pull/358 so that instead of a fatal/hard error, the below soft errors are raised and execution continues.
```
[GTK+] Not implemented: DetailedList.change_source()
...
[GTK+] Not implemented: DetailedList.rehint()
...
```
This PR relates to https://github.com/pybee/toga/issues/338
> detailedlist stub

- src/core/tests/test_key.py
- src/core/toga/keys.py
Also correct a typo:
CAPSLOCK = '<caps> lock' is replaced by CAPSLOCK = '<caps lock>'
Signed-off-by: Niklas Eidhagen <niklas.eidhagen@gmail.com>
> Add a test for is_printable().

- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/libs/foundation.py
- src/cocoa/toga_cocoa/window.py
`NSTextEffectAttributeName` is only supported in OSX 10.10+. Currently the toga project supports OSX 10.7+.
It was discovered the `NSTextEffectAttributeName` is unused in the project. To solve the compatibility issues, reference to `NSTextEffectAttributeName` in `toga/src/cocoa/toga_cocoa/libs/appkit.py` has been commented out.
Further compatabiity has been through adding `NSBundle.declare_property('bundlePath')` and ` NSWindow.declare_property('frame') ` for backwards compatability.
As per toga setup instructions in the README:
Create a virtual machine `python3 -m venv venv` and activate with `. venv/bin/activate`
```
$ pip install pycairo
$ pip install pygobject
$ pip install toga-demo
$ toga-demo
```
```
$ cd toga/examples/tutorial0
$ python3 -m tutorial
$ pip install -e src/core
$ pip …
```
> OSX 10.7+ re-compatability

- docs/tutorial/tutorial-0.rst
Adds documentation for installing python 3.
The current documentation says to make sure `python3` can be successfully run, but does not say anything on what to do if it does not work.
This should improve the the issue #335
> fix: Added information on how to install Python 3

- src/gtk/toga_gtk/widgets/icon.py
This patch sets the default Tiberius icon extension to .icns.
If you try to run the project in Linux from uptream code, the windows is
not showing up, due to the missing icon filename extension.
> Fix default Tiberius icon load in GTK

- src/cocoa/toga_cocoa/widgets/image.py
- src/core/toga/widgets/image.py
- src/iOS/toga_iOS/widgets/image.py
The ImageView example provides a relative path but Image.load_image
requires absolute path in Cocoa. This patch allows load_image to accept
a relative path.
Signed-off-by: William Clemens <wesclemens@gmail.com>
Will not resolve relative paths for Cocoa.
Image widget didn't resolve relative paths with Cocoa. This caused the exmpale imageview app to be broken.
> ImageView example provides rel path not working

- src/cocoa/toga_cocoa/libs/appkit.py
In tutorial1 of the toga project for OS 10.7+ the text field option has been fixed to be non-editable. This required declaring `editable` and `bezeled` as properties for `NSTextField`.
> OS 10.7+ compatability for non-editable text labels

- src/cocoa/toga_cocoa/libs/appkit.py
Solved by adding declare_property for itemIdentifier in appkit.py to solve compatibility issues.
```
File "_ctypes/callbacks.c", line 234, in 'calling callback function'
File "/Users/Munnu/Documents/gitrepo/pycon2018/beeware/toga/venv/lib/python3.6/site-packages/rubicon/objc/runtime.py", line 1033, in _objc_method
result = f(py_self, *args)
File "/Users/Munnu/Documents/gitrepo/pycon2018/beeware/toga/src/cocoa/toga_cocoa/window.py", line 89, in validateToolbarItem_
return self.interface._impl._toolbar_items[item.itemIdentifier].enabled
KeyError: <exception str() failed>
```
> Os lion re compatability - NSToolbarItem itemIdentifier error

- examples/dialogs/README.rst
- examples/dialogs/dialogs/__init__.py
- examples/dialogs/dialogs/__main__.py
- examples/dialogs/dialogs/app.py
- examples/dialogs/dialogs/resources/README
- examples/dialogs/setup.py
- src/core/toga/window.py
- src/winforms/toga_winforms/window.py
I added `open_file_dialog` to the core `main_window` class, as well as Windows implementation for `open_file_dialog` and `save_file_dialog`. There are several things I'm not sure about: 
1. Windows allows multiselect when opening files. Should we add it?
2. What is the format of `file_types` sent to these dialogs? Is it something like `['txt', 'py']` or `['.txt', '.py']`?
3. Save file dialog should only provide the path where to save, saving itself should be done in the app, right? And the same is true with open file dialog, it only returns the full file name.
4. If the dialog is canceled, it returns `None`. Is this preferred behavior?
> Add open file dialog and example app for dialogs

- src/gtk/toga_gtk/dialogs.py
- src/gtk/toga_gtk/window.py
Added the select_folder_dialog to gtk as well. It feels a bit repetitive compared to the other dialog functions--I initially tried to just cram an `is_folder` flag into the open_file function but that led to a few weird edge cases like passing file types to a folder dialog which felt less natural than just giving the folder dialog its own function.
Definitely open to suggestions here
EDIT: This PR also implements a small bugfix to the `save_file` dialog to handle the unused `file_types=None` case.
> add select_folder_dialog to gtk

- docs/reference/api/widgets/switch.rst
The intro text for the `switch` widget seemed to be copy and pasted from the text widget. This commit uses the docstring's text instead.
> Fix intro text for 'switch'-widget

- src/android/toga_android/window.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/test_window.py
- src/django/toga_django/window.py
- src/dummy/toga_dummy/window.py
- src/iOS/toga_iOS/window.py
- src/winforms/toga_winforms/window.py
EDIT: See comments below 
I added a setter method to toga_dummy\window.py for is_full_screen property. Then added a few lines to test_full_screen_set() so that it tests both reading and writing. If I understand correctly, an additional benefit of testing the setter method is to ensure the _impl method is invoked.
I'd like to continue working on this adding additional test for window.py, but would like to make sure I am on the right track, especially w.r.t changes/addition to toga_dummy\window.py
Best Regards,
Bob Marchese
Improves test coverage on window.py
> Add set_full_screen() stubs to window.py implementations

- src/gtk/toga_gtk/widgets/imageview.py
If the image path is invalid, gtk backend raises a value error instead of crashing the app.
Fixes #529
> GTK to raise error if image path is not valid

- src/cocoa/toga_cocoa/window.py
This PR is to implement the on_exit handler in Cocoa, while PR#522 did it for Core and Winforms by @obulat 
Added the handler to windowWillClose, which is the native method triggered when window is closed
Refs #522 
Signed off by @stantonxu
> On_exit handler created in Cocoa, related to PR#522

- src/gtk/toga_gtk/widgets/imageview.py
Changes the variable displayed in ValueError call in toga_gtk/widgets/imageview.py, line 34
Corrects the path variable displayed by the gtk imageview widget when the image is not found
> Fix some issues with gtk imageview.py that show up in the example

- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/window.py
PR#535 implemented the on_exit handler, called by windowWillClose_ in window.py, but everytime with app is closed, on_exit handler will be called twice.
This PR moved the on_exit handler to applicationWillTerminate_ in app.py, to avoid the on_exit handler being called twice.
- [*] All new features have been tested
- [*] I have read the **CONTRIBUTING.md** file
- [*] I will abide by the code of conduct
Signed off by @stantonxu
> On_exit handler called in app.py by applicationWillTerminate_

- examples/multilinetextinput/multilinetextinput/app.py
- src/winforms/toga_winforms/widgets/multilinetextinput.py
MultilineTextInput example app had a 'Toggle Enabled' button which was actually toggling `readonly` property of the MultilineTextInput. This caused issue #503. Now there are two buttons: to toggle both readonly and enabled properties.
> Edit MultilineTextInput example app

- examples/dialogs/dialogs/app.py
This PR is a proposed fix for the dialog examples. The open file, save file, and folder select each cause an error rather than showing the corresponding "canceled" message when the dialog is canceled or dismissed without selecting a file. I observed this behavior when running winforms and gtk.
Also, I believe there may be an issue in the underlying gtk code but I did not address it yet because I thought it would be better for this PR to stay focused on the example code. 
The "Save file dialog was canceled" message appears twice in the action_save_file_dialog() function. That is because winforms raises a ValueError while the gtk version does not. If you'd prefer, I could make make the the gtk dialogs.save_file() function also throw a ValueError when no filename is returned from the system …
> Fix for File Dialog Examples when Canceled

- src/core/toga/handlers.py
- src/gtk/toga_gtk/app.py
This solves the same problem as https://github.com/pybee/toga/pull/538 but it adds out the possibility of handlers to accept additional positional args. Additional positional args are required by GTK `activate` event handlers, it seems.
> add positional args to handlers

- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
When rendering tree and table rows, Cocoa references columns using an ObjC string identifier. Converting those identifiers to Python strings on demand is time consuming, to the point that it observably slows rendering performance when expanding/contracting tree nodes.
This patch caches the column identifiers so that instances can be re-used, rather than re-created.
> Cache ObjC string instances used as column identifiers.

- src/core/tests/widgets/test_multilinetextinput.py
- src/core/toga/widgets/multilinetextinput.py
- src/gtk/toga_gtk/widgets/multilinetextinput.py
When trying to get Cricket to run with Gtk+, I ran cricket-unittest and was getting errors:
1. The initial value of the MultilineTextinput widget was not being set a string value
2. at_least was not being imported from travertino and was undefined
This PR fixes both of these issues.
> Bug Fixes to MultilineTextInput Widget for Gtk+

- src/gtk/toga_gtk/widgets/canvas.py
Added an argument line_dash for stroke which is called by set_dash to allow for dashed lines to be made in a canvas widget for gtk users. I'm not sure if this needs documentation as the PR Checklist indicates.
Fixes #581.
> Added dashed line support for canvas stroke

- src/cocoa/toga_cocoa/libs/webkit.py
- src/cocoa/toga_cocoa/widgets/webview.py
WKWebView isn't quite ready for prime time on cocoa, due to handling of file URLs.
> Revert usage of WKWebView on Cocoa.

- docs/tutorial/tutorial-0.rst
Changed Python invocation for Windows to py to use the Python launcher 
Changed activate to activate.bat to activate venv in Windows
> Changed invocations for Windows users before venv is activated

- docs/tutorial/tutorial-0.rst
First-time contributor! Love the work! (Please forgive me for any noobie mistakes) 
Added docs for `button.style.flex = 1` in [tutorial 0](https://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html#write-the-app) with the correct [link](https://toga.readthedocs.io/en/latest/reference/style/pack.html#flex) to main docs. ( Fixes #568 ). 
I have also removed a couple of sentences below that says the button would take up the whole width by default, as this is actually a bit misleading. (I tried it without applying flex 1, attaching screenshot).
> docs(tutorial0): fixes #568

- examples/imageview/imageview/app.py
fixes #533,  #606 both issues
The path was looking for the image in the current directory instead of the parent one. The imageview example wanted the image which was in the resources folder of the parent directory but was looking for it in the current directory which had no such folder.
- [] All new features have been tested
- [] All new features have been documented
> imageview example fixes #533, #606

- CONTRIBUTING.md
- README.rst
- setup.py
BeeWare no longer uses the https://pybee.org/ domain. I have replaced what few links I have found with the updated domain https://beeware.org/
> Fix links pointing to pybee.org

- docs/reference/api/window.rst
Update documentation snippet as first contribution.
NOTE:  `toga.App()` will error (but not crash) during runtime due to no attribute select_file() implemented in `toga-cocoa`. I ignored this in the documentation as it may complicate the example for beginners.
Documentation was originally misleading; I am a beginner to `toga` and thought it was an independent code snippet, and the snippet did not run. This code can be pasted into a file and run with python -m $FILENAME assuming correct dependencies install.
#668. This issue may remain open if the `select_file()` method is desired to be implemented and the runtime error not present in the example.
> Update documentation for Window API Reference. 

- src/core/tests/test_icon.py
- src/core/toga/icons.py
It looks like for non-system Icon resources, setting the file property did not work:
```
return os.path.join(App.app_dir, self.path)
```
Since app_dir is not defined on the App class, this was erroring out when I added a test cases for the filename property/method. 
I've made the change to basically default to the icon file path in cases where resource is specified as false.
I've added a test case for the file property/method as well. Prior to the change:
```
toga/icons.py                           31      8    74%   12, 37-42, 55, 72
```
after the change:
```
toga/icons.py                           30      3    90%   12, 53, 70
```
> Fix Icon filename property

- src/core/tests/test_icon.py
Looking at the coverage tests attempted to expand coverage to the icon.py file in core.
These changes attempt to expand coverage to the TIBERIUS_ICON method of toga.icon
- [] All new features have been documented
> Added test code for togo.icon.TIBERIUS_ICON method.

- docs/Makefile
Signed-off-by: Rico Rodriguez <rico.l.rodriguez@gmail.com>
1) Force bash as shell (see http://www.gnu.org/software/make/manual/make.html#Setting, Variables defined with := in GNU make are expanded when they are defined rather than when they are used.)
2) Evaluate/expand source dir immediately to avoid dynamic evaluation resulting in path issues
3) Remove unused virtual environment reference in docs directory.
4) Correctly reference VENV using VIRTUAL_ENV environment variable.
Prior to these changes, make install did not actually work (even with bash) - it was creating a virtual environment that never got used. With alternate shells, nothing really worked.
These changes explicitly recognize the base virtual environment as the one where dependencies should be installed, and forces bash as …
> Fix Makefile (in particular, make install)

- examples/dialogs/dialogs/app.py
- src/cocoa/toga_cocoa/dialogs.py
- src/cocoa/toga_cocoa/window.py
Added an open_file_dialog implementation the cocoa implementation. I've added a button to the dialog examples app as well.
Fixes #646
> issue #646 Implement open file dialog for osx

- src/core/tests/widgets/test_canvas.py
Added code in Canvas's Test to to cover it's clear method. 
The clear method clears all drawn objects.
> Covering test case for Canvas's clear method

- examples/dialogs/dialogs/app.py
- src/cocoa/toga_cocoa/dialogs.py
- src/cocoa/toga_cocoa/window.py
- src/core/toga/window.py
- src/gtk/toga_gtk/dialogs.py
- src/gtk/toga_gtk/window.py
- src/winforms/toga_winforms/window.py
Adds in open directory functionality in toga-cocoa, kind of copying functionality in toga-gtk. This pull request is in progress and composes PR #674 by @nehararora; will be updated and merged in after 674 is merged in.
Previously, ExampledialogsApp had an `action_select_folder_dialog` that hooked to nothing when running on macOS. This feature has been implemented as methods `select_folder()` and `select_folder_dialog()` in toga-cocoa using NSOpenPanel.
Partially resolves issue #646.
> #646 Add in open directory functionality in toga-cocoa.

- src/cocoa/toga_cocoa/keys.py
There is a typo in `toga_cocoa/keys.py` which would break [podium](https://github.com/beeware/podium).
The problem is detailed in  [The arrows seem to be not working when capslock is on #27](https://github.com/beeware/podium/issues/27)
> Fix the CAPSLOCK typo in toga_cocoa

- src/cocoa/toga_cocoa/app.py
In [podium](https://github.com/beeware/podium), the `File > Open...` button does not work. The action bound to the open command seems to be wrong.
It's due to an error in `toga_cocoa/app.py::DocumentApp::_create_app_commands`. The action bound to the open command should be `select_file` instead of `open_file`
> Fix the open command in DocumentApp

- src/core/tests/widgets/test_splitcontainer.py
Adding test coverage for line 58 of SplitContainer widget whereby the
boxes passed to the SplitContainer can have their weights preset in a
tuple.
> Test SplitContainer setting container tuple weights

- docs/tutorial/tutorial-0.rst
In Tutorial 0, code line for installing pythonnet.whl for Windows was in an incomplete tab specification, leading to a build failure.
Fixes build failure and properly displays the command.
> Sphinx was failing to build the docs because of invalid tab code.

- examples/tutorial1/tutorial/app.py
- src/winforms/toga_winforms/factory.py
- src/winforms/toga_winforms/fonts.py
- src/winforms/toga_winforms/libs.py
- src/winforms/toga_winforms/widgets/label.py
- src/winforms/toga_winforms/widgets/numberinput.py
- src/winforms/toga_winforms/widgets/textinput.py
I added font support for WinForms backend for the following widgets: `label`, `numberinput`, `textinput`. Winforms doesn't support `OBLIQUE` font style and `SMALL_CAPS` font variant, so they are ignored. 
There is a problem with label size: if label has a larger font, it does not become larger to fit the text, instead the text is cut off.
Also, there is a problem with dpi in WinForms: at the moment symbols look blurry. Pywebveiw project seems to have a solution.
> Added font support for WinForms backend

- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/libs.py
- src/winforms/toga_winforms/window.py
Currently toga Winforms apps are rendered with 96 dpi, and virtually scaled to higher dpi monitors which makes text and controls appear blurry on high dpi monitors.
This PR sets app process  to be dpi aware, which makes texts appear crisper, and makes window size smaller. It is only set so on Windows major versions higher than 6.0 (Windows Vista, apparently). 
The change can be seen on this screenshot, the dpi-aware window is on the left, and the previous dpi-non-aware window is on the right.
> Dpi-aware process for Winforms

- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/libs.py
Changed the app.py create method for toga_winforms to check the current OS Version and build number to make sure we are using the most up to date DPI setting API for the user. Came across this issue when updating windows to the 1903 update (Build #: 18362)
> Implemented DPI process bug fix

- src/gtk/toga_gtk/app.py
When executing, GTK applications report to the window manager as "__main__.py", and don't show an icon.
This sets the window manager name as the app name, and sets the icon to a 72 pixel rendition of the app icon.
> Add app name and icon to GTK apps

- src/cocoa/toga_cocoa/app.py
When an app goes full screen, the windows involved are re-homed into an NSFulLScreenWindow. This is a new instance that doesn't have any Toga representation, so we need to fill in the gaps.
- [] All new features have been documented
> Fix the toga object chain on fullscreen cocoa windows.

- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/command.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/test_command.py
- src/core/toga/app.py
- src/core/toga/command.py
- src/core/toga/window.py
- src/dummy/toga_dummy/command.py
- src/gtk/toga_gtk/app.py
- src/gtk/toga_gtk/command.py
- src/gtk/toga_gtk/window.py
- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/command.py
- src/winforms/toga_winforms/window.py
Commands in Winforms can now be enabled/disabled. 
It turns out that commands in toolbar were not added correctly. The `command._impl` was not added to `command._widgets`, which made it impossible to interact with it. Also, there was no handling of enabling/disabling commands in Winforms backend.
> Make commands in Winforms possible to enable and disable

- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/libs.py
Example app crashes on Windows 7 due to:
Issue1:
shcore is loaded on win7 despite the fact that is not available there. It is from win8.1 (what is properly noticed in comment before shcore usage).  shcore was used only once in whole code.
Issue2:
`user32.SetProcessDPIAware()` shouldn't have an argument. Documentation: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware
Tested on Windows 7 only.
- [N/A] All new features have been tested
- [N/A] All new features have been documented
> fix: load module on win7; set DPIAware on win7

- src/cocoa/toga_cocoa/widgets/multilinetextinput.py
MultilineTextInput on Cocoa didn't have options for setting font. Let's add that.
> Set font for MultilineTextInput on Cocoa

- src/cocoa/toga_cocoa/app.py
If you start your Toga application as `python myapp.py` or `myapp.py`, the name of the Python script is included as a filename to be processed. Inspect the stack, and ignore any "document" that matches the file doing the executing.
> Ignore self as a command line argument when opening documents.

- README.rst
Add `--pre` to the install instructions for toga-demo, since the demo won't work out-of-the-box without it.
> Add --pre to README instructions.

- setup.cfg
- src/android/toga_android/app.py
- src/cocoa/toga_cocoa/app.py
- src/core/toga/app.py
- src/django/toga_django/app.py
- src/dummy/toga_dummy/app.py
- src/gtk/toga_gtk/app.py
- src/iOS/toga_iOS/app.py
- src/winforms/setup.py
- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/command.py
- src/winforms/toga_winforms/icons.py
- src/winforms/toga_winforms/images.py
- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/fonts.py
- src/winforms/toga_winforms/libs/proactor.py
- src/winforms/toga_winforms/libs/winforms.py
- src/winforms/toga_winforms/widgets/base.py
- src/winforms/toga_winforms/widgets/box.py
- src/winforms/toga_winforms/widgets/numberinput.py
- src/winforms/toga_winforms/widgets/scrollcontainer.py
- src/winforms/toga_winforms/widgets/splitcontainer.py
- src/winforms/toga_winforms/window.py
Integrates the Winforms event handling lifecycle with the asyncio event loop.
This is done by instantiating a Proactor, but customizing the Proactor so that `run_forever()` is split into two parts; `setup_run_forever()` and `tick()`. The `tick()` component is what historically would have been run as a tight "while True" loop; in this version, the call to tick is scheduled to run every 5ms using the winforms event infrastructure.
It also involves some refactoring of the winforms libs - they were starting to get unwieldly, and introducing the Proactor was a good opportunity to modularize that code.
Huge thanks for @hawkowl for the many, many pointers on getting this going.
> Add Winforms-compatible asyncio Proactor.

- src/winforms/toga_winforms/widgets/textinput.py
Added placeholder implementation to TextInput in Winforms backend. 
Winforms TextInput (TextBox) doesn't have native implementation of placeholder, so I added it myself: 
- `set_placeholder` sets text for `TextInput` and changes color to gray.
- clicking on the `TextInput` selects its text. If the current `TextInput` value is the same as the `self.interface.placeholder` value, the text is deleted and text color is set to black.
- when the `TextInput` loses focus, if the user didn't type anything in and there is a placeholder value, the `TextInput` text is again set back to grayed out placeholder text.
One question I have is this: should placeholder text be returned as value of the `TextInput`? If not, I need to add one more change to the code: …
> Add placeholder implementation to textinput in Winforms

- src/gtk/toga_gtk/widgets/canvas.py
The Canvas widget has a `redraw` method that is meant to allow for
asking it to redraw itself programatically. The backend implementation
for it in GTK was so far missing. In practice this manifested itself in
having the results of method calls on the Canvas Widget not show up on
screen until a redraw event was triggered E.g. by resizing the window.
This PR adds implementation for the `redraw` method in GTK.
Signed-off-by: Barak Korren <bkorren@redhat.com>
> Make Canvas handle explicit redraws in GTK

- src/core/tests/test_icon.py
We're seeing failures in production because of test ordering.
> Add a stub toga.App to avoid test ordering failure.

- examples/canvas/canvas/app.py
- src/cocoa/toga_cocoa/widgets/canvas.py
- src/core/tests/widgets/test_canvas.py
- src/core/toga/widgets/canvas.py
- src/dummy/toga_dummy/widgets/canvas.py
- src/gtk/toga_gtk/widgets/canvas.py
- src/iOS/toga_iOS/widgets/canvas.py
When a windows containing a Canvas widget is resized, its usually
desirable to update the Canvas contents to match the new window size.
This patch provides a way to do so by introducing a `resize` event that
can be hooked into a callback.
The patch also includes an implementation of that event in GTK. It is
somewhat less straight-forward due to the fact that GTK does not seem to
include a `resize` event of its own.
Signed-off-by: Barak Korren <bkorren@redhat.com>
> Add a `resize` event to Canvas and a GTK impl.

- src/cocoa/toga_cocoa/widgets/switch.py
And yet another small tweak: Is there any reason why one cannot set the font of a ``toga.Switch`` in Cocoa? The underlying `NSButton` supports settings a font attribute.
Let me know if all those PRs get annoying. I am trying to use Toga to put together a basic UI for a command-line tool and so I'm slowly going through the widgets as I need them...
> support different fonts in `toga_cocoa.Switch`

- src/cocoa/toga_cocoa/fonts.py
When setting a Pack style with `font_weight=BOLD` in Cocoa, the setting is only used when specifying a non-system font family and ignored otherwise.
This PR fixes the behaviour, by calling `NSFont.boldSystemFontOfSize` to get the correct font.
> don't ignore `font_weight` for system font in Cocoa

- src/cocoa/toga_cocoa/dialogs.py
- src/cocoa/toga_cocoa/libs/appkit.py
The old constants `NSWarningAlertStyle` etc have been deprecated in macOS 10.13 in favour of `NSAlertStyleWarning` etc (see [AppKit docs](https://developer.apple.com/documentation/appkit/nsalertstyle?language=objc)). The values of the constants have not changed so we maintain backward compatibility.
> renamed NSAlertStyle constants

- examples/table/table/app.py
- src/winforms/toga_winforms/widgets/table.py
When changing the data source on a table, the Winforms backend didn't clear the existing content.
> Fixes #798 - Ensure winforms table is cleared when data source changes.

- docs/reference/style/pack.rst
{1,4} is in Python (and in math) set of 2 digits. It means len in... regex?
> Clarify padding type

- docs/reference/api/containers/splitcontainer.rst
Fix `direction` argument in usage example in `SplitContainer` documentation so it is applied to the `SplitContainer` and not `ScrollContainer`
This is a new pull request to replace an older pull request (#320), which has conflicts.
NOTE: the direction argument is generated as `direction = True`, which does not make sense.
Possible alternatives are:
Use `horizontal` instead of `direction`
```python
class toga.widgets.splitcontainer.SplitContainer(id=None, style=None, horizontal=False, content=None, factory=None)
```
Use strings instead of booleans
```python
class SplitContainer(Widget):
"""..."""
HORIZONTAL = 'horizontal'
VERTICAL = 'vertical'
```
Use `Enum` or (`IntEnum`?)
```python
class SplitContainer(Widget):
"""..."""
@unique
class Direction(Enum):
HORIZONTAL = 0
VERTICAL = 1
def …
```
> Fix direction argument in SplitContainer doc

- src/cocoa/toga_cocoa/widgets/base.py
- src/cocoa/toga_cocoa/widgets/box.py
- src/core/toga/widgets/base.py
This PR fixes an issue where widgets would not appear on screen if they are added to a window after it has already been shown. This affects `toga_cocoa` but may be an issue with other backends as well.
The underlying fixes involve changes to both `toga_core` and `toga_cocoa`.
Changes to toga core:
- When a child is added to a widget, update its `window` attribute. Previously, only its `app` was updated.
- When `content` is added to a widget, update the content's `window` and `app`. I am not sure how "content" semantically differs from having a single child and which widgets can have content. At the moment, I am only aware of `ScrollContainer` and `Window`.
Changes to toga_cocoa:
- When a child is added to a widget, this is done by setting the child's `container` to the parent widget. This …
> Fix missing window content when added after `show` has been called

- examples/tree_source/README.rst
- examples/tree_source/tree_source/app.py
The `tree` example has a selection handler, but `tree_source` did not. It might be unclear to some, so I thought I'd add one for the `tree_source` example because it's a little different.
Also I could be wrong but I believe that readme defines the `tree` example with the movies, not the `tree_source` example with FileSystemSource.
> Added selection handler to tree_source example

- src/core/toga/app.py
As pointed out by #818, Toga crashes if the app code is in a single file, and the app is started using the `-m` flag.
There are a number of edge cases that need to be accounted for:
* Code in an `appname.py` file, started with `python appname.py`
* Code in an `appname.py` file, started with `python -m appname`
* Code in an folder named `appname` with a `__main__.py`, started with `python -m appname`
* Code that has an app_name set in the constructor of toga.App that *doesn't* match a module on the PYTHONPATH
* Code that has an app_name set in the packaging metadata that *doesn't* match a module on the PYTHONPATH
> Fixed #818 - Correct app module detection.

- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/libs/foundation.py
- src/cocoa/toga_cocoa/widgets/canvas.py
In getting graphics context on MacOS, first try `NSGraphicsContext.currentContext.graphicsPort()` and if `TypeError` is raised, try `NSGraphicsContext.currentContext.CGContext`.
Fixes `TypeError: 'int' object is not callable` in MacOS 10.15
Fixes #815
> Try getting CGContext if call to graphicsPort() raises TypeError

- examples/button/button/app.py
- src/cocoa/toga_cocoa/window.py
- src/core/toga/app.py
Signed-off-by: Ignacio Cabeza <ignaciocabeza@gmail.com>
When Window `resizable` property is `False`, the constraint `_min_width_constraint` and `_min_height_constraint`  is using `NSLayoutRelationEqual`. This causes not desired behaviour with the size of the `Window`. I changed to always use `NSLayoutRelationGreaterThanOrEqual`
Before change:
After change:
> Use defined size when resizable is False (Window/Cocoa)

- src/android/toga_android/paths.py
- src/cocoa/toga_cocoa/paths.py
- src/core/toga/icons.py
- src/core/toga/images.py
- src/dummy/toga_dummy/paths.py
- src/gtk/toga_gtk/paths.py
- src/iOS/toga_iOS/paths.py
- src/winforms/toga_winforms/paths.py
In some environments (E.g. web client) the use of `pathlib` does not make sense.
Move all the places where `pathlib.Path` objects are allocated in the interface layer down to the backends layer so that in platforms where `pathlib` does not exist the factory could provide an alternative.
> Remove dependencies on pathlib from the interface layer

- src/winforms/toga_winforms/widgets/table.py
- Enable double buffering
- Use `BeginUpdate()` and `EndUpdate()` to bundle multiple changes to table
Improves visual performance in frequently changing tables by removing flicker and making updates faster.
> Winforms table performance improvements

- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/widgets/detailedlist.py
- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
- src/winforms/toga_winforms/widgets/table.py
Implementing a fix suggested by @yconst, ensure that row content for Winforms tables are always cast to strings; and, if the content potentially contains an icon, that the icon is stripped out.
> Fixes #824 - Ensure that winforms table content is always a string

- examples/button/button/app.py
- src/core/toga/widgets/button.py
Set `self.enabled` property explicitly during init. Setting the property as part of super init has no effect because `_impl` is still `None`. Other components set the property in a similar manner.
Addresses Button cannot be set to not be enabled upon initialization.
> Explicitly set enabled property for Button in init

- src/winforms/toga_winforms/app.py
Stacktrace is not printed correctly.
When throwing stack trace in windows platform, the error message is not always ending with `"\\n']   at Python"`. I added a try-except close that can handle cases it doesn't
> Fix bug with running toga in windows.

- src/core/toga/widgets/detailedlist.py
It changes the key names for the data of detailed_list from "icon", "label1", and "label2" to "icon", "title", "subtitle" in the toga core, because both the macOS and iOS implementation if detailed list use these key names. I didn't test the iOS implementation since I don't have an iPhone.
It solves an issue where the default key names doesn't match the keywords of the implementation.
It fixes #707 
I think it also relates to #747
> fixes #707: Change key names for detailed_list

- src/android/toga_android/app.py
- src/android/toga_android/factory.py
- src/android/toga_android/icons.py
- src/android/toga_android/libs/__init__.py
- src/android/toga_android/libs/activity.py
- src/core/toga/icons.py
- src/core/toga/platform.py
This pull request makes minimal changes in toga_android so that it starts up using rubicon-java for communication between Python and Android, as well as the current Python-Android-support and gradle cookiecutter template.
I did take the liberty of removing commented-out code in this PR.
The `not_implemented` function is duplicated into `icons.py` (from `factory.py`, where it remains). This is because I want to avoid circular dependencies, and presumably I’m going to implement Icon at some point, so the duplication will go away.
Note that rubicon-java is available due to Python-Android-support bundling it, and therefore it's not specified anywhere in an explicit dependency list. This is totally OK with me for now, but I wanted to flag it in case it merits further thought.
Here's how I …
> Rely on rubicon-java for Android implementation

- src/android/toga_android/app.py
This is similar to how the Toga backend for Cocoa calls user app startup code.
Without this, user apps don't even really launch. 🤦 
I validated this by adding a `print()` to my `class HelloWorld`'s `def startup(self)` method in my sample app, and validated that it gets printed to the Android log with this change.
Before this change, it would not get printed.
(Additionally, my app creates a `Button`. This now successfully crashes. This is good news; I'll figure out how to make buttons :))
> Call user app startup code on Android

- src/core/tests/widgets/test_detailedlist.py
- src/core/toga/widgets/detailedlist.py
Added 3 tests to test on_delete, on_refresh and on_select functionalities on DetailedList class.
> Making the detailedlist coverage to be 100%

- src/core/tests/widgets/test_timepicker.py
- src/core/toga/__init__.py
- src/core/toga/widgets/timepicker.py
- src/dummy/toga_dummy/factory.py
- src/dummy/toga_dummy/widgets/timepicker.py
- src/winforms/toga_winforms/factory.py
- src/winforms/toga_winforms/widgets/timepicker.py
This PR implements a time picking widget on Windows and related tests. 
Below is the TimePicker widget in action with 11:15 AM set as the **max_time** and 11:00 AM set as the **min_time**. Also in action is the **on_change** automatically updated the toga label. 
Overall, pretty similar in concept to the DatePicker widget with the exception of the min_time and max_time implementation not being strictly native, but it works!
> Add windows TimePicker Widget 

- src/gtk/toga_gtk/widgets/box.py
Propagate the box x,y offsets to the children
Without this,  widgets appear offset up and left, putting them partially outside the app bounding box.
Signed-off-by: Eliot Blennerhassett <eliot@blennerhassett.gen.nz>
Fixes  #139 (maybe)
> Fix box children layout with gtk on wayland

- src/gtk/toga_gtk/widgets/numberinput.py
Modify `NumberInput` widget `on_change` behavior under **gtk** implementation.
Previously, `on_change` event was only being called when submitting the value by pressing the ENTER key or unfocusing the widget. 
Now the callback is called every time a character is inserted/deleted inside the `Entry` box.
This value is only accessible as a string, so an extra step is needed to convert it to a valid numeric format (`.replace(",", ".")`) and we need to take into account the empty string case, which we take as a zero value.
This PR refers to a bug found during the PyCon 2020 Virtual Sprint.
> make on_change event trigger with every key stroke

- src/gtk/toga_gtk/app.py
What was in the Appmenu becomes a menu item with the name of the application.
Move the About item into the Help menu where all other apps have it.
Fix a small bug in the Quit menu item.
Appearance is consistent Wayland vs X11, whether Gnome shell has appmenu visible or not.
Fixes #872
> Gtk  all menu items in standard menubar.

- src/android/setup.py
- src/android/toga_android/app.py
- src/android/toga_android/dialogs.py
- src/android/toga_android/layout.py
- src/android/toga_android/libs/__init__.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/button.py
- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/passwordinput.py
- src/android/toga_android/widgets/textinput.py
- src/android/toga_android/window.py
This pull request adjusts the Android implementation to pass `flake8`.
The reason I want to do this now, rather than later, is that as I write new code and test it on Android, I find myself writing code that would obviously crash, but I don't see it until it crashes on-device, which I find to be a painful waste of a ~2 minute debug loop, and I'd rather have `flake8` warn me first.
@freakboy3742 already gave me permission to delete the old Android code, but for now I like having it around, since it helps remind me of how things are going to work in the future.
I booted up my example app from https://github.com/beeware/toga/pull/853 and verified that it continues to not crash.
> Adjust Android implementation minimally to pass flake8

- src/dummy/toga_dummy/test_implementation.py
I'm submitting this change in the hopes of improving the error messages people will get as they add/modify Toga backends. I'm open to other implementation ideas.
When working on a different pull request, I found myself staring at `pytest` output that said:
```
==============================================================================
FAIL: tests/test_implementation.py::MainWindowImplTest::test_class_exists
------------------------------------------------------------------------------
File "/Users/asheesh/projects/beeware/beeware-tutorial/toga/src/dummy/toga_dummy/test_implementation.py", line 266, in fn
self.assertIn(element, element_list, msg=error_msg if error_msg else fn.__doc__)
File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Vers …
```
> In autogenerated assertions, provide fn.__doc__ as error_msg

- src/android/toga_android/app.py
- src/android/toga_android/factory.py
- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/box.py
- src/android/toga_android/widgets/button.py
- src/android/toga_android/window.py
Add Button widget for Android implementation
I tried to make this PR pretty minimal. I ended up having to minorly modify some semi-unrelated stuff. We can discuss in code review comments.
Using this app https://github.com/paulproteus/briefcase-toga-button-app-with-hacks , I get this screenshot when I launch:
The button does log its `on_press()` handler if you look in `.../adb logcat -s stdio`:
```
04-27 22:50:50.364 17953 17970 D stdio   : Hello, world! from Android Toga app
```
> Add Android Button widget

- examples/canvas/canvas/app.py
- src/cocoa/toga_cocoa/widgets/selection.py
- src/winforms/toga_winforms/fonts.py
- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/fonts.py
- src/winforms/toga_winforms/libs/winforms.py
- src/winforms/toga_winforms/widgets/canvas.py
Added support for:
The drawing of tutorial 4 seems to be rendered fine:
But when I add the text box:
I can't seem to find the reason for that. I checked if there's an anchoring problem, but seems like it is not the case. I suggest merging this pull request and I'll try figuring out what's wrong in another pull request. If there's another Windows developer that can take a look at it, It would be great.
> More windows canvas abillities

- src/winforms/toga_winforms/colors.py
Validates that the received rgb is integer based
when running *Toga Chart* got the following error:
```
File "c:\\users\\saroa\\repositories\\toga\\src\\winforms\\toga_winforms\\widgets\\canvas.py", line 65, in create_brush
return SolidBrush(native_color(color))
File "c:\\users\\saroa\\repositories\\toga\\src\\winforms\\toga_winforms\\colors.py", line 14, in native_color
color = Color.FromArgb(int(c.rgba.a * 255), c.rgba.r, c.rgba.g, c.rgba.b)
TypeError : No method matches given arguments for FromArgb
```
This is happening because the color values are calculated as `255 * value`, which results in a **float** values instead of **int**. In order to make sure that this kind of problems won't happen, added a value check close to the place where it is needed
> Fix bug in windows colors

- examples/canvas/canvas/app.py
This is done in order to show usage of move in one stroke.
> Add move example to canvas

- docs/tutorial/tutorial-0.rst
Add instruction on the tutorial to invite user to read prerequisites instruction.
That fixes installation issues like #697.
- **All new features have been tested**: inapplicable
- **All new features have been documented**: inapplicable
- **I will abide by the code of conduct**: not found :/
> Add prerequisites instructions

- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/box.py
- src/android/toga_android/window.py
Also:
- Use Android's built-in way to find the DPI for self.dpi
(this reports 420 on my Android Virtual Device)
- Measure width & height as needed in `AndroidViewport`
- Remove now-unnecessary `add_child()` method on `Box`; we can rely on
the base `Widget` class's existing `add_child()`.
This implementation waits for `show()` before actually making the window
visible. This works great, but it has the mild downside that it's possible
to `show()` a `Window` that has no widgets inside it, which is somewhat
ill-defined.
With this demo app -- https://github.com/paulproteus/briefcase-toga-button-demo-app/blob/master/src/helloworld/app.py -- you get this screenshot:
Simple, but nice.
- [] All new features have been documented
> Use `Window` as container; set `viewport` everywhere

- src/cocoa/toga_cocoa/widgets/multilinetextinput.py
Signed-off-by: Ignacio Cabeza <ignaciocabeza@gmail.com>
Fixed `set_value` because `clear()` was not working
Fixed `set_placeholder`
> Fix for set_value and placeholder in multilinetextinput [Cocoa]

- examples/canvas/canvas/app.py
- src/cocoa/toga_cocoa/widgets/canvas.py
- src/core/tests/widgets/test_canvas.py
- src/core/toga/widgets/canvas.py
- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/winforms.py
- src/winforms/toga_winforms/widgets/canvas.py
Fixed bug in `Canvas` fill rule in *toga core* and *toga coca*. also added to `Canvas` example usage of fill rule:
Stroke:
Nonzero fill rule:
Evenodd fill rule:
> Canvas fill rule bug

- src/winforms/toga_winforms/widgets/canvas.py
Fixed the `Canvas` example doesn't work drawing the "triangles" example in WIndows
> Fix canvas "triangles" example in windows

- src/android/toga_android/factory.py
- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/box.py
- src/android/toga_android/widgets/button.py
- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/textinput.py
- src/android/toga_android/window.py
This PR adds `TextInput` and `Label`. It begins to do layout as well.
<details>
<summary>
Sample code `app.py`:
</summary>
```python
"""
My first application
"""
import toga
from toga.constants import RIGHT
main_box = toga.Box(style=Pack(direction=COLUMN))
name_label = toga.Label(
'Your name: ',
style=Pack(padding=(0, 5))
)
self.name_input = toga.TextInput(style=Pack(flex=1))
main_box.add(name_label)
main_box.add(self.name_input)
button = toga.Button(
'Say Hello!',
on_press=self.say_hello,
style=Pack(flex=1)
)
print("HELLO BUTTON DO NOT GO AWAY", button)
main_box.add(button)
print("main_box added the button, so where did it go")
self.main_window = …
```
> Add `TextInput` and `Label` widgets; start doing layout

- examples/canvas/canvas/app.py
- src/cocoa/toga_cocoa/widgets/label.py
- src/cocoa/toga_cocoa/widgets/slider.py
- src/core/tests/widgets/test_slider.py
- src/core/toga/widgets/slider.py
- src/gtk/toga_gtk/widgets/slider.py
- src/winforms/toga_winforms/widgets/slider.py
Added a "translate" example for `Canvas`:
This had surfaced two bugs in cocoa:
1. `Slider` set_value method didn't work - fixed that
2. `Label` text is cut for some reason (see "X Translate") - Didn't investigate the problem. I'll try to take a look at it in another PR.
> Canvas translate example

- examples/textinput/textinput/app.py
- src/cocoa/toga_cocoa/widgets/label.py
- src/cocoa/toga_cocoa/widgets/passwordinput.py
- src/core/toga/widgets/passwordinput.py
- src/core/toga/widgets/textinput.py
`PasswordInput` now inherits from `TextInput`, which allows it to use all `TextInput` functionalities, including `on_change`.
Fixes #895
> Password input on change

- src/android/toga_android/app.py
- src/android/toga_android/dialogs.py
- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/window.py
Add an Android info dialog.
<details>
<summary>
Sample app code
</summary>
```python
"""
My first application
"""
import toga
from toga.constants import RIGHT
main_box = toga.Box(style=Pack(direction=COLUMN))
name_label = toga.Label("Your name: ", style=Pack(padding=(0, 5)))
self.name_input = toga.TextInput(style=Pack(flex=1))
name_box = toga.Box(style=Pack(direction=ROW, padding=5))
name_box.add(name_label)
name_box.add(self.name_input)
button = toga.Button(
"Say Hello!", on_press=self.say_hello, style=Pack(padding=5)
)
main_box.add(name_box)
main_box.add(button)
self.main_window = toga.MainWindow(title=self.formal_name)
self.main_window.content = main_box …
```
> Add Dialog

- examples/canvas/canvas/app.py
This is another example of `Canvas`. Now one can rotate the drawings:
> Added rotation example to Canvas

- src/android/toga_android/widgets/textinput.py
Call `toString()` so that we get a Java string, which rubicon-java converts to a Python string.
Without this, sample code below (== https://toga.readthedocs.io/en/latest/tutorial/tutorial-1.html ) prints `float() argument must be a string or a number, not 'java/lang/CharSequence'`.
<details>
<summary>
Sample code (from Toga tutorial 2)
</summary>
```python
import toga
from toga.style.pack import *
def build(app):
c_box = toga.Box()
f_box = toga.Box()
box = toga.Box()
c_input = toga.TextInput(readonly=True)
f_input = toga.TextInput()
c_label = toga.Label("Celsius", style=Pack(text_align=LEFT))
f_label = toga.Label("Fahrenheit", style=Pack(text_align=LEFT))
join_label = toga.Label("is equivalent to", style=Pack(text_align=RIGHT))
def calculate(widget):
try:
c_input.value = …
```
> Return a Python string from Android TextInput

- src/android/toga_android/widgets/textinput.py
For `set_alignment()`, the only testing I did was to ensure it doesn't crash. I'll test alignment more once I fix layout to have proper widths for these element.
For `set_readonly()`, I tested by validating that a `TextInput` which is not `editable`, if I click it, the app doesn't react.
For `set_placeholder()`, I added `C` placeholder to the Celsius `TextInput`. It does indeed show up, nicely grayed-out.
<details>
<summary>
Sample code -- very similar to Toga tutorial 2, but with two changes to test the above
</summary>
```python
import toga
from toga.style.pack import *
def build(app):
c_box = toga.Box()
f_box = toga.Box()
box = toga.Box()
c_input = toga.TextInput(readonly=True, placeholder="C")
f_input = toga.TextInput()
c_label = toga.Label("Celsius", style=Pack(text_align=LEFT)) …
```
> Add placeholder, alignment, and readonly to Android TextInput

- examples/switch/switch/app.py
Change the window size of the switch example
The window height was too small to display the third checkbox.
Removed unused variable.
It is no longer required to resize the window (height) to see the third checkbox.
> Change the window size of the switch example 

- src/cocoa/toga_cocoa/app.py
- src/core/tests/test_app.py
- src/core/toga/app.py
- src/gtk/toga_gtk/app.py
- src/winforms/toga_winforms/app.py
This allows mobile platforms where app icons are meaningless to avoid
unnecessarily binding the icon.
I still need to manually test these changes. I'm doing that now.
> Bind app icons in platform layer, not interface layer

- examples/slider/slider/app.py
- src/cocoa/toga_cocoa/widgets/slider.py
- src/core/tests/widgets/test_slider.py
- src/core/toga/widgets/slider.py
- src/dummy/toga_dummy/widgets/slider.py
- src/gtk/toga_gtk/widgets/slider.py
- src/iOS/toga_iOS/widgets/slider.py
- src/winforms/toga_winforms/widgets/slider.py
Added the option to mike slider discrete/continuous. This is helpful when you want integer values vs float values from the slider.
Implemented in Windows and OS. This will print "not_implemented" message in GTK and iOS
Fixes #893
> Slider can be descrete or continous

- examples/optioncontainer/README.rst
- examples/optioncontainer/optioncontainer/__init__.py
- examples/optioncontainer/optioncontainer/__main__.py
- examples/optioncontainer/optioncontainer/app.py
- examples/optioncontainer/optioncontainer/resources/README
- examples/optioncontainer/pyproject.toml
- src/cocoa/toga_cocoa/widgets/optioncontainer.py
- src/cocoa/toga_cocoa/widgets/selection.py
- src/core/toga/widgets/optioncontainer.py
- src/core/toga/widgets/selection.py
- src/dummy/toga_dummy/widgets/optioncontainer.py
- src/gtk/toga_gtk/widgets/optioncontainer.py
- src/gtk/toga_gtk/widgets/selection.py
- src/winforms/toga_winforms/widgets/optioncontainer.py
Signed-off-by: Ignacio Cabeza <ignaciocabeza@gmail.com>
Added method to enable or disable an option of the OptionContainer for Cocoa
This is a WIP. 
```python
import toga
from toga.constants import COLUMN, ROW
class ExampleApp(toga.App):
def on_enable(self, button):
self.optioncontainer.set_option_enabled(1, True)
def on_disable(self, button):
self.optioncontainer.set_option_enabled(1, False)
self.main_window = toga.MainWindow(title="Test Window")
self.button = toga.Button('enable tab 1', on_press=self.on_enable)
self.button2 = toga.Button('disable tab 1', on_press=self.on_disable)
box1 = toga.Box()
box2 = toga.Box()
self.optioncontainer = toga.OptionContainer()
self.optioncontainer.add('Option1', box1)
self.optioncontainer.add('Option2', …
```
> Enable or Disable tab in optionContainer

- src/android/toga_android/widgets/numberinput.py
- src/android/toga_android/widgets/textinput.py
This makes TravelTips work. See screenshot.
Layout is still broken-ish, but that's separate IMHO.
In the process, I noticed that `NumberInput` stores the `value` as a property of the `interface`, but `TextInput` does not (it uses a `get_value()` method). That's fine, but it seems a little weird.
I also fixed a problem where setting these to readonly would in fact make them not store any value. :)
I did manually test the `TextInput` as well by adding a `toga.TextInput` to TravelTips with an on_change() function that prints the value. It works fine. :)
> Fix on_change & value fetching for NumberInput, TextInput

- src/core/tests/widgets/test_numberinput.py
- src/core/toga/widgets/numberinput.py
`NumberInput` widget should have the ability to construct with a default value.
> Added the option to add default value to NumberInput

- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/widgets/button.py
- src/winforms/toga_winforms/widgets/numberinput.py
- src/winforms/toga_winforms/widgets/slider.py
- src/winforms/toga_winforms/widgets/splitcontainer.py
- src/winforms/toga_winforms/widgets/switch.py
- src/winforms/toga_winforms/widgets/timepicker.py
- src/winforms/toga_winforms/window.py
* Removes unnecessary subclasses for Winforms native widgets
* Introduces a consistent naming convention for Winforms native event handlers
* Introduces protection against event handlers firing until the widget is actually visible.
> Cleanup of Winforms widget events.

- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/textinput.py
- src/android/toga_android/window.py
Before this change, `AndroidViewport` was providing a screen
width of 0 to the layout engine. This meant that layout would
assume there was no spare space, so something `at_least(N)`
pixels wide would always be rendered at `N` pixels wide --
no space for anything else.
This commit also fixes other widgets so they look better.
By the way, there are a bajillion ways to measure text on Android. One would hope that `measure()` would do it, but nope. I did one of the ones that works. I'm proud of it. :D I'm a little confused how anyone successfully writes code against Android.
See TravelTips screenshot.
Note that `My curr...` is truncated. I think this is because TravelTips hard-codes a width for that widget. I haven't even checked if it does, but hey, it works fine with a modified Toga …
> Fix layout, mostly by computing width properly

- src/cocoa/toga_cocoa/widgets/canvas.py
Refs beeware/toga_chart#9
The `reset_transform()` method on the macOS canvas was operating by attempting add an inverse transform. For some reason, this was resulting in an incomplete inversion.
This patch updates the mechanism to take a snapshot of a "clean" transform at when the draw context is created, and restores that snapshot when reset is invoked. As the transform state is a stack, a clean transform is immediately re-snapshotted so there is always exactly 1 transform in the stack.
> Correct the implementation of reset_transform on Cocoa canvas

- examples/canvas/canvas/app.py
- examples/tutorial4/tutorial/app.py
- src/cocoa/toga_cocoa/fonts.py
- src/cocoa/toga_cocoa/widgets/canvas.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/test_font.py
- src/core/toga/widgets/canvas.py
- src/core/toga/window.py
- src/dummy/toga_dummy/fonts.py
- src/dummy/toga_dummy/test_implementation.py
- src/dummy/toga_dummy/widgets/canvas.py
- src/gtk/toga_gtk/fonts.py
- src/gtk/toga_gtk/widgets/canvas.py
- src/iOS/toga_iOS/fonts.py
- src/iOS/toga_iOS/widgets/canvas.py
- src/winforms/toga_winforms/widgets/canvas.py
- src/winforms/toga_winforms/window.py
Since the API for `Font.measure` has been changed to include the `dpi` as a parameter, the `Canvas` example is failing. This PR fixes that.
In order to fix the problem I had to add a `dpi` property to `Canvas`. I think it is reasonable that the `Canvas` should have this property since it is the main widget that will need to take it under consideration. Another option is to add this property to `Window` and to call it via `canvas.window.dpi`, but I don't think it's a good design.
Would love to hear your feedback on this.
I implemented the `dpi` property in *Windows* and *Cocoa*, but I guess you need to do the same for *GTK* and other platforms
1. Run the `Canvas` example.
2. Choose the *text* shape
3. A syntax error is raised
> Fix failing canvas example

- src/dummy/toga_dummy/test_implementation.py
- src/dummy/toga_dummy/widgets/activityindicator.py
- src/dummy/toga_dummy/widgets/canvas.py
- src/winforms/toga_winforms/widgets/optioncontainer.py
- src/winforms/toga_winforms/widgets/table.py
API compliance is tested by comparing against the Dummy API backend; however, the list of files being compared is statically listed. This has lead to widgets *not* being added to the list, and as a result, API discrepancies not being detected.
This PR makes the dummy API compliance list dynamic, based on the files that are present in the dummy backend.
> Fix dummy API test coverage.

- examples/canvas/canvas/app.py
Changed in the `Canvas` example to use mouse events such as `on_press`, `on_drag`, `on_release`, etc. in order to translate and rotate the image instead of using `Slider` instances.
This is done in order to later implement those methods in *Windows* and see if they work.
> Add mouse events to Canvas example

- demo/pyproject.toml
- demo/setup.py
Something evidently broke during the toga-demo release process for 0.3.0dev19, because it hard-codes a dependency on 0.3.0.dev18. 
The pyproject.toml PEP517 build dependecy is one possible cause of the problem.
> Fixes #927 -- Correct version pinning in toga-demo.

- src/winforms/toga_winforms/widgets/optioncontainer.py
Added all the missing methods from Winforms implementation.
Signed-off-by: Olga <obulat@gmail.com>
Added option label setter and getter, option enabled setter and getter, and setter for option change handler.
This change gets rid of all `Not implemented` warnings for OptionContainer widget in Winforms backend..
> Implement missing methods in Winforms OptionContainer

- examples/layout/README.rst
- examples/layout/layout/app.py
- src/cocoa/toga_cocoa/widgets/base.py
This fixes rendering issues on macOS when adding children to a `toga.Box` after the Box has been created but before it acquires a window. The related issue is #937.
This PR has the following changes:
- Fixes prematurely setting a wrong container for `toga_cocoa.Widget`.
- Introduce and use the `viewport` property to check if a widget is top-level, i.e., the content of a window or another widgets.
- Raise a RuntimeError when trying to set a container if a widget already has one. This prevents `native.addSubview` from being called twice and should hopefully prevent regressions.
> [WIP] rendering fixes

- src/android/toga_android/window.py
- src/cocoa/toga_cocoa/libs/__init__.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/style/test_pack.py
- src/core/toga/style/pack.py
- src/gtk/toga_gtk/libs/__init__.py
- src/gtk/toga_gtk/widgets/canvas.py
- src/gtk/toga_gtk/window.py
- src/iOS/toga_iOS/window.py
- src/winforms/toga_winforms/window.py
This allows us to give Android a `baseline_dpi` of 160.
I've also added one automated test to `test_pack.py`.
Screenshots:
macOS -- looks unchanged with my helloworld app
Android **with this change** -- widgets are no longer too far off to the right
Android **before this change** -- widgets are too far off to the right
I manually tested on Android, macOS, and iOS. I haven't manually tested the GTK or Winforms backends, but I think that's OK in this case. Happy to test there if it's important.
> Create `baseline_dpi` on each platform

- src/cocoa/toga_cocoa/widgets/internal/cells.py
- src/cocoa/toga_cocoa/widgets/table.py
- src/core/tests/widgets/test_table.py
- src/core/toga/sources/list_source.py
- src/core/toga/widgets/table.py
Following PR #784, this PR migrates the `toga_cocoa.Table` from a cell-based to a view-based NSTableView. This has several advantages:
- Significant performance improvements, especially when resizing a window with a Table.
- Allows embedding of arbitrary widgets as table cells.
- Automatically adjusts the row height to its content.
Examples for embedding widgets are currently still missing since this feature is not yet cross-platform (see #841 for a discussion of Windows implementations).
> View-based NSTableView

- src/core/toga/platform.py
Per discussion at https://github.com/beeware/Python-Android-support/issues/8 , we can detect that we're running on Android the same way the CPython test suite detects it's running on Android.
This is pretty trivial, but I want to submit this pull request because (a) it deletes unused code (I can't find a situation where `sys.platform` is `android`) and (b) IMHO it simplifies life for other people who might want to integrate Toga into their own Android-Python packaging ecosystem, since we and the stdlib are doing things the same way. I am personally aesthetically very much attracted to the idea of consistency between us and CPython upstream.
Using this Toga library, I booted up a helloworld app on Android, and indeed it launched properly. :)
> Detect Android the same way as the CPython test suite

- nursery/curses/setup.cfg
- nursery/flask/setup.cfg
- nursery/pyramid/setup.cfg
- nursery/qt/setup.cfg
- nursery/tvOS/setup.cfg
- nursery/uwp/setup.cfg
- nursery/watchOS/setup.cfg
- nursery/web/setup.cfg
- src/android/setup.cfg
- src/cocoa/setup.cfg
- src/django/setup.cfg
- src/dummy/setup.cfg
- src/gtk/setup.cfg
- src/iOS/setup.cfg
- src/winforms/setup.cfg
#943 changes the packaging metadata to be based on setup.cfg; however, due to having some stale wheels locally, I didn't notice that the root package contents of all the backends were not being included in the package.
> Correct packaging error.

- src/core/tests/widgets/test_table.py
Create a test if the accessor is already in use.
- [ x I will abide by the code of conduct
> coverage: line 162 of table.py - ValueError: accessor in use

- src/android/setup.py
- src/android/toga_android/app.py
Also bump `rubicon-java` dependency to as-yet-unreleased version containing that event loop.
See also https://github.com/beeware/rubicon-java/pull/49
I have **not** tested this, not even started it up! Once we release rubicon-java 0.2.2, I/you can test and fix if needed. I think it's OK, though. It's basically copy-pasta from my sample app. :)
> Start the Android event loop, for the benefit of user code calling asyncio

- src/iOS/toga_iOS/widgets/box.py
Signed-off-by: Isaiah Hewitt <isaiah@hewitts.us>
Added dark mode for iOS 13+.  For earlier versions without dark mode, the background color is white by default.
In dark mode, the background color defaults to black, and text defaults to white.
#856
> iOS supports dark mode

- src/android/toga_android/factory.py
- src/android/toga_android/widgets/passwordinput.py
Use `setInputType` & numeric input classes to configure Android TextInput to support password input.
I used an app with the following `app.py`.
```
"""
My first application
"""
import toga
main_box = toga.Box(style=Pack(direction=COLUMN))
name_label = toga.Label("Your name: ", style=Pack(padding=(0, 5)))
self.name_input = toga.PasswordInput(style=Pack(flex=1))
name_box = toga.Box(style=Pack(direction=ROW, padding=5))
name_box.add(name_label)
name_box.add(self.name_input)
button = toga.Button(
"Say Hello!", on_press=self.say_hello, style=Pack(padding=5)
)
self.button = button
main_box.add(name_box)
main_box.add(button)
self.main_window = toga.MainWindow(title=self.formal_name) …
```
> Enable & fix PasswordInput on Android

- docs/reference/api/widgets/divider.rst
Update the headline for the divider widget in the API Reference documentation in order to correctly identify the widget.
> Update headline in divider.rst

- src/android/toga_android/factory.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/multilinetextinput.py
- src/android/toga_android/widgets/numberinput.py
- src/android/toga_android/widgets/selection.py
- src/android/toga_android/widgets/textinput.py
Screenshot:
It works "great" except for the layout bug in #968 (sample code to test this is also in that PR).
> Add Android multi-line text input

- src/winforms/toga_winforms/widgets/box.py
- src/winforms/toga_winforms/widgets/button.py
- src/winforms/toga_winforms/widgets/label.py
Have added the ability to set text color and background color for label and button widgets in windows.
> set color on label & button widgets on windows

- src/core/toga/widgets/divider.py
This PR fixes and issue when instantiating a Divider widget. This issue was introduced by #974 which calls `rehint` while applying a style. This is called when the implementation instance is created and causes an AttributeError because `toga_cocoa.Divider.rehint` accesses the `toga.Divider._direction` attribute of the interface before it has been set.
> Bug fix for Divider

- docs/reference/api/widgets/activityindicator.rst
- src/cocoa/toga_cocoa/widgets/activityindicator.py
- src/core/tests/widgets/test_activityindicator.py
- src/core/toga/widgets/activityindicator.py
- src/dummy/toga_dummy/widgets/activityindicator.py
- src/gtk/toga_gtk/widgets/activityindicator.py
As discussed in #975, this PR removes the "hide when stopped" property of the ActivityIndicator. The ActivityIndicator is now always hidden when not spinning. There are two reasons for this change:
* The functionality is rarely used. There is little benefit from showing an ActivityIndicator when not spinning.
* Some platforms such as Gtk don't support this natively.
> Remove "hide when stopped" functionality from ActivityIndicator

- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
This PR improves the appearance of Table and Tree widgets in Cocoa. In particular:
* Minimum row heights are no longer hard-coded but taken from the platform default. This is also in preparation for macOS Big Sur where the NSOutlineView and NSTableView have a new `style` attribute to change their appearance, including the row height, depending on the context they are shown in.
* The Table widget now has alternating row colors.
> Tableview style improvements

- src/cocoa/toga_cocoa/widgets/base.py
- src/cocoa/toga_cocoa/widgets/box.py
As described in #976, setting the background color for a Box with the Cocoa backend raises AttributeError. This PR aims to fix this with the following changes:
* A TRANSPARENT background color is handled in the Cocoa backend by setting `self.native.drawsBackground = False`.
* The implementation of `set_background_color` is moved from the Box widget to the base Widget because all Cocoa Views have a background color attribute.
> Handle transparent background color in Cocoa

- src/cocoa/toga_cocoa/colors.py
- src/cocoa/toga_cocoa/widgets/base.py
This fixes an issue introduced by #1002 where the background color of all Cocoa views would default to `windowBackgroundColor`. This does not make sense for some widgets such as text fields (white background). The background color now defaults to `None` instead. As far as I can see, this gives the correct behaviour for all widgets. But maybe there are corner cases which I missed?
There is also a subtle difference in macOS Big Sur between explicitly setting the background color to `windowBackgroundColor` and not setting it at all. Not setting the background color gives a slightly brighter background which seems to be the default for built-in apps.
Apologies for not testing the previous PR sufficiently.
> Fix defaulting to windowBackgroundColor

- src/android/toga_android/factory.py
- src/android/toga_android/fonts.py
- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/box.py
- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/multilinetextinput.py
- src/android/toga_android/widgets/numberinput.py
- src/android/toga_android/widgets/textinput.py
Add Android font support for text widgets (Label, NumberInput, TextInput) including bold & italic & font size.
This does not add fantasy or cursive support. Those are a smidge more complicated, and I'd prefer to add those in a separate pull request.
Screenshot of TravelTips now:
Feedback welcome.
Sometimes, calls to Android `measure()` will throw `NullPointerException`. For some widgets, they need `LayoutParams` (which are only added in Toga when a widget gets added to a container) before `measure()` can be called. This does an explicit check for `None` in those cases, which does the job fine, so I propose we roll with it.
> Add Android font support

- src/cocoa/toga_cocoa/widgets/canvas.py
- src/iOS/toga_iOS/widgets/canvas.py
- src/winforms/toga_winforms/widgets/canvas.py
#984 made some small changes to font binding, but there were some edge cases that were missed.
> Corrected some font binding problems.

- src/cocoa/toga_cocoa/widgets/internal/refresh.py
The scroll direction on DetailedList on Cocoa was the opposite to what it should be.
> Fixes #690 -- corrects the scroll direction on Cocoa DetailedList.

- src/iOS/toga_iOS/app.py
- src/iOS/toga_iOS/widgets/detailedlist.py
Refresh handling on iOS incorrectly referred to the UIRefeshControl, so the refresh control would never disappear.
> Correct after_on_refresh handling for iOS.

- src/winforms/toga_winforms/widgets/canvas.py
- src/winforms/toga_winforms/widgets/numberinput.py
- src/winforms/toga_winforms/widgets/optioncontainer.py
- src/winforms/toga_winforms/widgets/selection.py
- src/winforms/toga_winforms/widgets/splitcontainer.py
- src/winforms/toga_winforms/widgets/table.py
- src/winforms/toga_winforms/widgets/textinput.py
Signed-off-by: Olga <obulat@gmail.com>
This PR improves consistency in naming winforms event handler functions. All handlers are now named as `winforms_<native_event_name>`. For example the handler of `toga.TextInput`'s native `TextChanged` event is called `winforms_text_changed`.
> Rename winforms event handler functions for consistency

- src/winforms/toga_winforms/widgets/table.py
Signed-off-by: Olga <obulat@gmail.com>
Fixes #994.
Added a check for interface `on_select` callback before calling winforms `on_select`.
> Fix TypeError when no on_select callback is specified

- src/android/toga_android/widgets/button.py
Android's `Button` is a `TextView` subclass. This pull request gives its `rehint()` method the same treatment as toga `Label` (i.e., android `TextView`).
The recent font work (#1005) fiddled with layout under Toga's Android backend, which is why this is only needed now.
Happy to discuss more!
> Fix crash in Android button

- .github/labels.toml
- .gitignore
This PR adds a *labels.toml* file. This file can be used to sync the Github labels of the *Toga* project, making it easy to add, edit, and delete labels. look [here](https://raphael.codes/blog/announcing-python-3.6-cli-labels/) for for details.
It is worth noting that I kept the color-coding of existing labels as they were but used the new labels colors taken from the *Briefcase* project for unification purposes. In the future, it is worth changing all the colors to be the same in both projects.
Once this PR will be approved and merged, I will run the `labels sync` command in order to sync the labels with the repository.
After a little bit of thought, simply copied the *labels.toml* file from *Briefcase*. If any changes are needed, let me know.
> Add labels toml

- examples/webview/pyproject.toml
- src/android/toga_android/factory.py
- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/widgets/webview.py
Add Android WebView
Here's a screenshot of the app running the new WebView demo.
Notable missing features:
- No onload. It's too bad, but I can't make it work without rubicon-java subclassing.
- No on key down. Doesn't seem that important, but I'm OK adding it. I'd rather get this merged, and deal with that in a follow-up pull request, if possible.
If there are code style problems, I'd prefer to have you fix them if you're OK with it @freakboy3742 . I'm open to making revisions, just scared of latency.
> Add Android WebView

- src/winforms/toga_winforms/widgets/textinput.py
When using TextInput widget in windows, every click selects all text. This should be happening only when clicking twice. Changed that.
> TextInput select_all on double click instead of click

- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/widgets/internal/cells.py
- src/cocoa/toga_cocoa/widgets/table.py
This PR improves the layout of the `TogaIconCell` which is used to display content in Table and Tree widgets. Specifically:
* The layout of subviews is now handled with constraints instead of an autoresizing mask. As a result, the `NSTextField` subview will now be resized properly when the column width changes.
* Set the line break mode of the `NSTextField`  to truncating the tail. Together with the above change, this means that the text is now properly truncated when the user resizes a column.
* Remove the animations when adding or removing rows. @freakboy3742, I have come to agree with you that they become really annoying when rapidly adding many rows.
> Toga icon cell improvements

- src/android/toga_android/icons.py
An Android icon's `path` is already computed properly, which is the only
aspect that is meaningful on Android.
This pull request removes the meaningless "not implemented" printout when using an Android icon.
> Mark Android icon as implemented

- src/android/toga_android/widgets/detailedlist.py
WIth this diff:
```
diff --git a/examples/detailedlist/detailedlist/app.py b/examples/detailedlist/detailedlist/app.py
index 59ca272d..6dbfe1c3 100644
--- a/examples/detailedlist/detailedlist/app.py
+++ b/examples/detailedlist/detailedlist/app.py
@@ -10,6 +10,7 @@ from .translations import bee_translations
class ExampleDetailedListApp(toga.App):
def on_select_handler(self, widget, row, **kwargs):
+        print("FYI, you selected row " + str(row))
self.label.text = 'You selected row: {}'.format(row) if row is not None else 'No row selected'
async def on_refresh_handler(self, widget, **kwargs):
@@ -47,7 +48,7 @@ class ExampleDetailedListApp(toga.App):
outer_box = toga.Box(
-            children=[widget, self.label],
+            children=[self.label, widget],
style=Pack(
flex=1, …
```
> Implement DetailedList.on_select() on Android

- src/android/toga_android/libs/android_widgets.py
- src/android/toga_android/widgets/detailedlist.py
Rely on `androidx`'s `SwipeRefreshLayout` to get pull-to-refresh behavior on Android.
Like #1036, I recommend fiddling with the sample app to get a slightly different layout.
In addition, you'll have to incorporate https://github.com/beeware/briefcase-android-gradle-template/pull/23 into your template so this works.
If you do all that, you get this behavior:
> Implement on_refresh for Android DetailedList

- src/winforms/toga_winforms/widgets/table.py
When trying to run the table example in Windows, I get the following error:
```
File "c:\users\saroa\repos\toga\src\winforms\toga_winforms\app.py", line 144, in run_app
self.create()
File "c:\users\saroa\repos\toga\src\winforms\toga_winforms\app.py", line 65, in create
self.interface.startup()
File "C:\Users\saroa\repos\toga\examples\table\table\app.py", line 111, in startup
self.main_window.content = outer_box
File "c:\users\saroa\repos\toga\src\core\toga\window.py", line 132, in content
self._impl.set_content(widget._impl)
File "c:\users\saroa\repos\toga\src\winforms\toga_winforms\window.py", line 101, in set_content
child._impl.container = widget
File "c:\users\saroa\repos\toga\src\winforms\toga_winforms\widgets\base.py", line 40, in container
child._impl.container = container
File …
```
> Fix table example in Windows

- src/cocoa/toga_cocoa/widgets/internal/cells.py
- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
This PR provides performance improvements to `toga_cocoa.Table` and `toga_cocoa.Tree` and small layout tweaks:
* Avoid calling `tableView_viewForTableColumn_row_` from `tableView_heightOfRow_` because it leads to unnecessary initialisations of table cell views. Instead use the default row height if the cell contains only text and an icon. The same holds for `outlineView_viewForTableColumn_item_`.
* Constrain the icon width to 16 pixels in `TogaIconView`. This prevents the icon from shrinking when the column width is smaller than 16 pixels.
* Set the minimum column width to 16 pixels so that a possible icon is always visible. 
The first change leads to significant performance improvements for large tables because Cocoa will only initialise the views which are currently visible to the user.
> Performance improvements to `toga_cocoa.Table` and `toga_cocoa.Tree`

- examples/tree_source/tree_source/app.py
- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
- src/core/tests/widgets/test_table.py
- src/core/toga/widgets/table.py
- src/core/toga/widgets/tree.py
- src/dummy/toga_dummy/widgets/table.py
- src/dummy/toga_dummy/widgets/tree.py
- src/gtk/toga_gtk/widgets/table.py
- src/gtk/toga_gtk/widgets/tree.py
- src/winforms/toga_winforms/widgets/table.py
- src/winforms/toga_winforms/widgets/tree.py
Added a handler `on_double_click` to Tree and Table widgets to handle when a user double-clicks a row or node. This has multiple use cases, for instance to "open" a clicked item if it represents a file or folder, or to open a window with detailed information on the represented item. This PR only includes an implementation for the Cocoa backend.
In addition, the `tree_source` example, which demonstrates how to implement a file browser with a Tree widget, now responds to double-clicking a node with opening the file or folder in the platform's default app.
> Table row double click action

- examples/table/table/app.py
- examples/table_source/table_source/app.py
- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
- src/core/toga/widgets/table.py
- src/core/toga/widgets/tree.py
- src/dummy/toga_dummy/widgets/table.py
- src/dummy/toga_dummy/widgets/tree.py
- src/gtk/toga_gtk/widgets/table.py
- src/gtk/toga_gtk/widgets/tree.py
- src/winforms/toga_winforms/widgets/table.py
- src/winforms/toga_winforms/widgets/tree.py
Historically, we've used a shadow attribute to track selection on trees and tables. This replaces that mechanism with a native API call to extract the selection.
Also implements multi-select for trees and tables on GTK.
> Determine tree/table selection directly by API, rather than using a shadow

- src/gtk/toga_gtk/widgets/base.py
This PR implements the API to insert and remove widgets in the Gtk backend, similar to existing implementations for Cocoa and Winforms.
The example to test this is `layout`. However, there remains a small issue with this example in particular and the implementation of `toga_gtk.ImageView`: the example involves adding and reparenting an ImageView. However, the `toga_gtk.ImageView.rehint` produces incorrect dimensions in the first run after ImageView added to the new container (`native.get_allocated_width()` and `native.get_allocated_height()` both return 1). We only get correct values and an appearing image in the second run, for instance when resizing the window.
To me, this looks like an issue with `toga_gtk.ImageView` itself and should be fixed there instead of in this PR.
> Implement insert and remove api for toga_gtk.Widget

- examples/box/box/app.py
- src/winforms/toga_winforms/colors.py
- src/winforms/toga_winforms/widgets/box.py
- src/winforms/toga_winforms/widgets/button.py
- src/winforms/toga_winforms/widgets/label.py
This fixes a bug when trying to set the background color of a widget in Windows with  `TRANSPARENT` it raises an error.
> Add transparent color to windows color map

- .coveragerc
- .github/workflows/ci.yml
- .gitignore
- MANIFEST.in
- src/core/tests/test_app.py
- tox.ini
Add coverage tests to Toga core abilities. we are now on 91% coverage!
This PR is missing us to add **CODECOV_TOKEN** to the repository's secrets.
> Add code coverage to Toga

- src/cocoa/toga_cocoa/widgets/tree.py
Fixes an unresolved reference `current_index` in `toga_cocoa.widgets.tee.Tree.get_selection()`.
> Fixes an unresolved reference in Cocoa Tree

- src/gtk/toga_gtk/widgets/splitcontainer.py
This PR will add frame to the splits of the splitcontainer to be visually distinguish from other contents.
* Before add frame:
* After add frame:
> Adding frame to the split container to be visually distinguish.

- examples/scrollcontainer/scrollcontainer/app.py
- src/cocoa/toga_cocoa/widgets/scrollcontainer.py
This confines the content of a ScrollContainer to its width or height along any non-scrolling direction. This means that for a ScrollContainer without a horizontal scroll bar (`horizontal = False`), the content will be confined to the width of the ScrollContainer. For a ScrollContainer without a vertical scroll bar (`vertical = False`), the content will be confined to the height of the ScrollContainer.
This change prevents content from unexpectedly becoming invisible when it's outside of the visible area along a non-scrolling direction.
I am not sure if this is the intended effect of disabling a scrollbar but it makes sense to me. A common use case would be a vertical stack of widgets to scroll through, similar to DetailedList, where the width of the widgets is fixed by the available …
> Cocoa ScrollContainer: confine content in non-scrolling direction

- src/core/tests/widgets/test_switch.py
- src/core/toga/widgets/switch.py
Added a toggle method to `toga.Slider` to invert `Slider.is_on` property.
> Add toggle method to toga.Switch

- examples/divider/divider/app.py
- src/winforms/toga_winforms/factory.py
- src/winforms/toga_winforms/widgets/divider.py
This is an initial implementation of the `toga.Divider` widget in Windows, based on [this](https://stackoverflow.com/questions/3296110/draw-horizontal-divider-in-winforms) suggestion.
> Add Divider implementation in Windows

- examples/canvas/canvas/app.py
- src/core/toga/keys.py
- src/winforms/toga_winforms/keys.py
- src/winforms/toga_winforms/widgets/slider.py
Added missing keys to Winform's keymap and added those keys to the `Canvas` example.
When doing so, found a bug in Winform's `Slider`, so fixed it.
> Support more shortcuts in windows

- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/libs/core_graphics.py
- src/cocoa/toga_cocoa/libs/foundation.py
- src/cocoa/toga_cocoa/libs/webkit.py
From macOS 11 onward, system libraries are no longer present on the filesystem. From Apple's release notes:
> New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache.
As a result, using `cdll.LoadLibrary(util.find_library('lib'))` fails to load the libraries on macOS 11. This will likely be fixed when PR https://github.com/python/cpython/pull/21241 is merged. I believe the fix will be …
> Use rubicon-objc `load_library` to load system libraries

- README.rst
- docs/reference/api/widgets/webview.rst
- docs/reference/platforms.rst
- src/cocoa/README.rst
- src/cocoa/toga_cocoa/widgets/webview.py
- src/core/README.rst
This PR migrates the WebView implementation in Cocoa from WebView (deprecated in macOS 10.10) to WKWebView.
> Migrate WebView -> WKWebView

- examples/textinput/textinput/app.py
- src/android/toga_android/widgets/textinput.py
- src/cocoa/toga_cocoa/widgets/passwordinput.py
- src/cocoa/toga_cocoa/widgets/textinput.py
- src/core/tests/widgets/test_textinput.py
- src/core/toga/widgets/textinput.py
- src/dummy/toga_dummy/utils.py
- src/dummy/toga_dummy/widgets/textinput.py
- src/gtk/toga_gtk/widgets/textinput.py
- src/iOS/toga_iOS/widgets/textinput.py
- src/winforms/toga_winforms/widgets/textinput.py
Initial implementation of a validator in `toga.TextInput` in Windows. One can add a `validator` parameter to the `toga.TextInput` constructor in order to validate the value. the `validator` callable should return `None` if the value is valid and an error message if it is not.
closes #909
> Add TextInput validator

- src/winforms/toga_winforms/app.py
on_exit handler was not being called
> call on_exit handler

- examples/dialogs/dialogs/app.py
- src/winforms/tests/test_window.py
- src/winforms/toga_winforms/window.py
Under Winforms, when a file filter is used on a File dialog, only files of that type are shown. If the list of acceptable file types is long, that makes file navigation unwieldy, as you can only see files of one type at a time; and it makes selecting two files of a different type impossible under multiple selection. 
This adds an "all matching files" option as the default, which matches all valid file types.
> Fixes #1112 -- Provide an 'all matching' option for winforms file dialogs

- examples/examples_overview/README.rst
- examples/examples_overview/examples_overview/__init__.py
- examples/examples_overview/examples_overview/__main__.py
- examples/examples_overview/examples_overview/app.py
- examples/examples_overview/examples_overview/resources/README
- examples/examples_overview/pyproject.toml
This PR introduces a new example `examples_overview` which shows a table of all examples and the REAMDE of the selected example. There are buttons to run an example and to open its folder. On supported platforms, double-clicking a table row will also run the example.
Screenshot:
The aim is to simplify testing multiple examples in a user-friendly way which does not require excessive command line usage. It also makes it easier for newcomers to get an overview.
> An example overview making it easy run multiple examples

- src/cocoa/toga_cocoa/widgets/internal/cells.py
As reported in #1115, the call to `NSImage.resizeTo` in `TogaIconView` is sketchy: rubicon-objc recognises the method but it is not documented anywhere. This PR removes this call and uses the image as-is. Any resizing is already handled properly by the `NSImageView` because of the enforced constraints.
> Don't use `NSImage.resizeTo`

- examples/slider/slider/app.py
- src/winforms/toga_winforms/widgets/slider.py
On windows, pressing and releasing sliders does not cause the `on_change ` method to perform the same way the Cocoa implementation does.
Fixed that and fixed the example accordingly.
> Fix Slider on_press and on_release in Windows.

- src/gtk/toga_gtk/widgets/multilinetextinput.py
The current Gtk implementation of`MultilineTextInput` is not very useful, partly because of #1131, but also because it doesn't have text wrapping or scroll bars.
This change:
* enables text wrapping—without this, long lines just disappear off the edge of the box, and because there are no scroll bars by default, you'd need to use arrow keys or click and drag to get to the bits out of view to the side
* adds a vertical scroll bar if it's required
I would argue that having text wrapping and vertical scroll bar if required represents the most useful way for `MultilineTextInput` to behave on a desktop.
> Add text wrapping and vertical scroll bar to multilinetextinput in Gtk backend.

- src/gtk/toga_gtk/widgets/multilinetextinput.py
This is a one-line fix for the fact that with toga_gtk, `multilinetextinput.value = 'anything'` would not do anything.
The existing implementation was accessing `self.interface.value`, which in turn called `self.get_value()`, so it would set it back to the current value regardless of the string passed in.
> toga_gtk: fixed bug where attempting to set multilinetextinput.value would do nothing.

- examples/multilinetextinput/multilinetextinput/app.py
- src/core/toga/widgets/multilinetextinput.py
#1131 and #1132 added some fixes to mutlilinetextinput; these changes provide a way to exercise those features in the corresponding example.
> Add content generation button to multilinetextinput demo.

- examples/textinput/textinput/app.py
- src/core/tests/test_validators.py
- src/core/tests/widgets/test_textinput.py
- src/core/toga/validators.py
- src/core/toga/widgets/textinput.py
This alters the API for TextInput validators so that `validators` is a list, rather than a single object. This means there is no need for a `Combine` operator, as combination of validators is the default behaviour.
> Make input validators a list.

- src/winforms/toga_winforms/widgets/splitcontainer.py
When trying to set a split container with a given ratio between tabs, it doesn't work as expected.
FIxed that.
> Fix bug in windows split container

- src/core/tests/test_validators.py
- src/core/toga/validators.py
At the moment the numbers validator does not excpet numbers such as "1e+12" or "-9.2e-17".
Fixed that.
> Number regular expression should include exponents

- src/winforms/toga_winforms/widgets/selection.py
There is a bug in the `select_item` method in Winforms.
It seems like the method "native.FindItem"  returns the wrong index.
In order to fix the problem altogether, setting `SelectedItem` instead of `SelectedIndex`.
> Fix bug in windows selection

- src/cocoa/toga_cocoa/dialogs.py
`open_file_dialog` in cocoa is not casting the NSString into a python string for single files. I cast it to a python string if just one file is selected.
> cast str on cocoa open_file dialog single file selection

- src/core/toga/widgets/base.py
- src/winforms/toga_winforms/widgets/base.py
When trying to refresh an App in windows, sometimes an `AttributeError` is raised that _impl doesn't have a `viewport` attribute.
Fixed that by default, viewport is `None`.
> Add None viewport by default to Windows widget.

- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/detailedlist.py
On Android, use a global JNI ref for `_native_activity`.
This allows the Android DetailedList demo's "Insert Row" button to be clicked without triggering a crash.
> Fix crash on adding new row to DetailedList

- src/cocoa/toga_cocoa/widgets/webview.py
- Fixes #1197
- What problem does this change solve? Currently one cannot enter text into inputs within a WebView on Mac OS (Cocoa).
- Propagate event to superclass handler in Cocoa `TogaWebView.keyDown_`.
> Fix Cocoa keyDown event propagation

- src/cocoa/toga_cocoa/widgets/internal/cells.py
This PR fixes an issue with `TogaIconView` where the instances of `NSImageView` and `NSTextField` can be deallocated 
before they are added as subviews to the `TogaIconView`. This becomes a problem when we start doing proper reference management, i.e., giving up the ownership of objc instances once the corresponding Python variable is destroyed.
See https://github.com/beeware/rubicon-objc/pull/201#issuecomment-758664864 for a proper analyses of the issue.
> Fix memory management issue in Cocoa TogaIconView

- src/winforms/toga_winforms/widgets/imageview.py
Currently, when we set an image to Winforms ` imageview`, it doesn't check if it already has the image. This way, when changing the image, resources are not being freed (disposed of), and we cannot delete the image that was previously used because of the Permission Error.
This PR adds a check for the existing image. If it exists, we free the resources by calling `Dispose`, and only then set the new image.
> Make changing Winforms imageview image possible

- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/winforms.py
- src/winforms/toga_winforms/widgets/multilinetextinput.py
Implemented placeholder text in `toga.MultilineTextInput` in Windows implementation.
Unfortunately, there wasn't a straight-forward approach to implement this new feature, so I had to improvise a little bit.
> Add multiline text input placeholder implementation on windows

- src/winforms/toga_winforms/libs/fonts.py
- src/winforms/toga_winforms/libs/winforms.py
Refs #1210
This PR fixes a bug where the Windows backend could not set a custom font.
The `win_font_family` function was looking up the string value of the font name in a list of FontFamily objects, and, therefore, could not find it. Since Winforms doesn't provide an easy way to get a list of installed font family names as strings, this PR simply tries to get the FontFamily from the value string and uses the fallback in case of pythonnet's ArgumentException.
I tested it the tutorial1 because there is no specific example app for fonts, and managed to set the label font to 'Comic Sans MS'.
> Fix Winforms font family lookup

- src/android/toga_android/widgets/detailedlist.py
On Android, the DetailedList rows had a different background color than the rest of the widget. This fixes that. Note that it's subtle -- look carefully at the color behind "Bee" vs. the color behind "INSERT ROW".
The DetailedList still needs swipe-based actions to be implemented. I plan to work on that next. I saw this issue and wanted to fix it first.
> Fix DetailedList row background color

- src/android/toga_android/widgets/detailedlist.py
This changes the Android `DetailedList` so that it passes row data, not the row _index_. This makes it work the same as iOS & macOS (the only two that I tested). See relevant code here:
* https://github.com/beeware/toga/blob/master/src/cocoa/toga_cocoa/widgets/detailedlist.py#L89
* https://github.com/beeware/toga/blob/master/src/iOS/toga_iOS/widgets/detailedlist.py#L78
I noticed this issue in the `adb logcat` output of the DetailedList example app. When I touched a row in the app, I would get a stacktrace.
To test this, I added a `print(self.label.text)` to the `ExampleDetailedListApp` in `examples/detailedlist/detailedlist/app.py`. This proved to me that the new `self.label.text` is what it should be.
> Android DetailedList: Implement on_select

- README.rst
- setup.cfg
Since we have removed the support for 3.5, we can remove it from the badge as well. I've added python versions up to 3.8, but didn't add 3.9 because it's not yet supported on Windows. The last time I tried about a month ago, I have managed to install dependencies, but got an error that Briefcase doesn't have a template for Windows with Python 3.9.
> Update python version badge

- src/winforms/toga_winforms/libs/proactor.py
#1109 made some changes to memory handling in the Winforms proactor loop to stop a slow leak.
On further investigation, it appears that this is stopping the leak by stopping the proactor :-) This meant that all asyncio handlers and background workers stopped working.
It appears that the actual problem is deeper inside Python.net (or our usage of Python.net). Even with the patch from #1109, you can see a small leak every time you click on a button. The proactor is effectively implementing "click a button every 5ms", which is why the leak is more obvious when the proactor is running.
> Fixes #1166 - Roll back memory cleanup changes from #1109.

- src/android/toga_android/widgets/detailedlist.py
- src/core/toga/widgets/detailedlist.py
Fix the `.selection` property on the Android `DetailedList`.
In the GIF screenshots, you can see that this also fixes the "Delete Row" button in the DetailedList demo app.
It also fixes a typo in a comment in the `core` DetailedList.
> Fix Android DetailedList .selection property

- src/android/toga_android/window.py
On Android, compute the Toga viewport size such that the full app can display.
To do that, we subtract the app action bar (app name header) plus status bar (platform clock widget).
With this change, here's the DetailedList demo:
Note that the bottom status text now actually displays!
This is very similar to the iOS layout.
> Compute Android Toga window height properly

- docs/requirements.txt
Sphinx 4 causes problems with some plugins; pin the Sphinx version to prevent problems.
> Pin Sphinx requirement to prevent use of Sphinx 4.

- README.rst
- docs/index.rst
- docs/reference/platforms.rst
- nursery/curses/README.rst
- nursery/falcon/README.rst
- nursery/pyramid/README.rst
- nursery/qt/README.rst
- nursery/starlette/README.rst
- nursery/tornado/README.rst
- nursery/tvOS/README.rst
- nursery/uwp/README.rst
- nursery/watchOS/README.rst
- src/android/README.rst
- src/cocoa/README.rst
- src/core/README.rst
- src/django/README.rst
- src/dummy/README.rst
- src/flask/README.rst
- src/gtk/README.rst
- src/iOS/README.rst
- src/web/README.rst
- src/winforms/README.rst
Turns out direct Discord links aren't a good idea; replace them with a simpler link to the invite.
> Simplify Discord links.

- src/cocoa/toga_cocoa/widgets/textinput.py
Cocoa's textInputs cleared themselves on loss of focus; this was due to not completing the internal `textDidEndEditing:` action.
> Ensure textinput content persists on loss of focus.

- src/cocoa/toga_cocoa/app.py
Added "Hide <app>", "Hide Others" and "Show All" in a separate
section immediately preceding "Quit".  Also added Cmd+, as
a shortcut for "Preferences" and sectioned it off.
Closes #1261.
Signed-off-by: layday <layday@protonmail.com>
> cocoa: add standard app menu items

- examples/textinput/README.rst
- examples/textinput/pyproject.toml
fix copy errors for .\examples\textinput
In .\examples\textinput, the pyproject.toml is copied from the handlers example.
This enables "briefcase dev" to work on the textinput example.
- [ x ] All new features have been tested (both "briefcase dev" and "py -m textinput")
> fix textinput example copy over errors

- src/android/toga_android/widgets/scrollcontainer.py
This PR fixes the problem that ScrollContainer on Android did not calculate the height correctly with flex=1
> Android ScrollContainer fix for flex=1

- src/cocoa/toga_cocoa/widgets/table.py
- src/cocoa/toga_cocoa/widgets/tree.py
Following the recent improvements to memory management in `rubicon-objc`, a few issues in toga-cocoa have become apparent which previously where hidden because Objective-C instances would live for ever.
This PR fixes an issue where the `TogaIconView` in a Tree or Table widget is deallocated before it can be used because no Python references are left after `tableView_viewForTableColumn_row_` or `outlineView_viewForTableColumn_item_` returns.
> [cocoa] Fix segfault when TogaIconView is deallocated

- src/cocoa/toga_cocoa/libs/appkit.py
macOS on M1 adopts the iOS values for some constants. See
https://developer.apple.com/documentation/apple-silicon/addressing-architectural-differences-in-your-macos-code
for details. 
This PR uses platform.architecture() to differentiate arm from x86 macOS builds.
> Fixes #1282 - Use different enum constants on M1 Macs

- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/command.py
- src/cocoa/toga_cocoa/window.py
- src/core/toga/command.py
- src/core/toga/handlers.py
This passes `unhideAllApplications:` as a selector to `NSMenuItem`
and turns `autoenablesItems` back on, for `validateMenuItem:`
to be invoked for built-in selectors.
With `autoenablesItems` being true
flipping the value of `NSMenuItem.enabled` does not trigger an update
and we must implement `validateMenuItem:` on the delegate
to disable custom commands.
Signed-off-by: layday <layday@protonmail.com>
> cocoa: disable 'Show All' menu item when all windows are shown

- src/winforms/toga_winforms/widgets/base.py
Refs #1284 
When adding a child widget to another widget in Winforms, we only checked if the parent had a `container` property, and set the child's `container` property to that. A top-level container does not have a `container` property, so it was impossible to add a child to any top-level container.
This PR uses the Cocoa implementation: it checks for the parent widget's `viewport`. If the parent has `viewport` property, it is the top-level widget, so we set the child's container to the widget itself.
This was actually a change that was added to make widget addition/removal possible, but the Winforms backend was not updated at the time.
> Add child to top level container in Winforms

- src/cocoa/toga_cocoa/app.py
Thanks to the preceding work by @layday, this PR adds default commands for the macOS edit menu. This includes copy, paste, cut, select all and a couple more.
Closes #796.
> Add default commands in macOS Edit menu

- examples/tutorial2/tutorial/app.py
- src/cocoa/toga_cocoa/widgets/splitcontainer.py
Reported by @hoffenmerCode in #1292
The weight attributes of a SplitContainer were not being applied correctly in Cocoa. This corrects the layout.
> Correct the application of split view weights on cocoa.

- src/android/toga_android/widgets/slider.py
Convert range properly to Android SeekBar values
Fixes #1277
See [sample app](https://github.com/paulproteus/toga-issue-1277)
> Fix Android slider math

- src/android/toga_android/factory.py
- src/android/toga_android/libs/activity.py
- src/android/toga_android/libs/android/graphics.py
- src/android/toga_android/widgets/canvas.py
Add drawing solid lines on Android canvas.
This makes progress toward implementing the Canvas widget on Android generally.
I made a sample app here: https://github.com/paulproteus/toganvas/blob/main/toganvas/src/toganvas/app.py / https://github.com/paulproteus/toganvas
On iOS and on Android, it looks as follows.
There's lots more work to do, but I thought it would be nice for my motivation to submit some progress via this pull request.
> Add solid lines on Android canvas

- src/android/toga_android/widgets/canvas.py
- src/android/toga_android/window.py
Use Android viewport DPI (vs. baseline DPI) to compute Canvas scale factor.
I resized an Android virtual device to approx the same size as iOS, and I used the https://github.com/paulproteus/toganvas codebase to draw a colored "X". Here's what it looks like.
Pretty similar.
This is the same way we adjust pixel size for during layout:
https://github.com/beeware/toga/blob/19e89a77f1bacddc09110fd5c240ea4ecbf85b2a/src/core/toga/style/pack.py#L116-L118
I wanted to use a keyword argument for `scale_factor` and compute it only once, hence the computation within `DrawHandler#handle_draw`.
> Scale Android canvas properly

- src/android/toga_android/libs/android/graphics.py
- src/android/toga_android/widgets/canvas.py
- src/android/toga_android/window.py
Add dashed line support to Android Canvas
(depends on #1317 )
Android:
iOS:
I can't think of a way to make sense of `[4, 4]` resulting in what I see on iOS. Is the Toga iOS port buggy? Who's right? :D
> Android dashed line canvas

- src/cocoa/toga_cocoa/widgets/textinput.py
- src/winforms/toga_winforms/widgets/textinput.py
Adds support for `color` style directives on TextInput widgets
> Add support for foreground colors in TextInput

- examples/table/table/app.py
- src/cocoa/toga_cocoa/widgets/table.py
Significantly speeds up the instantiation time on Cocoa tables.
When the TableViewDelegate provides tableView:heightOfRow:, it is invoked for *every* row in the table. If you have a large table (50k rows), that takes a lot of time, even if you return a constant.
However, you only need to implement this method if the table rows have custom or different heights per-row. Since we don't currently support that feature, we're paying a cost for no benefit.
> Speed up creation of Cocoa TableViews

- src/cocoa/toga_cocoa/widgets/detailedlist.py
- src/cocoa/toga_cocoa/widgets/internal/data.py
DetailedList examples (beeliza, detailedlist) were both crashing as of dc565f9c5d. I couldn't narrow down a specific change where this problem was introduced; it appears that it may have *always* been there, but something subtle in a recent macOS change has surfaced the problem.
> Ensure data objects used by DetailedList are correctly retained

- src/cocoa/toga_cocoa/fonts.py
- src/cocoa/toga_cocoa/libs/appkit.py
The Cocoa implementation of font traits (bold, italic, etc) wasn't correct; it assumed a consistent naming scheme in font names, which didn't exist.
This changes font loading to use the sharedFontManager to convert the base font into a font with the requested traits.
> Fix handling of font traits on Cocoa.

- src/cocoa/toga_cocoa/window.py
- src/core/toga/window.py
This PR fixes #1329 which prevents windows with a disabled a close button on macOS from being closed programatically.
It also updates the doc string for `toga.Window.on_close`.
> Fix closing window without the close button

- src/cocoa/toga_cocoa/widgets/canvas.py
Via a report from @wesley5040 about toga-chart.
If a Canvas is a top level widget, the initial `on_resize` call it made would report a size of (0,0). This is because resize was handled as a widget-level change, and when the widget is at the top level, it is managed using an autoresize mask, which means it gets `frameChanged:` events *before* the layout algorithm is invoked.
Changing on_resize event handling to be triggered by the application of results from the layout algorithm means the Toga event can provide the final layout size.
> Canvas resize

- README.rst
- docs/tutorial/tutorial-0.rst
The readme distinguishes between Ubuntu versions. Further the list of
debian packages in the readme differs from the one in the tutorial.
Because the readme is more recent (see 82c94a72) it's presumably more up
to date.
Hopefully this change doesn't drop a debian package which is used only
by the tutorial but not by the readme.
> Align tutorial installation instructions with readme

- src/android/toga_android/widgets/canvas.py
Implement support for `.closed_path` at the Android impl layer.
This allows one to draw e.g. two line segments, then by "closing" the path, let the platform connect the dots to make sure you have built a 2D shape that would "hold water" if you poured water into it. I'm not sure I know a better way to describe it.
Mac app:
Android app:
Android app _before this change_:
Tested with this code: 
https://github.com/paulproteus/toganvas/blob/6b52d1c4481294114cc217f71f8c740275cb4a7b/toganvas/src/toganvas/app.py#L63-L87
> Support closing a path in Android

- src/cocoa/toga_cocoa/libs/appkit.py
Handle NSAboutPanelOption symbols for older version of macOS i.e., lower than 10.13
- Add check for platform version
- Set keys to None if version lower than minimum
supported version
Build the app for macOS versions lower than 10.13 due to unsupported symbols
Fixes #1345
> Add check for NSAboutPanelOption symbols

- src/android/toga_android/widgets/canvas.py
The Android output is slightly smaller than the macOS one -- I _think_ this is just the status quo with my emulator. I'm focusing on the aspect ratio here, which does seem correctly scaled.
With this code: https://github.com/paulproteus/toganvas/blob/ff09b3cbe61143ba223c391af5fed069addd21c0/toganvas/src/toganvas/app.py#L156
macOS:
Android:
> Implement scale on Android canvas

- .github/workflows/ci.yml
- setup.cfg
- src/cocoa/toga_cocoa/app.py
- src/gtk/toga_gtk/app.py
- tox.ini
This PR replaces the usage of `asyncio.get_event_loop()` in toga-cocoa and toga-gtk where it was used to retrieve the default but not running event loop. From the Python docs [here](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop):
> Deprecated since version 3.10: Deprecation warning is emitted if there is no running event loop. In future Python releases, this function will be an alias of get_running_loop().
> Replaces deprecated usage of `asyncio.get_event_loop()`

- src/iOS/toga_iOS/dialogs.py
- src/iOS/toga_iOS/libs/foundation.py
iOS 15 explicitly makes `NSRunLoop.currentRunLoop` a property, which breaks the usage accessing the property as a function. Explicitly declaring as a property allows both old and new iOS versions to use property-based access.
> Mark currentRunLoop as a property.

- .github/workflows/ci.yml
- README.rst
- docs/reference/api/widgets/webview.rst
- docs/tutorial/tutorial-0.rst
- src/winforms/setup.py
The Python.net team hasn't published 2.X wheels for Python 3.9 or 3.10, and their development effort seems to be focussed on the 3.X branch. They've indicated they're not planning to make the 2.X branch compatible with Python 3.10. 
The vast majority of first-time users are coming to Toga with Python 3.10 or 3.9. If we want to be able to support these users, we need to work off a source release until Python.net formally releases 3.0.
The 8d93c39d hash is, as best as I can work out, what was in the 3.0.0-preview2021-10-05 release published to nuget - but they didn't tag anything for that release, so we have to guess based on commit dates.
> Move to a pre-release version of Python.net.

- src/cocoa/toga_cocoa/widgets/splitcontainer.py
Split containers with more than 2 panels didn't apply the position correctly.
> Correct weight handling for Cocoa split containers.

- src/cocoa/toga_cocoa/fonts.py
- src/cocoa/toga_cocoa/libs/appkit.py
- src/cocoa/toga_cocoa/widgets/button.py
- src/cocoa/toga_cocoa/widgets/canvas.py
- src/cocoa/toga_cocoa/widgets/switch.py
The default Cocoa button has, by definition, a fixed height. This is because the macOS HIG doesn't recommend changing the font size on text buttons, and doesn't recommend having buttons of arbitrary size.
There is occasionally a need to violate this; and requests for setting the height of a button are common, so we might as well support the request.
> Cocoa button size

- src/cocoa/toga_cocoa/widgets/optioncontainer.py
On Cocoa, if an OptionContainer is part of a layout, and the window is resized, the layout of non-visible content won't reflect the new overall window size. So - when a tab is selected, force a refresh of the content layout.
> Force a refresh when the tab changes.

- README.rst
- src/winforms/setup.py
Updated Pythonnet version to an [alpha version](https://pypi.org/project/pythonnet/3.0.0a1/)
Closes #1370
> Use alpha version of pythonnet

- src/gtk/toga_gtk/paths.py
The app.name is a displayable name, it is preferable to use the app_name
which is a technical name (the python module name).
> [Gtk] replace app.name to app.app_name in paths

- src/android/toga_android/paths.py
This file was a copy/paste from the iOS one, so it didn't make sense.
Now use `getApplicationContext().getFilesDir()` for data directory, and
`getApplicationContext().getCacheDir()` for cache and logs directories.
> [Android] fix paths to use right ones

- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/button.py
- src/android/toga_android/widgets/detailedlist.py
- src/android/toga_android/widgets/label.py
- src/android/toga_android/widgets/scrollcontainer.py
- src/android/toga_android/widgets/switch.py
- src/android/toga_android/widgets/table.py
- src/android/toga_android/widgets/textinput.py
- src/android/toga_android/widgets/webview.py
beeware/rubicon-java#67 modified the handling of NULL return values, returning a typed `JavaNull` rather than a Python `None`.
> Remove explicit comparisons with None.

- src/android/toga_android/widgets/textinput.py
Without input type set, the textinput will be a multi-line text input widget in my test.
This patch set the input type and then the text input becomes single-line.
The above code is used in text, in which height was set to a large value so that multiple lines can be seen in a screenshot picture:
```python
import toga
main_box = toga.Box()
main_box.add(toga.TextInput(style=Pack(flex=1, height=512)))
self.main_window = toga.MainWindow(title=self.formal_name)
self.main_window.content = main_box
self.main_window.show()
def main():
return HelloWorld()
```
Before setting the input type:
After setting the input type:
> [Android] make TextInput single-line

- src/android/setup.py
- src/android/toga_android/app.py
- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/detailedlist.py
- src/android/toga_android/widgets/scrollcontainer.py
- src/android/toga_android/widgets/webview.py
Updates Toga to use Rubicon 0.2.6, and the new APIs that come with that (in particular, `__global__()`; but also some other miscellaneous fixes that were required).
> Use new Rubicon APIs

- src/winforms/toga_winforms/widgets/numberinput.py
Reported (indirectly) through freakboy3742/traveltips#9.
When a min/max value is defined on a NumberInput on Winforms, the min/max value wasn't able to be converted.
> Correct conversion of min/max values on Winforms Numberinput.

- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/widgets/textinput.py
Added `argtypes=[c_void_p]` to the `send_super` call in `TogaTextField.textDidEndEditing_()`
This adds a noop mehtod for the `select_file` callback in toga_cocoa.app.App
TextInput crashes on Apple M1 silicon when losing focus
This exception is raised when creating a Toga app on macOS
```
Exception ignored on calling ctypes callback function: <rubicon.objc.api.objc_method object at 0x10796f7f0>
File "/Users/fuzz/dev/dev-venv/lib/python3.10/site-packages/rubicon/objc/api.py", line 275, in __call__
result = self.py_method(py_self, *args)
File "/Users/fuzz/dev/dev-venv/lib/python3.10/site-packages/toga_cocoa/app.py", line 56, in applicationOpenUntitledFile_
self.impl.select_file()
AttributeError: 'App' object has no attribute 'select_file'
```
- [ X] All new …
> Fix TextInput crash on Apple M1. Add noop select_file to cocoa.app.App to prevent an exception being raised

- src/cocoa/toga_cocoa/widgets/internal/refresh.py
Add argtypes to send_super in RefreshableScrollView
Crash on Apple M1 silicon when using the scroll wheel
- [ X] All new features have been tested
- [ X] All new features have been documented
- [ X] I have read the **CONTRIBUTING.md** file
- [ X] I will abide by the code of conduct
> Add argtypes to send_super in RefreshableScrollView

- src/winforms/toga_winforms/widgets/canvas.py
Description
-------------
At the moment, the `Canvas` example is failing for *winforms*.
This PR fixes this problem
Why?
------
About two months ago we started using an alpha version of *Pythonnet 3.0*. This version now treats enums as objects instead of integers. the only way to get the integer value of the enum is using the `value__` attribute.
In the meanwhile, I opened an [issue](pythonnet/pythonnet#1585) for fixing this problem, and suggested adding the `__int__` method for getting `value__`. While *Pythonnet* did implement this ability in pythonnet/pythonnet#1661, it is not available in the alpha version.
In order for *Toga* to keep working until the next version of *Pythonnet* is released, I added this PR. once they publish their production version, I'll create a new PR and use the …
> Fix canvas example on Windows

- src/core/toga/app.py
This PR adds a doc string to `toga.App.add_background_task()`. Questions regarding its the usage or requests for functionality which is provided by `add_background_task()` have come up sufficiently often on Discord or GH Issues that this API should be documented.
This is a first step to address #1371.
> Add docstring to `App.add_background_task()`

- examples/numberinput/README.rst
- examples/numberinput/numberinput/__init__.py
- examples/numberinput/numberinput/__main__.py
- examples/numberinput/numberinput/app.py
- examples/numberinput/numberinput/resources/README
- examples/numberinput/pyproject.toml
- src/android/toga_android/widgets/numberinput.py
- src/android/toga_android/widgets/selection.py
This PR fixes the problem that NumberInput causes an app crash on startup.
It also fixes an exception in Selection when getting the value and nothing is selected.
> Fix for NumberInput and Selection (Android)

- src/android/toga_android/widgets/base.py
- src/android/toga_android/widgets/canvas.py
- src/android/toga_android/widgets/scrollcontainer.py
- src/android/toga_android/window.py
This PR fixes several UI problems on Android:
1. adding Widgets to a Box after startup has no effect
2. adding Widgets to the ScrollContainer's content box did not update the ScrollContainer
3. setting a new content on the ScrollContainer when there already was a content caused an app crash
The PR has been tested with following demo apps:
https://bitbucket.org/TomArn/demoapp.git      branch: switch_content
https://github.com/paulproteus/toganvas.git   commit [854b6ad]
> Android switch content

- src/cocoa/toga_cocoa/widgets/tree.py
- src/cocoa/toga_cocoa/widgets/webview.py
This PR fixes remaining usages of `send_super` in toga-cocoa. See https://github.com/beeware/rubicon-objc/issues/219 for the rationale.
> More `send_super` fixes

- src/android/toga_android/widgets/textinput.py
This PR fixes the problem on Android that there is following error message when creating a TextInput:
'TextInput' object has no attribute _on_change
It seems that the lately added setInputType triggers a change event, but at this time, the on_change handler is not yet in place.
> Fix for following creation error on Android: 'TextInput' object has no attribute _on_change

- src/gtk/toga_gtk/window.py
Currently, it doesn't work to set a content on a window if there is
already one, Gtk displays this error:
> Attempting to add a widget with type GtkBox to a GtkApplicationWindow,
but as a GtkBin subclass a GtkApplicationWindow can only contain one
widget at a time; it already contains a widget of type GtkBox
This is because there is an existing Box layout inside the window.
To fix it, we remove the existing layout if it already exists.
Note that to work, it is required to call again 'window.show()' after
replacing the content.
> [Gtk] fix replacing a window content by another one

- src/core/toga/widgets/detailedlist.py
I'm getting error `got an unexpected keyword argument 'row'` when trying to create `on_select` handler for `DetailedList` using provided example from documentation (I'm on MacOS)
This commit changes `Examples:` section of `DetailedList` class documentation to use the proper argument name
Currently documentation for DetailsList contains example, which raises exception
> Fixing error using this example on_select handler definition

- src/android/toga_android/app.py
- src/cocoa/toga_cocoa/app.py
- src/core/tests/test_app.py
- src/core/toga/app.py
- src/gtk/toga_gtk/app.py
- src/iOS/toga_iOS/app.py
- src/winforms/toga_winforms/app.py
Currently, a handler passed to `toga.TogaApp.add_background_task()` is passed on as-is to the implementation layer and wrapped there. This has the consequence that the first argument passed to the handler is an instance of `toga_impl.App` instead of `toga.TogaApp`, therefore violating the contract that the first argument should be interface layer instance.
This PR fixes this by moving the `wrapped_handler(self, handler)` call to the interface layer.
> Wrap handler in interface layer for `add_background_task()`

- src/winforms/toga_winforms/widgets/webview.py
If no URL is set on a webview, don't try to set the webview's URL.
> Add protection against empty URLs on winforms.

- src/cocoa/toga_cocoa/widgets/canvas.py
The recent change to weak properties broke one of the references to the implementation layer on macOS canvas.
> Correct reference to impl in macOS canvas

- .gitignore
- examples/window/README.rst
- examples/window/pyproject.toml
- examples/window/window/__init__.py
- examples/window/window/__main__.py
- examples/window/window/app.py
- examples/window/window/resources/README
- src/android/toga_android/window.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/test_window.py
- src/core/toga/app.py
- src/core/toga/window.py
- src/dummy/toga_dummy/window.py
- src/gtk/toga_gtk/window.py
- src/iOS/toga_iOS/app.py
- src/iOS/toga_iOS/window.py
- src/web/toga_web/window.py
- src/winforms/toga_winforms/window.py
Window currently maintains an internal proxy of window title, size and position. This can lead to drift between the proxied value and the "true" value.
This PR moves to a "source of truth" model, where the interface interrogates the operating system APIs to obtain size, position and window title.
This requires initialization data to be passed to the implementation layer at time of construction; however, this also allows us to simplify the creation process. 
It also adds a test app to validate that these properties work as expected.
Supercedes (and includes portions of):
* #1395 (thanks to @eliteraspberries)
* #1023 (thanks to @t-arn)
> Move to a "source of truth" model for window title, size and position

- src/winforms/toga_winforms/widgets/webview.py
This PR fixes the problem that on Windows 11, you get an "Access Denied" error when using WebView2 with 'briefcase dev' because Python tries to create the WebView2 user data dir in a subdirectory of the python.exe
With 'briefcase dev', this is a subdirectory of C:\Program Files\PythonXX\ where a normal user does not have write access.
With 'briefcase run', you do not get the error because the user has write access to the folder where the (embedded) python.exe is located.
The PR now sets the WebView2 user data dir to toga.App.app.paths.cache / "WebView2"
> Fix for "access denied" error when using WebView2 on Windows 11

- src/cocoa/toga_cocoa/window.py
Following on from #1461 (and a comment from @samschott), Removes the adjustment for the primary screen origin, as it will always be 0,0.
> Correct the handling of screen origin in window placement on Cocoa

- src/core/toga/app.py
The changes for #1463 altered how the exit paths worked to allow for on_exit handlers to be asynchronous - but didn't account for the case when there isn't an on_exit handler at all.
> Account for app exit with no on_exit handler.

- src/core/toga/app.py
#1435 moved the wrapping of background handlers into the interface layer; #1461 inadvertently reverted that change. 
Thanks to @t-arn for the report and diagnosis.
> Ensure background handlers are wrapped correctly.

- src/gtk/toga_gtk/widgets/webview.py
Small tweaks to the GTK web view:
* Enables the developer menu (so that you can work out why pages aren't rendering)
* Change the cache model to `DOCUMENT_VIEWER`. This ensures that every URL request loads the page; the default mode (`WEB_BROWSER`) has aggressive page caching, which means the content won't be redisplayed even if the web server changes.
* Tweaks the error message with Webkit2 bindings haven't been installed.
> Improvements to GTK Webview

- demo/toga_demo/app.py
Signed-off-by: Nick Moore <nick@zoic.org>
Fixes #1484 ... a trivial RuntimeError bug in toga-demo.
This changes the "action2" action to be asynchronous, which means it can then await the result of the "Is this cool or what?" dialog asynchronously.
> Fixes #1484 by shifting the "action2" action to be asynchronous.

- src/cocoa/toga_cocoa/dialogs.py
Fixes setting the NSTextView in the stack trace dialog being vertically resizable.
> Fix typo in the cocoa stack trace dialog

- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/winforms.py
- src/winforms/toga_winforms/widgets/imageview.py
Some installs seem to disable TLS1.2 and TLS1.3; this ensures those protocols are enabled for Winforms-derived requests.
Also fixes #1416, correcting aspect ratio for images.
Thanks to @rmartin16 for the diagnosis and .NET assistance on this.
> Explicitly define allowed Winforms TLS protocols.

- src/core/toga/window.py
The recent change to async dialogs was not reflected in the docstrings for the methods opening those dialogs.
Thanks to @matteotanghe for the report.
> Fixes #1483 - Update docstrings for dialogs.

- examples/window/window/app.py
- src/cocoa/toga_cocoa/window.py
- src/core/toga/window.py
- src/winforms/toga_winforms/window.py
Corrects an oversight from #1464; analogous to #1466, but with secondary windows.
> Fixes #1482 - If a secondary window doesn't have a close handler, it can still be closed

- src/winforms/toga_winforms/dialogs.py
Calling `MainWindow.select_folder_dialog` would raise `AttributeError`
for `FileName`.
`OpenFileDialog` does not have a `FileName` or `FileNames` property
(nor does it support filtering nor multi-select)
so it cannot be handled the same way as the other two dialogs.
> Fix select folder dialog on Windows

- src/iOS/toga_iOS/widgets/textinput.py
The iOS TextField implementation had an odd line of code that was an obvious typo, and looked like a no-op.
However, when #1328 added weak property declarations, it caused a problem, because accessing a weak property that hasn't been defined causes a segfault.
> Correct a loose reference on iOS.

- src/winforms/toga_winforms/window.py
Ref #1439
Replacing main_window.content was acting as a no op on Windows. By removing the existing controls, then adding the new widget, this fixes that problem. I'm personally concerned that there may be some subtlety I'm missing in the way winforms works here, but it works in the example from the ticket.
Would like to know if anyone is aware of a toga app where this approach would break it and I'll dive back into researching to see if I can use a lighter touch.
Things I did attempt:
* Tried moving setting the content until after the call to set_content, but that caused a number of failures (primarily on startup.)
* identity comparisons of controls don't work the way you would assume in Python. There may be some other kind of identity check I could do that I missed.
Video of the fix on …
> Fix setting main_window.content acts as noop on windows.

- src/winforms/toga_winforms/window.py
Fixes #1420.
The winforms Window constructor wasn't doing anything with the `toga.Window.minimizable` attribute. This PR sets the `Form.MinimizeBox` to the value of `interface.minimizable` which Windows respects. Found the attribute for the Form object here: https://stackoverflow.com/questions/3025923/disabling-minimize-maximize-on-winform
The resizable and closeable attributes were both being respected when I tested.
Tested on Windows 10, build 19044.1706 with Python 3.8.10 and Python 3.10.0
Short video demonstrating fix using the sample application from #1420:
Welcome to feedback on how to test this in an automated fashion.
> Fix minimizable=False on Windows.

- examples/tutorial3/tutorial/app.py
- src/android/toga_android/widgets/webview.py
- src/cocoa/toga_cocoa/libs/__init__.py
- src/cocoa/toga_cocoa/widgets/webview.py
- src/core/toga/widgets/webview.py
- src/dummy/toga_dummy/widgets/webview.py
- src/gtk/toga_gtk/widgets/webview.py
- src/iOS/toga_iOS/widgets/webview.py
- src/winforms/toga_winforms/widgets/webview.py
This PR implements WebView.get_url() for Winforms and Android, so the current URL can be fetched from the implementation.
The PR can be tested with tutorial3 which has been extended to always show the current URL in the url_input field (this updating the url_input field does not work on Android because on_webview_load does not work there. So, for Android, I tested the PR with a print debug statement).
> WebView: Get the current URL from the implementation

- .github/workflows/ci.yml
- MANIFEST.in
- src/android/toga_android/paths.py
- src/cocoa/tests/test_paths.py
- src/cocoa/toga_cocoa/paths.py
- src/core/MANIFEST.in
- src/core/tests/test_paths.py
- src/core/tests/testbed/installed.dist-info/INSTALLER
- src/core/tests/testbed/installed.dist-info/METADATA
- src/core/tests/testbed/installed/__main__.py
- src/core/tests/testbed/installed/app.py
- src/core/tests/testbed/simple/__main__.py
- src/core/tests/testbed/simple/app.py
- src/core/tests/testbed/standalone.py
- src/core/toga/app.py
- src/dummy/toga_dummy/paths.py
- src/dummy/toga_dummy/utils.py
- src/gtk/tests/test_paths.py
- src/gtk/toga_gtk/paths.py
- src/iOS/toga_iOS/paths.py
- src/web/toga_web/paths.py
- src/winforms/tests/test_paths.py
- src/winforms/toga_winforms/paths.py
- tox.ini
When running an application as a single file, as a module, e.g:
`python -m app` on a `app.py` file,
Toga would not assume the working directory to resolve relative paths, and would fail to load local app resources.
`factory.paths.app` is now built using `__main__.__file__`.
This works both for:
- apps inside packages: `__main__.__file__` returns the path for the app package `__main__.py`.
- when the app is launched from single startup script: `__main__.__file__` returns the path for the single startup script.
The old method used  `sys.modules[App.app.module_name].__file__)`,  which returns the path for the app package `__init__.py`.
But for apps launched from a single startup script, `App.app.module_name` is set to `toga`. In that case, only resources on the `toga` package could be …
> Return the correct factory.paths.app, even when launched as a single file

- setup.cfg
- src/winforms/toga_winforms/libs/proactor.py
I've noticed that every time I run a BeeWare app on Windows, my laptop fan spins up. I've also noticed that whenever a BeeWare app is running, my VcXsrv X server locks up, preventing me from using any graphical Linux apps at the same time.
This was caused by the `PostMessageA` line in the event loop. `0xffff` doesn't just send the message to every window in the current app, it sends it to every window in *every* running app, 200 times per second.
As I understand it, this window message mechanism is a partially-disabled implementation left over from #741, which was intended to address #750 but was blocked by a bug in python.net.
I could comment out the rest of the window message code, but I think it's confusing having fragments of two different implementations mixed together in the file, …
> Windows: remove unused window message mechanism from event loop

- src/winforms/toga_winforms/app.py
If the app thread raises an exception, re-raise in the main thread context.
At present, if an app-terminating exception raised, it is caught inside the thread, printed, and then swallowed. This causes the application to terminate, but from the perspective of the main thread, the application completed successfully. This makes it difficult to identify at a process level when apps are failing.
> Improve top-level exception handling in Windows apps.

- docs/reference/style/pack.rst
Two minor edits:
* Corrected a typo: "``text_align`` value of ``center``" -> "``alignment`` value of ``center``"
* Changed all instances of "a ``alignment``" to "an ``alignment``"
- [N/A] All new features have been tested
- [N/A] All new features have been documented
> Pack algorithm documentation: typo & grammar corrections

- docs/how-to/contribute.rst
- src/core/toga/widgets/progressbar.py
- src/django/README.rst
- src/flask/README.rst
- src/winforms/toga_winforms/widgets/slider.py
There are small typos in:
- docs/how-to/contribute.rst
- src/core/toga/widgets/progressbar.py
- src/django/README.rst
- src/flask/README.rst
- src/winforms/toga_winforms/widgets/slider.py
Fixes:
- Should read `continuous` rather than `continous`.
- Should read `achieved` rather than `acheived`.
- Should read `initial` rather than `inital`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- src/winforms/toga_winforms/dialogs.py
This PR aims to add functionality for the `initial_directory` argument of `select_folder_dialog` on Windows, fixing #1244.
The way that this is currently done in this PR is through the `SelectedPath` property of `FolderBrowserDialog`s. The initial directory will now be preselected in the dialog -- this does not match up perfectly with the behaviour of `initial_directory` for `open_file_dialog`, but it will still provide a useful, roughly equivalent function.
The changes to code may or may not be complete already, but more testing (and potentially documentation) is likely still needed right now.
> Add support for select_folder_dialog initial_directory on Windows

- examples/box/box/app.py
- examples/canvas/canvas/app.py
- examples/focus/focus/app.py
- examples/progressbar/progressbar/app.py
- examples/scrollcontainer/scrollcontainer/app.py
- examples/switch_demo/switch_demo/app.py
- src/android/toga_android/widgets/switch.py
- src/cocoa/toga_cocoa/widgets/switch.py
- src/core/tests/testbed/bootstrap.py
- src/core/tests/testbed/subclassed/__main__.py
- src/core/tests/testbed/subclassed/app.py
- src/core/tests/widgets/test_switch.py
- src/core/toga/widgets/switch.py
- src/dummy/toga_dummy/widgets/switch.py
- src/gtk/tests/widgets/test_switch.py
- src/gtk/toga_gtk/widgets/switch.py
- src/iOS/toga_iOS/widgets/switch.py
- src/winforms/toga_winforms/widgets/switch.py
The Switch widget API becomes more consistent with other widgets by renaming some properties:
- label -> text
- is_on -> value
- on_toggle -> on_change
The legacy API still works, with deprecation warnings. Exceptions are raised if both the new and old init parameters are used. The label text parameter, now called `text`, was temporarily changed to keyword argument. It should be changed back to positional argument when the compatibility code is removed.
> API consistency: switch widget

- src/android/toga_android/app.py
- src/android/toga_android/libs/android/__init__.py
- src/android/toga_android/libs/android/view.py
- src/android/toga_android/window.py
This is the Toga part of the fix described in https://github.com/beeware/briefcase-android-gradle-template/pull/50.  It mostly works, but the viewport height is slightly wrong after rotation because the action bar is narrower in landscape orientation. I'll look into this and add another commit.
> Android: update layout after rotation

- examples/activityindicator/activityindicator/app.py
- examples/box/box/app.py
- examples/button/button/app.py
- examples/canvas/canvas/app.py
- examples/focus/focus/app.py
- examples/font/font/app.py
- examples/layout/layout/app.py
- examples/selection/selection/app.py
- src/android/toga_android/dialogs.py
- src/android/toga_android/widgets/button.py
- src/cocoa/toga_cocoa/widgets/button.py
- src/core/tests/widgets/test_button.py
- src/core/toga/widgets/button.py
- src/dummy/toga_dummy/widgets/button.py
- src/gtk/toga_gtk/widgets/button.py
- src/iOS/toga_iOS/widgets/button.py
- src/web/toga_web/widgets/button.py
- src/winforms/toga_winforms/widgets/button.py
Used the same approach as the Switch.label rename
> API consistency: Button widget

- .github/workflows/ci.yml
Github has [announced that they have deprecated the 10.15 runner, and will remove it by 30 Aug 2022](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/). This moves macOS CI to macOS-latest.
> Run CI on macOS-latest

- examples/canvas/canvas/app.py
- examples/date_and_time/date_and_time/app.py
- examples/multilinetextinput/multilinetextinput/app.py
- examples/numberinput/numberinput/app.py
- examples/slider/slider/app.py
- examples/tutorial3/tutorial/app.py
- src/core/tests/widgets/test_datepicker.py
- src/core/tests/widgets/test_multilinetextinput.py
- src/core/tests/widgets/test_numberinput.py
- src/core/tests/widgets/test_slider.py
- src/core/tests/widgets/test_textinput.py
- src/core/tests/widgets/test_timepicker.py
- src/core/toga/widgets/datepicker.py
- src/core/toga/widgets/multilinetextinput.py
- src/core/toga/widgets/numberinput.py
- src/core/toga/widgets/slider.py
- src/core/toga/widgets/textinput.py
- src/core/toga/widgets/timepicker.py
Making the init param consistent with the widget property.
What I didn't do: re-use the 'default' param to implement actual default semantics (as was mentioned here: https://github.com/beeware/toga/discussions/1521#discussioncomment-3160501).
> Renamed 'initial' and 'default' init params to 'value'

- src/iOS/toga_iOS/widgets/scrollcontainer.py
On iOS, if a ScrollContainer widget doesn't have any content, the request to rehint the size of the widget will generate an error. This can happen if no content has been assigned to the widget; but it can also happen during app startup, as the first rehint occurs before any content is assigned.
Tested with the scrollcontainer demo app, plus the test case provided on #1473. The Scrollcontainer demo app raises errors associated with the use of Commands, but that doesn't stop the app from running.
> Refs #1473 - Check for content before updating content size.

- src/winforms/toga_winforms/widgets/canvas.py
pythonnet/pythonnet#1833 reveals a problem passing float-like numpy types to Winforms APIs. This causes problems with toga-chart, as it uses numpy types internally.
Adding explicit casts to float avoids these problems. Eventually, we'll be able to remove these casts; but for now it doesn't hurt.
Fixes beeware/toga-chart#16.
> Add explicit casts to float in Winforms canvas.

- docs/reference/style/pack.rst
- src/core/tests/style/test_pack.py
- src/core/toga/style/pack.py
I am trying to get a deeper understanding of the Pack layout. As an exercise, I copied one of the tests and swapped the horizontal and vertical dimensions. This exposed (I believe) two bugs in the algorithm.
In both cases, the symmetry of the code was broken. My changes bring back the symmetry.
My case is purely synthetic, and those changes in symmetry might be features, not bugs. But in that case, they should be documented.
> New Pack test: transposed layout

- examples/imageview/imageview/app.py
- src/core/tests/test_image.py
- src/core/toga/images.py
I probably should have announced my intentions to work on this before actually working on it, but ah well.
This pull request aims to implement the functionality described in issue #1294. Currently, `toga.Image` expects to be given a string, and will error if given a `pathlib.Path` object. Under this PR, it will convert the given `path` argument to a string, allowing `pathlib.Path` objects to be used to construct images without having to manually convert to a string.
The `imageview` example has also been modified to add a test case for passing in `pathlib.Path` objects to `toga.Image`.
Potential concerns:
- The PR currently does not do any type checking of the `path` argument, though Toga in general does not do much type checking and it's hard for me to imagine a situation where converting …
> Cast pathlib.Path to string in Image()

- src/android/toga_android/widgets/base.py
- src/core/tests/widgets/test_base.py
- src/core/tests/widgets/test_optioncontainer.py
- src/core/tests/widgets/test_scrollcontainer.py
- src/core/tests/widgets/test_splitcontainer.py
- src/core/toga/widgets/base.py
- src/core/toga/widgets/optioncontainer.py
- src/core/toga/widgets/scrollcontainer.py
- src/core/toga/widgets/splitcontainer.py
- src/dummy/toga_dummy/factory.py
- src/dummy/toga_dummy/widgets/base.py
- src/gtk/toga_gtk/widgets/base.py
- src/iOS/toga_iOS/widgets/base.py
- src/winforms/toga_winforms/widgets/base.py
- src/winforms/toga_winforms/widgets/scrollcontainer.py
Fixes #833 
Now, for every container, app is set for it's content once it is set for the container.
Done for `OptionContainer`, `SplitContainer` and `ScrollContainer`.
> Fix containers app

- examples/command/command/app.py
- examples/focus/focus/app.py
- examples/tutorial2/tutorial/app.py
- src/android/toga_android/app.py
- src/cocoa/toga_cocoa/app.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/command/test_command.py
- src/core/tests/command/test_commands_group.py
- src/core/tests/command/test_commands_set.py
- src/core/toga/command.py
- src/core/toga/widgets/button.py
- src/core/toga/widgets/switch.py
- src/gtk/toga_gtk/app.py
- src/gtk/toga_gtk/window.py
- src/winforms/toga_winforms/app.py
- src/winforms/toga_winforms/window.py
As discussed in https://github.com/beeware/toga/discussions/1521
> Renamed 'label' to 'text' for Command and Group

- src/winforms/toga_winforms/widgets/canvas.py
Fix the same bug described in #1559 
Now the problem is with setting `Pen.DashPattern`:
```
File "c:\users\sagi\pycharmprojects\toga\src\winforms\toga_winforms\widgets\canvas.py", line 144, in create_pen
pen.DashPattern = line_dash
File "c:\users\sagi\pycharmprojects\toga\src\winforms\toga_winforms\widgets\canvas.py", line 272, in stroke
pen = self.create_pen(color=color, line_width=line_width, line_dash=line_dash)
File "c:\users\sagi\pycharmprojects\toga\src\core\toga\widgets\canvas.py", line 474, in _draw
impl.stroke(self.color, self.line_width, self.line_dash, *args, **kwargs)
File "c:\users\sagi\pycharmprojects\toga\src\core\toga\widgets\canvas.py", line 43, in _draw
obj._draw(impl, *args, **kwargs)
File …
```
> Fix bug in windows `DashPattern`

- .github/workflows/ci.yml
- src/core/tests/test_paths.py
Some core tests fail on Windows due to the paths not being capitalised.
I have fixed this by using the resolve() method which is part of pathlib.
I have re-run the core tests on both Windows and Linux successfully.
Fixes #1567
> Fix capitalisation bug in test_paths

- examples/optioncontainer/optioncontainer/app.py
- src/cocoa/toga_cocoa/widgets/optioncontainer.py
- src/core/tests/widgets/test_optioncontainer.py
- src/core/toga/widgets/optioncontainer.py
- src/dummy/toga_dummy/widgets/optioncontainer.py
- src/gtk/toga_gtk/widgets/optioncontainer.py
- src/winforms/toga_winforms/widgets/optioncontainer.py
Added a few tests to increase coverage of OptionContainer.
There was a bug: inserting a tab (not adding it after existing tabs) was not working. 
Fixed for toga_cocoa, I left `FIXME` comments for other platforms.
Maybe a convenience `insert` method should be added to OptionContainer, instead of calling `.content.insert()`
Or `.add()` could have an optional `index` parameter?
> Improve coverage of OptionContainer

- src/core/tests/style/test_pack.py
- src/core/toga/style/pack.py
This pull request aims to fix the two bugs in the layout code that I pointed out on Discord: alignment taking padding into account incorrectly, and left alignment and right alignment being switched from how they should be.
More work is likely needed regarding tests for this behaviour, so this pull request is not yet ready for review.
> Pack layout system: fixing two bugs

- tox.ini
This change provides a more useful output when using `tox` to run the test suite on the command line, e.g.:
```
tox -e py310
```
Will run the test suite in a python 3.10 environment, and the coverage report will include the line numbers not being covered by the tests.
It is possible to pass other parameters to `pytest`, e.g.:
```
tox -e py310 -- tests/test_platform.py 
```
Will only run the tests in the specified file.
> Add "missing" lines to coverage report, and allow for extra parameters

- examples/optioncontainer/optioncontainer/app.py
- src/cocoa/toga_cocoa/widgets/optioncontainer.py
- src/core/tests/widgets/test_optioncontainer.py
- src/core/toga/widgets/optioncontainer.py
- src/dummy/toga_dummy/widgets/optioncontainer.py
- src/gtk/toga_gtk/widgets/optioncontainer.py
- src/winforms/toga_winforms/widgets/optioncontainer.py
As discussed on https://github.com/beeware/toga/discussions/1521
> API consistency: OptionContainer

- .gitignore
- examples/window/window/app.py
- src/winforms/setup.cfg
- src/winforms/toga_winforms/window.py
**Description**
After the fix in #1572 , when setting the `content` property of a window in Windows, its menu strip is disappeared.
**Reproduction steps**
On a Windows computer:
1. Run the "window" example"
2. Click the "change content" button
3. See that the main menu strip above (File, Help, etc.) is gone.
**Solution**
The fix is simple: when we setting the content we clear all the Controls of the window, including the main menu strip. We simply need to add it back.
> Fix bug of disappearing main menu strip

- examples/textinput/textinput/app.py
- src/android/toga_android/widgets/textinput.py
- src/cocoa/toga_cocoa/widgets/textinput.py
- src/core/tests/widgets/test_textinput.py
- src/core/toga/widgets/textinput.py
- src/dummy/toga_dummy/utils.py
- src/dummy/toga_dummy/widgets/textinput.py
- src/gtk/toga_gtk/widgets/textinput.py
- src/iOS/toga_iOS/widgets/textinput.py
- src/winforms/toga_winforms/widgets/textinput.py
Fixes #1582 
Added `TextInput.is_valid` property as suggested in the linked issue.
> Text input is valid property

- examples/window/window/app.py
- src/android/toga_android/window.py
- src/cocoa/toga_cocoa/window.py
- src/core/tests/test_window.py
- src/core/toga/window.py
- src/dummy/toga_dummy/window.py
- src/gtk/toga_gtk/window.py
- src/iOS/toga_iOS/window.py
- src/web/toga_web/window.py
- src/winforms/toga_winforms/window.py
Fixes #1553 
This is an implementation of the API described in the linked issue.
Now, one can programmatically hide and show a window. Moreover, a `Window.visible` attribute was add to indicate if a window is visible or not.
Added an implementation for Windows and empty implementation for all other platforms.
Added relevant unit tests and made coverage of `toga.Window` 100%.
> Window hide method and visible

- src/winforms/toga_winforms/app.py
On Windows, the default network settings do not enable TLS1.2 or TLS1.3, so we explicitly enable TLS1.2 and 1.3 support.
However, TLS1.3 support was only added in .NET 4.8, and it's possible that end-users won't have .NET 4.8 installed. This manifests as an AttributeError accessing the `Tls13` constant (Refs beeware/beeware#170)
Rather than crashing when the user has an older version of .NET, this PR raises a warning to the user. An app that doesn't use web content won't be affected by the lack of TLS1.2/1.3 support; apps that *do* use web content will fail to connect to the server, which is bad, but having a log entry describe the problem is better than an outright crash.
> Add fallback when TLS1.2/1.3 support isn't present

- src/android/toga_android/app.py
- src/dummy/toga_dummy/test_implementation.py
The Android Window class inherits a Java interface in order to be notified of screen rotations. Unfortunately Chaquopy doesn't currently allow classes that inherit Java interfaces to be further subclassed (https://github.com/chaquo/chaquopy/issues/659#issuecomment-1210225928). So this PR just makes MainWindow identical to Window, and updates the AST unit tests to accept that.
> Android: make MainWindow identical to Window

- examples/multilinetextinput/multilinetextinput/app.py
- src/android/toga_android/widgets/multilinetextinput.py
This PR adds the missing on_change() and set_color() implementation for MultilineTextInput on Android
The changes can be tested with the MultilineTextInput and Color examples.
> Multilinetextinput android: added on_change and set_color

- src/android/toga_android/widgets/multilinetextinput.py
This PR fixes the problem that on_change was called before the widget was fully configured
When running the MultilineTextInput example (without this bugfix) on Android, you get following error message:
D Python  : Native invocation 129448237098512 :: afterTextChanged
E Python  : Traceback (most recent call last):
E Python  :   File
"/data/user/0/org.beeware.multilinetextinput/files/python/user_code/app_packages/rubicon/java/api.py", line 54, in dispatch
E Python  :     val = getattr(pyinstance, method)(*args)
E Python  :   File "/data/user/0/org.beeware.multilinetextinput/files/python/user_code/app_packages/toga_android/widgets/multilinetextinput.py", line 23, in afterTextChanged
E Python  :     if self.interface.on_change:
E Python  :   File …
> BugFix for MultilineTextInput on Android

- src/android/toga_android/widgets/textinput.py
- src/core/toga/widgets/textinput.py
This PR fixed problem that on_change was called before the widget was fully configured
It also makes sure (on all platforms) that setting the initial value does not trigger the on_change event
> Bugfix for TextInput on_change on Android

- examples/imageview/imageview/app.py
- examples/imageview/pyproject.toml
- src/android/toga_android/images.py
- src/cocoa/toga_cocoa/images.py
- src/cocoa/toga_cocoa/libs/foundation.py
- src/core/tests/test_image.py
- src/core/toga/images.py
- src/dummy/toga_dummy/images.py
- src/gtk/toga_gtk/images.py
- src/iOS/toga_iOS/images.py
- src/winforms/toga_winforms/images.py
- src/winforms/toga_winforms/libs/__init__.py
- src/winforms/toga_winforms/libs/winforms.py
Currently Image loads files by file path or URL. This PR adds a `bytes` object as an option.
Refs #1348
I'd like feedback on whether overloading the positional argument for the Image constructor is well received. Its name, `path`, makes no sense anymore. I changed it to value.
Implemented on all backends, but only tested on macOS.
> Load Image from bytes

- src/android/toga_android/widgets/selection.py
Fixes #1603. This is caused by Chaquopy representing Java objects as their runtime type, versus Rubicon which used the declared type. `getSelectedItem` is declared to return `Object`, but in this case it'll always return a `String`, so Chaquopy automatically converts it to a Python `str` and it won't have a `toString` method anymore.
Using `str` rather than `toString` fixes this while maintaining backward compatibility with Rubicon.
I checked all the other uses of `toString` in toga_android, but none of them are on objects which could already be Strings, so they're all fine.
> Android: replace `toString` with `str` in Selection

- src/android/toga_android/widgets/numberinput.py
Fixes #1615. Like #1616, this is another case of Rubicon logging and ignoring a Python exception, but Chaquopy passing it through to the Android main loop, causing the app to crash.
Fixed by catching the `Decimal` conversion exception and setting the widget's `value` to `None`. Because the native widget is set to only accept numbers, the only invalid inputs I could find were the empty string, or a single `.`, `+` or `-`.
> Android: make NumberInput handle exception when Decimal conversion fails

- src/core/toga/widgets/switch.py
Same idea as #1610.
To reproduce, run examples/box on Android:
```
com.chaquo.python.PyException: AttributeError: 'Switch' object has no attribute '_on_change'
at <python>.toga.widgets.switch.on_change(switch.py:137)
at <python>.toga_android.widgets.switch.onCheckedChanged(switch.py:18)
at <python>.chaquopy_java.call(chaquopy_java.pyx:379)
at <python>.chaquopy_java.Java_com_chaquo_python_PyObject_callAttrThrowsNative(chaquopy_java.pyx:351)
at com.chaquo.python.PyObject.callAttrThrowsNative(Native Method)
at com.chaquo.python.PyObject.callAttrThrows(PyObject.java:232)
at com.chaquo.python.PyInvocationHandler.invoke(PyInvocationHandler.java:31)
at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
at $Proxy15.onCheckedChanged(Unknown Source)
at …
```
> Ensure the Switch on_change handler has a value before it might be used

- src/android/toga_android/widgets/scrollcontainer.py
Fixes #1604.
The reason this issue appeared in dev36 was because of #1507. Before that, the widget passed to AndroidViewport was only used to get at the Resources object, so all viewports were the same size: a rather unreliable estimate of the size of the whole window. #1507 changed AndroidViewport to return the dimensions of the widget that was passed to it. 
So this PR fixes ScrollContainer to create its viewport from the container, not the content.
> Android: make ScrollContainer use correct widget for viewport

- MANIFEST.in
- pyproject.toml
- setup.cfg
- src/android/pyproject.toml
- src/android/setup.cfg
- src/cocoa/pyproject.toml
- src/cocoa/setup.cfg
- src/core/pyproject.toml
- src/core/setup.cfg
- src/dummy/pyproject.toml
- src/dummy/setup.cfg
- src/gtk/pyproject.toml
- src/gtk/setup.cfg
- src/iOS/pyproject.toml
- src/iOS/setup.cfg
- src/web/pyproject.toml
- src/web/setup.cfg
- src/web/setup.py
- src/winforms/pyproject.toml
- src/winforms/setup.cfg
#1614 modified the packaging of wheels, using the [automatic discovery](https://setuptools.pypa.io/en/latest/userguide/package_discovery.html#automatic-discovery)  feature of Setuptools.
While this appears to generate working wheels, it doesn't produce working source installs, which is required for any of the examples in the Toga repository to work.
Automatic discovery is marked as a beta feature; so reverting may be a good idea.
This PR also:
* Corrects the lack of a toga-core dependency in toga-web
* The lack of pyproject.toml files; pip 22.3 starts complaining about these aggressively.
* The packaging of the top level wheel, ensuring that it is a pure stub with no code content.
* The manifest exclusions in the top level package.
Fixes #1632.
> Revert usage of automatic discovery by setuptools.

- src/core/src/toga/platform.py
pypa/setuptools#3649 causes duplicated entry points to be registered when a package is installed editable. Use `set()` to remove duplicates prior to selecting the appropriate backend.
Fixes #1636.
> Remove duplicate entry points caused by editable installs.

- src/winforms/setup.py
- src/winforms/src/toga_winforms/widgets/canvas.py
[Pythonnet 3.0.0](https://github.com/pythonnet/pythonnet/releases/tag/v3.0.0) has been released!
Therefore, toga_winforms should no longer to rely on an alpha version of Pythonnet.
Also, removed redundant float conversions which where fixed in Pythonnet new version.
> Update Pythonnet to 3.0.0

- .github/dependabot.yml
- .github/workflows/dependabot-changenote.yml
Enable dependabot, including workflows to add a changenote when dependencies are updated.
The `BRUTUS_PAT_TOKEN` has been added to repo settings; however, dependabot has *not* been turned on; that should be turned on when this configuration is in place.
Configuration largely copied from Briefcase.
> Add Dependabot configuration.

- changes/1659.bugfix.rst
- changes/1660.bugfix.rst
- src/cocoa/src/toga_cocoa/window.py
- src/core/src/toga/window.py
- src/core/tests/test_window.py
- src/dummy/src/toga_dummy/window.py
Two corrections to recent changes in window and widget handling.
1. Ensures that NSWindow retains a backreference to the interface and impl of the window. These previously existed, but were  removed by #1328 when references were made weak. However, the `current_window()` implementation requires that the native widget can navigate back to the interface. This PR re-introduces the references, but as weak references so that there won't be circular references.
2. Modifies the handling of the app registry, removing the explicit addition of a window's widgets to the app registry when the window is assigned to an app. This was introduced by #1599, with a test; however, the test was unrealistic - it defined a collection of widgets, and manually added them to the window's widget repository without …
> Corrections to widget and window handling

- changes/1699.bugfix.rst
- winforms/src/toga_winforms/libs/__init__.py
- winforms/src/toga_winforms/libs/winforms.py
- winforms/src/toga_winforms/widgets/datepicker.py
Fixes #1699. 
The Winforms native datepicker widget "Value" attribute is a native DateTime object. This converts the DateTime object to text using the ISO 8601 format. It is then parsed to a Python datetime object using strptime(). This solves the problem of the date format being dependent on local Windows settings.
> Fix winforms datepicker widget unexpected date format

- android/src/toga_android/app.py
- changes/1705.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- core/tests/test_app.py
- dummy/src/toga_dummy/app.py
- dummy/src/toga_dummy/utils.py
- gtk/src/toga_gtk/app.py
- iOS/src/toga_iOS/app.py
- web/src/toga_web/app.py
- winforms/src/toga_winforms/app.py
Consolidates the common implementation of `add_background_task()` into the interface, and uses the threadsafe `call_soon` variant.
As a review note: This means that the `loop` attribute is now part of the public "_impl" API. I've opted for the simple approach here of just assuming the attribute exists; however, it may be worth considering whether we should promote `loop` to the interface layer (with construction of the loop deferred to the backend), or add a formal impl API for accessing the loop from the interface layer.
Fixes #1705.
> Use call_soon_threadsafe for background tasks, and consolidate implementation

- .github/workflows/ci.yml
- changes/1712.misc.rst
- core/tests/utils.py
The CI pass for #1709 revealed 2 problems with our CI configuration:
1. GitHub Actions has moved ubuntu-latest to 22.04; this no longer has fuse2 by default, causing AppImage runtime tests to fail
2. Python 3.12.0a3 formally changed the long-deprecated behavior of `asyncio.get_event_loop()`.
> Corrections to address CI failures

- .github/workflows/dependabot-changenote.yml
- changes/1709.misc.rst
Use centralized workflow to add dependabot changenote.
- beeware/.github#2
> Use dependabot changenote CI workflow from .github repo

- changes/1710.feature.rst
- gtk/src/toga_gtk/widgets/canvas.py
Add GTK implementation for canvas events.
I've manually tested the following with `./examples/canvas`:
> implement gtk canvas events

- changes/1724.doc.rst
- pyproject.toml
- tox.ini
Before:
```
* Apps can now specify the order in which widgets receive focus. (#1686)
```
After:
```
* Apps can now specify the order in which widgets receive focus. (`#1686 <https://github.com/beeware/toga/issues/1686>`__)
```
Although this always produces an `/issues` URL, GitHub will automatically redirect it to a `/pull` URL if the number happens to refer to a PR.
> Make release history issue numbers into GitHub links

- android/src/toga_android/widgets/multilinetextinput.py
- changes/1728.feature.rst
- cocoa/src/toga_cocoa/widgets/multilinetextinput.py
- core/src/toga/widgets/multilinetextinput.py
- dummy/src/toga_dummy/widgets/multilinetextinput.py
- examples/multilinetextinput/multilinetextinput/app.py
- gtk/src/toga_gtk/widgets/multilinetextinput.py
- iOS/src/toga_iOS/widgets/multilinetextinput.py
- winforms/src/toga_winforms/widgets/multilinetextinput.py
This PR adds the features `scroll_to_bottom()` and `scroll_to_top()` to the `MultilineTextInput` widget.
It's implemented for Windows, Linux , MacOS and Android. ~~The implementation for Android seems straight-forward, but I haven't set up a testing environment for this OS.~~
Use this example app for testing:
```python
"""
Demo for scroll to top/bottom
"""
import toga
class Multiline_scroll(toga.App):
"""Demo app to demonstrate scroll_to_bottom/_top for MultilineTextInput."""
main_box = toga.Box(style=Pack(direction=COLUMN))
text_box = toga.Box(style=Pack(direction=COLUMN))
button_box = toga.Box(style=Pack(direction=ROW))
self.mlti = toga.MultilineTextInput(style=Pack(padding=(10, 70), height=60)) …
```
> MultilineTextInput: scrolling to top and bottom

- changes/1733.doc.rst
- changes/1733.misc.rst
- docs/background/commands.rst
Was getting a syntax error and it seems it is due to a missing comma:
https://toga.readthedocs.io/en/latest/background/commands.html#:~:text=icon%3D%27icons/pretty.png%27
> add missing comma in example code

- README.rst
- changes/1740.misc.rst
An oversight of the master->main conversion - the CI badges in the README still referred to the master branch.
> Update stale branch references in README badges.

- changes/1751.misc.rst
- cocoa/setup.py
- iOS/setup.py
Updates cocoa and iOS to set a rubicon 0.4.5rc1 minimum version. This is required because 0.4.4 had to be yanked, as it is incompatible with the version of Toga that is available for general use (0.3.0dev39). By publishing a prerelease version of Rubicon, and then including a version specifier that will pick up that prerelease, we can have access to the new features of Rubicon without affecting current production users.
This will fail CI until rubicon-objc 0.4.5rc1 is publishes (hopefully early tomorrow).
Fixes #1750
> Adopt Rubicon 0.4.5rc1

- changes/1756.bugfix.rst
- cocoa/src/toga_cocoa/widgets/numberinput.py
Setting the `enabled` state on `toga_cocoa.widgets.NumberInput` would inherit the parent method and set the enabled state on the `native` layer, in this case a TogaView.
It makes more sense for this widget to set the `enabled` state on the text input and stepper which are the UI elements that a user interacts with.
> [cocoa] Fix enabled state for NumberInput

- changes/1757.bugfix.rst
- cocoa/src/toga_cocoa/widgets/numberinput.py
Fix accessing the implementation layer (`_impl` -> `impl`) in TogaStepper which is part of the NumberInput widget.
> [cocoa] Fix impl access in NumberInput widget

- changes/1750.misc.rst
- core/setup.cfg
- docs/conf.py
The documentation for Toga 0.3.0 has a title in the sidebar that describes the version as 0.3.1dev0+gcddb9e4a.d20230130. This is a setuptools_scm version indicating that the branch being used to build the release is dirty, but has 0 commits.
This PR:
1. Switches to using install metadata rather than setuptools_scm to determine the release version. This is the approach [recommended by setuptools_scm](https://github.com/pypa/setuptools_scm#usage-from-sphinx), because RTD can change the working directory, causing the dirty version tag. It also removes the need to have setuptools-scm in the documentation environment.
2. Modifies the title template to drop the redundant "Documentation".
> Correct version handling in docs.

- .github/workflows/pre-commit-update.yml
- changes/1765.misc.rst
Forgot that `toga` has many packages in it; add `./core[dev]` as `pre-commit` source in workflow.
> Specify source of `pre-commit` in workflow

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- changes/1771.misc.rst
Implements shared workflows from beeware/.github#8
- `pre-commit-run`
- `towncrier-run`
- `python-package-create`
> Use Shared CI Workflows

- changes/1786.doc.rst
- docs/reference/style/pack.rst
Added a note mentioning that the values should be passed as strings. Added missing ``font_style`` description and missing value of ``visibility``.
> New Update pack.rst

- changes/1783.bugfix.rst
- cocoa/src/toga_cocoa/widgets/multilinetextinput.py
For some reason, NSTextView requires an additional flag to make it adhere to dark mode default coloration.
Fixes #1783.
> Make Cocoa Multilinetextview adhere to darkmode default colors

- .readthedocs.yaml
- changes/1802.misc.rst
- docs/_static/custom.css
- docs/conf.py
- docs/reference/style/pack.rst
The fonts in the Furo style sheet are:
```
-apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji;
```
On macOS, this resolves to the system font SF, where the black and white circles are the same size, and fairly large. But on Windows it uses Segoe UI, where the black circle is much smaller than the white one.
This PR makes the tables use fonts whose circles are equally-sized, and fit in well with the specified font size.
I considered using other Unicode circles instead, but none of them worked well enough:
* The "medium" circles appeared as emojis by default, which stopped them responding to dark mode. There's a variation character which is supposed to switch them back to text mode, but it only worked on Windows, not macOS. 
* The "large" …
> Make API support table circles a more consistent size

- .github/workflows/ci.yml
- README.rst
- changes/1813.misc.rst
- docs/tutorial/tutorial-0.rst
- testbed/CHANGELOG
- testbed/LICENSE
Similar to https://github.com/beeware/briefcase/pull/1130.
> Run testbed on fixed Ubuntu version and corresponding system Python version

- android/src/toga_android/widgets/box.py
- android/tests_backend/widgets/box.py
- android/tests_backend/widgets/label.py
- changes/1820.feature.rst
- cocoa/src/toga_cocoa/widgets/box.py
- cocoa/tests_backend/widgets/base.py
- cocoa/tests_backend/widgets/box.py
- cocoa/tests_backend/widgets/label.py
- core/src/toga/widgets/box.py
- core/tests/test_deprecated_factory.py
- core/tests/widgets/test_box.py
- docs/reference/api/containers/box.rst
- docs/reference/data/widgets_by_platform.csv
- iOS/src/toga_iOS/widgets/box.py
- iOS/tests_backend/widgets/base.py
- iOS/tests_backend/widgets/box.py
- iOS/tests_backend/widgets/label.py
- testbed/tests/widgets/properties.py
- testbed/tests/widgets/test_box.py
A testing and documentation audit of the `toga.Box` widget.
Includes the content from #1819.
> [widget audit] toga.Box

- changes/1826.bugfix.rst
- gtk/src/toga_gtk/container.py
The rendering optimisation introduced by #1794 was a little bit *too* optimised; while a recalculation of geometry isn't required on every redraw, we *do* need to involve `set_allocation()` on all child widgets. If this doesn't happen, animations on widgets like Switch and ProgressBar don't get rendered correctly.
Fixes #1826.
> Correct issues with animated widgets on GTK

- .github/workflows/ci.yml
- changes/1835.misc.rst
- cocoa/src/toga_cocoa/window.py
- core/src/toga/colors.py
- core/src/toga/constants/__init__.py
- core/src/toga/fonts.py
- gtk/src/toga_gtk/container.py
- gtk/src/toga_gtk/libs/gtk.py
- setup.cfg
- Remove unnecessary `noqa` markers and clarify unqualified markers
- Simplify `flake8` configuration
- Remove `max-complexity`.....30 is pretty high and I'm guessing someone was just trying to disable the check
- Use [default](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-ignore) list of checks to `exclude`
- E266 - Too many leading '#' for block comment
- This doesn't seem to be relevant anymore
- E501 - Line too long
-  All (well, nearly all) of the problem cases were already marked
- W503 - Line break occurred before a binary operator
- In the default list of excluded checks
- Update CI to cancel the current run if a PR receives new commits
> Flake8 tweaks

- changes/1863.feature.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/style/applicator.py
- examples/window/window/app.py
- winforms/src/toga_winforms/app.py
- winforms/src/toga_winforms/window.py
Added support for `set_full_screen` so that both `enter_full_screen` and `exit_full_screen` works in WinForms.
> Added support for `set_full_screen` in WinForms.

- changes/1868.doc.rst
- docs/how-to/contribute-code.rst
- docs/how-to/contribute-docs.rst
- docs/spelling_wordlist
- nursery/textual/CONTRIBUTING.md
- nursery/textual/MANIFEST.in
- nursery/textual/README.rst
- nursery/textual/pyproject.toml
- nursery/textual/setup.cfg
- nursery/textual/setup.py
- nursery/textual/tests/test_implementation.py
- nursery/textual/toga_textual/__init__.py
- tox.ini
Update the contribution guide to provide more suggestions for areas to contribute, and to explain how the backend tests work.
Also adds the `{posargs}` improvement to the core test runner.
Lastly, includes a nursery project for a textual backend, since the docs reference that backend as a possible area of contribution.
> Update the contribution guide

- changes/1882.misc.rst
- core/setup.cfg
- tox.ini
- With the release of sphinx-csv-filter v0.4.1, Toga docs can be built in parallel.
- Using the `-r\--recreate` flag for `tox` may be necessary to update sphinx-csv-filter.
- This should drastically speed up builds on many core machines.
> Builds docs in parallel

- changes/1887.feature.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- dummy/src/toga_dummy/app.py
- examples/window/window/app.py
- gtk/src/toga_gtk/app.py
- web/src/toga_web/app.py
- winforms/src/toga_winforms/app.py
An API for setting a window into active focus was added.
> Added support for current_window setter.

- changes/1893.feature.rst
- core/src/toga/widgets/base.py
- core/tests/widgets/test_base.py
> Add a `clear` method that removes all children.

- changes/1901.feature.rst
- docs/reference/data/widgets_by_platform.csv
- web/src/toga_web/factory.py
- web/src/toga_web/libs.py
- web/src/toga_web/widgets/progressbar.py
- web/src/toga_web/widgets/switch.py
Add new widgets for the web platform:
* ProgressBar
* Switch
Also adds a pyodide import to `toga_web.libs` so we can use the `create_proxy` function to avoid having our proxies destroyed as seen [here](https://github.com/pyodide/pyodide/issues/2498).
> Add progressbar and switch widgets to web platform.

- changes/1916.misc.rst
- tox.ini
Running `tox -e py-cocoa` (or any other backend) is currently failing on local installs because the ordering of dependencies in the install leads to recent versions of pip trying to resolve the toga-core install from the toga-cocoa install, rather than using the explicit reference to toga-cocoa. 
Reordering the install order removes this problem.
> Tweak the ordering of tox installs to trick the pip resolver.

- .pre-commit-config.yaml
- changes/1917.misc.rst
Updated `pre-commit` hooks to their latest versions and ran updated hooks against the repo.
> Auto-update `pre-commit` hooks

- changes/1894.feature.rst
- examples/window/window/app.py
- winforms/src/toga_winforms/app.py
Added support for cursor visibility in WinForms for the existing APIs. As discussed, implementation was done under existing API and no new API was added. A shadow variable was needed as the calls to show and hide cursor needs to be balanced.
> Added support for cursor visibility in WinForms.

- android/src/toga_android/widgets/table.py
- changes/1879.bugfix.rst
- changes/1913.feature.rst
- cocoa/src/toga_cocoa/widgets/tree.py
- core/src/toga/widgets/tree.py
- examples/table/table/app.py
- examples/tree/tree/app.py
- gtk/src/toga_gtk/widgets/internal/sourcetreemodel.py
- gtk/src/toga_gtk/widgets/tree.py
For linux, I passed the missing_value from self.interface.missing_value from Tree to the sourcetreemodel. I did this because self.instance is not available inside the sourcetreemodel but the value is needed to be able to solve the bug.
For android, I simply added the self.interface.missing_value as the default option for the getattr.
On android the app will crash if values are not provided for all headings, on linux it will cause an error in the logs. 
Fixes #1879
> Fixed bug related to missing_value for android and linux

- .github/workflows/publish.yml
- .github/workflows/release.yml
- changes/1900.misc.rst
Adds the `id-token: write` permission to the publishing workflow to take advantage of trusted publishers.
Related to: https://github.com/beeware/beeware/issues/219
> Use trusted publisher for publishing workflow

- attic/django/setup.py
- attic/falcon/setup.py
- attic/flask/setup.py
- attic/pyramid/setup.py
- attic/starlette/setup.py
- attic/tornado/setup.py
- attic/win32/setup.py
- changes/1926.misc.rst
Dependabot has been raising alerts for Django and Flask versions. These projects are in the attic, so there's no actual security risk. Removing the version pins allows us to keeps the code around without triggering security alerts.
> Unpin versions in attic projects to avoid dependabot alerts.

- android/src/toga_android/widgets/selection.py
- changes/1723.bugfix.rst
- cocoa/src/toga_cocoa/widgets/selection.py
- examples/selection/selection/app.py
- iOS/src/toga_iOS/widgets/selection.py
Added an if statement for get_selected_item that checks if the Selection has values or not. If it does not it will return None which is consistent with linux and windows. If it has values, it will return "" with type str if an empty value is selected. 
Makes the return value consistent across platforms
Fixes #1723
> Bug fix for toga.Selection on android for value

- changes/1920.bugfix.rst
- gtk/src/toga_gtk/widgets/detailedlist.py
GTK's DetailedList widget wasn't providing a size hint; as a result, it was collapsing to size 0 when placed inside a box.
Fixes #1920.
> Correct size hinting on GTK DetailedList.

- changes/1921.bugfix.rst
- gtk/src/toga_gtk/libs/gtk.py
Added an if statement to check if Gdk has a display which will return None if $DISPLAY is not set. If it is None, it will exit and display the reason.
Makes it clear as to why the application is not running.
#1715
> Improves segfault error crash handling on systems without a DISPLAY variable.

- android/src/toga_android/app.py
- changes/1909.bugfix.rst
Removed if statement that called resolveActivity and replaced with a try block that excepts an Attribute Error. Ideally this would be an ActivityNotFoundException however rubicon does not have JavaExceptions to my knowledge so I couldn't set that as the except.
Fixes an issue that caused valid intents like ACTION_OPEN_DOCUMENT to return as not found when it does exist. After android 11, package visibility changed and shown in [this link](https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9). It suggests doing the try catch instead of the resolveActivity.
Fixes #1909
> Improve error handling when Android raises an ActivityNotFoundException

- android/src/toga_android/dialogs.py
- changes/1948.misc.rst
- cocoa/src/toga_cocoa/dialogs.py
- core/src/toga/handlers.py
- core/src/toga/window.py
- dummy/src/toga_dummy/dialogs.py
- examples/dialogs/dialogs/app.py
- gtk/src/toga_gtk/dialogs.py
- iOS/src/toga_iOS/dialogs.py
- web/src/toga_web/dialogs.py
- winforms/src/toga_winforms/dialogs.py
In the process of auditing WebView, I noticed an opportunity for code reuse in Dialog.
This refactors the Dialogs implementation so that:
1. There's a clear interface/impl separation for dialog objects
2. There's a full `interface`/`_impl`/`native` chain. This should make dialog testing simpler (hopefully?)
3. The asynchronous result capability is factored out as a base class that can be re-used
Testing regimen for this is the `dialogs` example.
> Refactor dialog implementation

- changes/1952.misc.rst
- core/src/toga/widgets/activityindicator.py
- core/src/toga/widgets/base.py
- core/src/toga/widgets/box.py
- core/src/toga/widgets/button.py
- core/src/toga/widgets/divider.py
- core/src/toga/widgets/label.py
- core/src/toga/widgets/multilinetextinput.py
- core/src/toga/widgets/progressbar.py
- core/src/toga/widgets/slider.py
- core/src/toga/widgets/switch.py
At some point during the audit, we decided to introduce type annotations as part of documentation. 
This PR retrospectively applies type annotations (including adding `from __future__ import annotations` so we can benefit from the most recent set of typing conventions).
> Update type annotations for audited widgets.

- changes/1963.misc.rst
- iOS/src/toga_iOS/widgets/multilinetextinput.py
After the merge of #1946, we've been seeing intermittent failures on two iOS tests:
* tests/widgets/test_multilinetextinput.py::test_focus
* tests/widgets/test_multilinetextinput.py::test_placeholder_focus
The errors are both caused when the widget being tested *loses* focus as a result of another widget being explicitly given focus. In CI conditions, the widget *doesn't* lose focus as a result of call to give the other widget focus. 
I haven't been able to reproduce this problem locally; however, via #1960 I have been able to rule out it being an issue of the event loop not catching up - a longer wait after the focus call doesn't make the test pass; this indicates that the widget is refusing to give up focus.
The willingness of a UITextView widget to give up focus is controlled by its …
> Correct iOS delegate method prototype

- .pre-commit-config.yaml
- changes/1977.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.4.0 to v3.6.0. and ran the update against the repo.
> Bump pyupgrade from v3.4.0 to v3.6.0.

- changes/1988.misc.rst
- examples/tutorial0/pyproject.toml
- web/src/toga_web/paths.py
In the recent updates to app paths, the web paths weren't fully tested. The web backend tries to instantiate an instance of Paths (which is no longer required); but the instantiation doesn't provide the necessary arguments, so it fails.
> Remove a stray instantiation in the web paths

- android/src/toga_android/factory.py
- changes/1992.feature.rst
- cocoa/src/toga_cocoa/factory.py
- gtk/src/toga_gtk/factory.py
- iOS/src/toga_iOS/factory.py
- web/src/toga_web/factory.py
- winforms/src/toga_winforms/factory.py
When a platform doesn't support a widget, the user currently gets an error of the form:
```
...
File ".../toga/widgets/datepicker.py", line 43, in __init__
self._impl = self.factory.DatePicker(interface=self)
AttributeError: module 'toga_gtk.factory' has no attribute 'DatePicker'
```
This has been the source of regular confusion in support channels, as this isn't a clear indication that a widget isn't supported. 
This PR adds a PEP562 handler for the platform factories so that a missing widget in a factory is now reported as:
```
...
File ".../toga_gtk/factory.py", line 83, in __getattr__
raise NotImplementedError(f"Toga's GTK backend doesn't implement {name}")
NotImplementedError: Toga's GTK backend doesn't implement …
```
> Improve error message when a platform doesn't support a widget.

- changes/1998.misc.rst
- docs/reference/data/widgets_by_platform.csv
I couldn't tell if an existing PR has already fixed this; please just close if so.
> Fix docs reference to `toga.paths.Paths`

- changes/1989.misc.rst
- gtk/src/toga_gtk/widgets/webview.py
- testbed/tests/widgets/test_webview.py
Via a report from @rmartin16 
Tutorial3 was crashing on GTK because the WebView widget was being created with no URL. This caused a URL of None to be set, which immediately triggered the on_webview_load handler. However, the widget hadn't completed construction, so the app hadn't assigned `self.webview` yet, and the handler crashed.
This problem didn't manifest in the testbed because the on_webview_load wasn't being set in the constructor. Even if it was, it wouldn't have caused a crash because the testbed event handler is a mock.
This PR puts the load notification event on the event queue. This means it will still trigger almost immediately, but it's guaranteed to occur *after* the widget has completed construction (because control must have been given back to the event loop).
This also …
> Defer on-load event when clearing the URL on GTK.

- changes/2008.misc.rst
- web/src/toga_web/libs.py
- Pyodide removed most names from the root module with the 0.23.0 release. They must be accessed from their respective submodules.
Please close if already resolved with an open PR.
> Fix `pyodide.create_proxy` usage with `pyodide.ffi.create_proxy`

- .pre-commit-config.yaml
- changes/2014.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.6.0 to v3.7.0. and ran the update against the repo.
> Bump pyupgrade from v3.6.0 to v3.7.0.

- android/src/toga_android/app.py
- changes/2018.feature.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/src/toga_cocoa/libs/appkit.py
- core/src/toga/app.py
- core/tests/test_app.py
- dummy/src/toga_dummy/app.py
- gtk/src/toga_gtk/app.py
- iOS/src/toga_iOS/app.py
- web/src/toga_web/app.py
- winforms/src/toga_winforms/app.py
- winforms/src/toga_winforms/libs/__init__.py
- winforms/src/toga_winforms/libs/winforms.py
`app.beep()` is a new method that will play the default system notification sound.
Only tested for macOS
- https://developer.apple.com/documentation/appkit/1473622-nsbeep
- https://docs.gtk.org/gdk3/func.beep.html
- https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/how-to-play-a-beep-from-a-windows-form
> Added app.beep() to play the default system notification sound.

- .readthedocs.yaml
- changes/2019.misc.rst
- See details in https://github.com/beeware/briefcase/issues/1339
RTD build for this PR: https://readthedocs.org/projects/toga/builds/21175753/
>  Ensure repo checkout is unshallow in RTD builds for SCM versioning

- .pre-commit-config.yaml
- changes/2022.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.7.0 to v3.8.0. and ran the update against the repo.
> Bump pyupgrade from v3.7.0 to v3.8.0.

- .github/workflows/ci.yml
- changes/2021.doc.rst
- docs/how-to/contribute-code.rst
- docs/how-to/contribute-docs.rst
- docs/tutorial/tutorial-0.rst
- gtk/README.rst
- testbed/pyproject.toml
- Follow on work from beeware/beeware#231
- Stops installing Python packages for `PyGObject` and `cairo` from Debian repos
- This includes `python3-gi`, `python3-gi-cairo`, etc
- When `PyGObject` is installed from PyPI, it brings along all the Python stuff it needs
- This also aligns Toga's install instructions with PYGobject's install [instructions](https://pygobject.readthedocs.io/en/latest/getting_started.html).
- Stops installing `libpango1.0-dev` since these headers are not needed for anything
- `libpango` will be installed as a dependency of `libgtk-3-0`
> Refine Linux dependencies for developing and using Toga

- .pre-commit-config.yaml
- changes/2028.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.8.0 to v3.9.0. and ran the update against the repo.
> Bump pyupgrade from v3.8.0 to v3.9.0.

- .pre-commit-config.yaml
- changes/2034.misc.rst
Bumps `pre-commit` hook for `black` from 23.3.0 to 23.7.0. and ran the update against the repo.
> Bump black from 23.3.0 to 23.7.0.

- changes/2039.misc.rst
- iOS/src/toga_iOS/dialogs.py
in `/iOS/src/toga_iOS/dialogs.py`
```
-        interface.window._impl.controller.presentViewController(
+        interface.window._impl.native.rootViewController.presentViewController(
```
Fixing a bug introduced in #1969 that clashes the dialog display on iOS
fix #2039
> Fixing dialog clashing on iOS bug (#2039)

- android/src/toga_android/app.py
- changes/2047.feature.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- core/tests/test_app.py
- dummy/src/toga_dummy/app.py
- gtk/src/toga_gtk/app.py
- iOS/src/toga_iOS/app.py
- web/src/toga_web/app.py
- winforms/src/toga_winforms/app.py
(EuroPython sprints)
Fixes #760 
Typically users will override the `App.startup()` method with one of their own. For most backends, this method must create a `MainWindow`. This PR refactors the call to `startup` so that after the call, a new `_verify_startup()` private method will be called which, for all the GUI backends, will enforce the condition. For `DocumentApp` app the verification is empty. 
Additionally, the "dummy" test backend was not properly chaining calls so `main_loop` calls `create` which calls `startup`. This was changed too to make the new feature testable.
> test, fix invalid user-provided startup() method

- android/src/toga_android/app.py
- changes/1235.bugfix.rst
- iOS/src/toga_iOS/app.py
Add hide_cursor() and show_cursor() to App in toga_android and toga_iOS. Android and iOS apps don't crash anymore if you call these functions.
Fixes #1235 partly.
> Fix 1235 partly

- changes/2052.misc.rst
- testbed/pyproject.toml
https://gitlab.gnome.org/GNOME/pygobject/-/issues/119 has finally been resolved; however, as a result, the git branch we were using to obtain a patched version has now been deleted. This updates the version pin in testbed. 
Once the next release of pygobject is made, we can pin a formal release number, rather than a git repo hash.
> Alter the version pin for pygobject in testbed.

- changes/2051.feature.rst
- docs/reference/data/widgets_by_platform.csv
- web/src/toga_web/factory.py
- web/src/toga_web/widgets/divider.py
Prior to this change, the web implementation of divider widget was only implemented as a dummy widget.
This change adds basic implementation of the divider widget and adds it into web factories.
> Add a web widget for divider

- changes/2050.feature.rst
- core/src/toga/style/pack.py
- core/tests/style/pack/test_css.py
- docs/reference/data/widgets_by_platform.csv
- docs/reference/style/pack.rst
- web/src/toga_web/factory.py
- web/src/toga_web/widgets/activityindicator.py
> Add a web widget for the activity indicator (shoelace spinner)

- changes/2044.feature.rst
- core/setup.cfg
- core/src/toga/app.py
- core/src/toga/fonts.py
- core/src/toga/handlers.py
- core/src/toga/icons.py
- core/src/toga/sources/accessors.py
- core/src/toga/sources/base.py
- core/src/toga/validators.py
- core/src/toga/widgets/activityindicator.py
- core/src/toga/widgets/base.py
- core/src/toga/widgets/box.py
- core/src/toga/widgets/button.py
- core/src/toga/widgets/canvas.py
- core/src/toga/widgets/slider.py
- core/src/toga/window.py
- docs/conf.py
- docs/reference/api/app.rst
- docs/reference/api/widgets/button.rst
- docs/reference/api/window.rst
- [diff](https://github.com/beeware/toga/pull/2044/files/1f2193243b9b95fcc310a3d6dca9219135861da0) Unify how App/Window/Widget IDs are created and documented, and ensures that the ID is always a string.
- [diff](https://github.com/beeware/toga/pull/2044/files/1f2193243b9b95fcc310a3d6dca9219135861da0..HEAD) Add type annotations to user-facing classes
- Refs #2042 by adding `typing.Protocol`s for callback functions
- Fix a few typos (a/an, missing comma, ...)
> Add type annotations, minor cleanups

- changes/2053.misc.rst
- cocoa/src/toga_cocoa/widgets/splitcontainer.py
A late change to #1984 added checks for split containers managing non-content. This test *passed* on Cocoa, but was raising a warning because the event handler was crashing. 
This PR adds protection against that edge case. No extra test or coverage is required, as the branch was being implicitly hit previously, but was raising a warning as a result.
> Cleanup a test warning on cocoa

- .pre-commit-config.yaml
- changes/2056.misc.rst
Bumps `pre-commit` hook for `flake8` from 6.0.0 to 6.1.0. and ran the update against the repo.
> Bump flake8 from 6.0.0 to 6.1.0.

- .pre-commit-config.yaml
- changes/1956.removal.rst
- changes/2057.misc.rst
- cocoa/src/toga_cocoa/constraints.py
- cocoa/src/toga_cocoa/container.py
- core/src/toga/widgets/canvas.py
- core/src/toga/widgets/numberinput.py
- core/src/toga/widgets/slider.py
- core/tests/sources/test_list_source.py
- core/tests/style/pack/layout/test_fixed.py
- core/tests/style/pack/layout/test_flex.py
- core/tests/test_paths.py
- core/tests/widgets/test_canvas.py
- core/tests/widgets/test_multilinetextinput.py
- core/tests/widgets/test_slider.py
- core/tests/widgets/test_webview.py
- examples/beeliza/beeliza/bot.py
- examples/dialogs/dialogs/app.py
- gtk/src/toga_gtk/container.py
- gtk/src/toga_gtk/widgets/multilinetextinput.py
- gtk/src/toga_gtk/widgets/table.py
- gtk/src/toga_gtk/widgets/tree.py
- iOS/src/toga_iOS/constraints.py
- iOS/src/toga_iOS/container.py
- pyproject.toml
- testbed/tests/widgets/test_label.py
- testbed/tests/widgets/test_selection.py
- testbed/tests/widgets/test_webview.py
- toga/README.rst
- web/src/toga_web/app.py
Adds codespell as a pre-commit configuration, and fixes a bunch of errors that are found in the process.
> Add codespell configuration.

- .pre-commit-config.yaml
- changes/2067.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.9.0 to v3.10.1. and ran the update against the repo.
> Bump pyupgrade from v3.9.0 to v3.10.1.

- changes/2085.bugfix.rst
- changes/2085.misc.rst
- gtk/src/toga_gtk/widgets/webview.py
Replace `run_javascript()` with `evaluate_javascript()` in `toga_gtk.WebView`.
Fixes #2085.
> Replace deprecated WebView API usage to evaluate javascript on Gtk

- changes/2089.feature.rst
- examples/passwordinput/README.rst
- examples/passwordinput/passwordinput/__init__.py
- examples/passwordinput/passwordinput/__main__.py
- examples/passwordinput/passwordinput/app.py
- examples/passwordinput/passwordinput/resources/README
- examples/passwordinput/pyproject.toml
- web/src/toga_web/factory.py
- web/src/toga_web/widgets/passwordinput.py
This PR implements a password input web backend component using Shoelace and allows the `sl-change` event to trigger validation.
See screenshot for the component in action.
Steps to test:
- `cd examples\passwordinput`
- `briefcase run web`
> Feat web password

- changes/2094.bugfix.rst
- winforms/src/toga_winforms/window.py
Modified the `WinForms` backend to enable correct behavior of `toga.Window.title`.
Prevents the error:`TypeError: 'str' object is not callable` when `toga.Window.title` is invoked on WinForms.
> Corrected `toga.Window.title` backend for winforms

- changes/2095.bugfix.rst
- core/src/toga/window.py
- winforms/src/toga_winforms/window.py
Modified WinForms backend to prevent error when window content is not set.
Prevents non meaningful error messages like the following from showing up:
```
...
File "...\winforms\src\toga_winforms\window.py", line 124, in show
self.interface.content.refresh()
AttributeError: 'NoneType' object has no attribute 'refresh'
```
> Modified WinForms backend to prevent error when window content is not set.

- changes/2092.misc.rst
- examples/dialogs/dialogs/app.py
- textual/src/toga_textual/app.py
- textual/src/toga_textual/dialogs.py
- textual/src/toga_textual/factory.py
- textual/src/toga_textual/widgets/base.py
- textual/src/toga_textual/widgets/label.py
- textual/src/toga_textual/window.py
Add Info, Question, Confirm, Error, and Stack Trace dialogs for Textual.
Also corrects the 24/25 line aspect ratio calculation identified in [this comment](https://github.com/beeware/toga/pull/2065#discussion_r1299275168)
> Add textual dialogs

- .pre-commit-config.yaml
- changes/2115.misc.rst
Bumps `pre-commit` hook for `black` from 23.7.0 to 23.9.0. and ran the update against the repo.
> Bump black from 23.7.0 to 23.9.0.

- changes/2116.bugfix.rst
- changes/2116.misc.rst
- gtk/src/toga_gtk/app.py
Fixed a pixbuf bug present in gtk icons. Prevents the error:
```
AttributeError: 'Pixbuf' object has no attribute 'get_pixbuf'
```
With this bug, it would be impossible to show the about dialog on gtk.
> Fixed pixbuf bug in gtk icons.

- android/tests_backend/widgets/imageview.py
- changes/2119.misc.rst
- cocoa/tests_backend/widgets/imageview.py
- gtk/src/toga_gtk/widgets/imageview.py
- gtk/tests_backend/widgets/imageview.py
- iOS/tests_backend/widgets/imageview.py
- testbed/tests/widgets/test_imageview.py
- winforms/tests_backend/widgets/imageview.py
In the process of checking box/child handling #1903 I ran the entire test suite, and noticed a regression in behaviour that the testbed suite wasn't picking up.
The imageview tests validate the size of the ImageView itself, and validate the aspect ratio handling of the image view, but doesn't validate the size of the actual image itself.
On every backend *other* than GTK, this doesn't matter, because the ImageView is responsible for scaling the underling image. The size of the widget and the scaling behaviour is all that needs to be validated.
However, on GTK, it's the responsibility of the user to scale the pixbuf being rendered by the ImageView to the appropriate size, performing any aspect ratio change etc. This worked when #1956 landed; but somewhere along the way, we've made a subtle …
> Correct image scaling on GTK

- .pre-commit-config.yaml
- changes/2123.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.10.1 to v3.11.0. and ran the update against the repo.
> Bump pyupgrade from v3.10.1 to v3.11.0.

- .pre-commit-config.yaml
- changes/2124.misc.rst
Bumps `pre-commit` hook for `black` from 23.9.0 to 23.9.1. and ran the update against the repo.
> Bump black from 23.9.0 to 23.9.1.

- changes/2128.misc.rst
- docs/conf.py
- The footer in the docs no longer include a copyright year
- IIUC, this was the desired outcome from beeware/briefcase#1431
> Remove copyright year from docs (re: beeware/briefcase#1431)

- changes/2127.misc.rst
- cocoa/src/toga_cocoa/widgets/webview.py
- iOS/src/toga_iOS/widgets/webview.py
[UIDelegate](https://developer.apple.com/documentation/webkit/wkwebview/1415009-uidelegate?language=objc) was misspelled.
> typo on UIDelegate

- .pre-commit-config.yaml
- changes/2131.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.11.0 to v3.13.0. and ran the update against the repo.
> Bump pyupgrade from v3.11.0 to v3.13.0.

- .pre-commit-config.yaml
- changes/2147.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.13.0 to v3.15.0. and ran the update against the repo.
> Bump pyupgrade from v3.13.0 to v3.15.0.

- .pre-commit-config.yaml
- changes/2146.misc.rst
Bumps `pre-commit` hook for `pre-commit-hooks` from v4.4.0 to v4.5.0. and ran the update against the repo.
> Bump pre-commit-hooks from v4.4.0 to v4.5.0.

- android/tests_backend/widgets/base.py
- android/tests_backend/widgets/numberinput.py
- android/tests_backend/widgets/textinput.py
- changes/2151.feature.rst
- cocoa/src/toga_cocoa/widgets/multilinetextinput.py
- cocoa/tests_backend/widgets/base.py
- cocoa/tests_backend/widgets/multilinetextinput.py
- cocoa/tests_backend/widgets/numberinput.py
- cocoa/tests_backend/widgets/textinput.py
- gtk/tests_backend/widgets/base.py
- gtk/tests_backend/widgets/multilinetextinput.py
- gtk/tests_backend/widgets/numberinput.py
- gtk/tests_backend/widgets/textinput.py
- iOS/tests_backend/widgets/base.py
- iOS/tests_backend/widgets/numberinput.py
- iOS/tests_backend/widgets/textinput.py
- testbed/tests/widgets/test_multilinetextinput.py
- testbed/tests/widgets/test_numberinput.py
- testbed/tests/widgets/test_passwordinput.py
- testbed/tests/widgets/test_textinput.py
- winforms/tests_backend/widgets/base.py
- winforms/tests_backend/widgets/numberinput.py
- winforms/tests_backend/widgets/textinput.py
Widgets tested are:
- TextInput
- MultilineTextInput
- PasswordInput
- NumberInput
The cocoa MultilineTextInput widget has been updated to enable undo.
Replaces PR https://github.com/beeware/toga/pull/2037
> Test undo/redo behaviour of text input widgets on macOS.

- .pre-commit-config.yaml
- changes/2165.misc.rst
Bumps `pre-commit` hook for `black` from 23.9.1 to 23.10.0. and ran the update against the repo.
> Bump black from 23.9.1 to 23.10.0.

- changes/2161.bugfix.rst
- iOS/src/toga_iOS/container.py
- iOS/src/toga_iOS/libs/uikit.py
This sets the [autoResizingMask](https://developer.apple.com/documentation/uikit/uiview/1622559-autoresizingmask?language=objc) property of the container.native UIView so that all possible resizing options (i.e. margin, height, and width) are set.
On iOS14 and iOS15 the container.native UIView doesn't always resize properly on orientation change.  This is not a problem on iOS16 and iOS17 for some reason.  You can see this behavior on the positron-django example.
> Make container automatically resize on orientation change

- changes/2163.misc.rst
- winforms/src/toga_winforms/app.py
- winforms/src/toga_winforms/command.py
- winforms/src/toga_winforms/window.py
Fixes #2163.
The change to make event handlers weakrefs added in #2066 had the unintended side effect of breaking menu items, because `Command.as_handler()` was producing a transient callable that was being garbage collected immediately.
This PR modifies the handler to be a direct method on Command, so it isn't garbage collected.
> Ensure Winforms menu/toolbar handlers aren't garbage collected

- .pre-commit-config.yaml
- changes/2177.misc.rst
Bumps `pre-commit` hook for `black` from 23.10.0 to 23.10.1. and ran the update against the repo.
> Bump black from 23.10.0 to 23.10.1.

- changes/2180.misc.rst
- winforms/src/toga_winforms/window.py
Although modern versions of Windows only draw a 1-pixel border around windows, the invisible resize area surrounding it is still counted as part of `native.Size`. This was causing the window of tutorial4 to be too narrow to contain the image.
> WinForms: take borders and title bar into account when setting window size

- android/src/toga_android/widgets/progressbar.py
- android/src/toga_android/widgets/selection.py
- android/src/toga_android/widgets/slider.py
- changes/2200.feature.rst
- core/src/toga/widgets/scrollcontainer.py
- winforms/src/toga_winforms/widgets/selection.py
- winforms/src/toga_winforms/widgets/slider.py
Updates from the review of #2186.
The best kind of PR – one that only removes code. 😄
> Android and WinForms rehint updates

- changes/2204.misc.rst
- docs/reference/api/documentapp.rst
- docs/reference/api/mainwindow.rst
- docs/reference/api/widgets/multilinetextinput.rst
- docs/reference/api/widgets/selection.rst
- docs/reference/api/window.rst
- docs/reference/data/widgets_by_platform.csv
Doesn't matter how many times you look at something, you'll miss something.
Corrects some inconsistencies in markup for widget support.
Biggest change is marking Window as not supported on iOS, Android, Web and Textual. While the class exists and it's tested (on iOS and Android anyway), it only functionally exists in as much as there's a MainWindow, so it seemed like we should reflect that.
> Correct some discrepancies and inconsistencies in widget support docs.

- android/src/toga_android/app.py
- changes/2215.misc.rst
This PR moves the Android app command creation into the method _create_app_commands() like it is for the other platforms
> Android: moved app command creation to method _create_app_commands()

- changes/2216.misc.rst
- core/tests/widgets/test_slider.py
When I was working on the Canvas, I fixed a division by zero error in the Slider (https://github.com/beeware/toga/commit/142ec173c451a9247a1ee7fc249225208f9fec90). This PR adds some tests which would have caught that error.
> Add more tests for sliders with empty ranges

- changes/2214.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/tests_backend/app.py
The menu items used for Close and Close All follow the example of Safari, which is a bit of an oddity when compared to *most* other macOS apps. 
This PR changes the default macOS menu items to match the more common naming and shortcuts:
* "Close Window" (CMD-SHIFT-W) -> "Close" (CMD-W)
* "Close All Windows" (CMD-OPT-SHIFT-W) -> "Close" (CMD-OPT-W)
Fixes #2214.
> Improve macOS HIG compliance of Close and Close All menu items.

- changes/2219.bugfix.rst
- changes/2219.misc.rst
- docs/reference/api/widgets/webview.rst
- docs/reference/platforms/windows.rst
Updated the anchor `#download-section` in link `https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section` as it's invalid and causes the CI to fail.
> Updated invalid anchor section in webview download link in windows docs

- changes/2222.misc.rst
- cocoa/src/toga_cocoa/app.py
- gtk/src/toga_gtk/app.py
- web/src/toga_web/app.py
Changed the first non-`self` parameter name in Command handlers to `command`.
The `ActionHandler` protocol is defined as accepting `self, command: Command, **kwargs`, where `command` is the command that triggered the action. In the codebase, handlers were defined with this parameter named `app` and in one case `widget`. Especially since none of the defined handlers reference the argument, this is an entirely semantic fix with no runtime significance.
> Fixed argument name for Command handlers

- .pre-commit-config.yaml
- changes/2224.misc.rst
- core/setup.cfg
- Dependabot is seemingly unable to update dependencies if a directory contains both a `setup.cfg` and `setup.py`
- Currently the dependencies are about 9 months out of date....this brings them all to their latest version
> Update all development dependencies

- README.rst
- changes/2228.doc.rst
- changes/2228.removal.rst
- cocoa/src/toga_cocoa/libs/appkit.py
- docs/reference/platforms/macOS.rst
- docs/spelling_wordlist
Updated documentation to list minimum macOS version as 11 (Big Sur) rather than 10.10 (Yosemite). Also cleaned up places where Cocoa classes were commented out or conditionally defined due to lack of availability in older OS versions.
As mentioned [here](https://github.com/beeware/toga/pull/2227#discussion_r1390616671), Briefcase supports a minimum of 11 (Big Sur), so the documentation is misleading and the avoided / conditional Cocoa definitions are unnecessary.
Since [#2227](https://github.com/beeware/toga/pull/2227) is nowhere near as simple as I'd first thought,  I'm putting this in separately rather than wait for resolution on that.
...What category should this changenote be? Docs? It does change code, but doesn't actually fix a bug.
> Updated macOS minimum version to 11, matching Briefcase

- .github/workflows/ci.yml
- changes/2230.misc.rst
- Runs the Android testbed in Linux instead of macOS
- The emulator runs about 2x faster on Linux....at least now that GitHub has [sanctioned](https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/) access to KVM
- In preparing to add the ability to run the helloworld apps in `app-build-verify.yml`, I got this working and figured I share here...especially since Toga's CI has been serving as inspiration
- No worries if you've got other reasons to want to stay with macOS testing
> Run testbed for Android on Linux

- .github/workflows/ci.yml
- changes/2235.misc.rst
- Adds an app data path for testbed failures on Windows
- Demonstration: https://github.com/beeware/toga/actions/runs/6915247187
- I just excluded android instead of trying to figure out the right `adb` command...it's not even really clear to me how valuable this data is...
- Example of previous behavior: https://github.com/beeware/toga/actions/runs/6906873154/job/18792969335
> Specify app user data path for testbed on Windows

- android/src/toga_android/app.py
- changes/2193.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/src/toga_cocoa/window.py
- cocoa/tests_backend/window.py
- core/src/toga/command.py
- core/tests/command/conftest.py
- core/tests/command/test_command.py
- core/tests/command/test_commandset.py
- gtk/src/toga_gtk/app.py
- gtk/src/toga_gtk/window.py
- winforms/src/toga_winforms/app.py
- winforms/src/toga_winforms/window.py
Reworks the handling of separators in command groups.
Previously, the process of iterating over commands yielded both Group and Section breaks. This modifies the handling to *only* yield section breaks; the group for a command can be determined by lookup on the group for any given command. However, it now yields section breaks that are caused when a *sub group* is in a new section.
Fixes #2193.
> Correct handling of separators.

- .github/workflows/ci.yml
- changes/2240.misc.rst
- When Briefcase moved to "pyproject only", it now requires a newer pip to build and install it
- So, upgrade pip before installing Briefcase directly from GitHub
> Upgrade pip before installing Briefcase from GitHub

- android/tests_backend/icons.py
- changes/2246.misc.txt
- cocoa/src/toga_cocoa/paths.py
- cocoa/tests_backend/app.py
- cocoa/tests_backend/icons.py
- core/tests/test_fonts.py
- core/tests/test_icons.py
- core/tests/test_images.py
- core/tests/test_paths.py
- core/tests/widgets/test_imageview.py
- docs/reference/api/resources/images.rst
- examples/imageview/imageview/app.py
- examples/positron-static/src/positron/app.py
- gtk/src/toga_gtk/paths.py
- gtk/tests_backend/app.py
- gtk/tests_backend/icons.py
- iOS/tests_backend/icons.py
- testbed/tests/test_fonts.py
- testbed/tests/widgets/test_canvas.py
- textual/src/toga_textual/paths.py
- winforms/tests_backend/app.py
- winforms/tests_backend/icons.py
This might very well be a solution for a non-problem, but I noticed that a lot of paths in the codebase are written with all slash operators, like this:
```python
Path.home() / "does" / "not" / "exist" / "image.jpg"
Path("does") / "not" / "exist" / "image.jpg"
```
All this PR does is simplify all such instances , e.g.:
```python
Path.home() / "does/not/exist/image.jpg"
Path("does/not/exist/image.jpg")
```
This avoids creating and discarding intermediate Path objects along the way, and at least personally I find it more readable too.
In the event that this is an intentional style decision, I could submit a PR that instead changes all of the latter style to the former, for consistency.
> Simplified Path declarations

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- changes/2249.misc.rst
- core/pyproject.toml
- core/src/toga/__init__.py
- core/src/toga/platform.py
- core/tests/test_platform.py
- web/src/toga_web/libs.py
- For imports that are dependent on the version of Python, make that explicit and use a syntax that `pyupgrade` can automatically handle for Python EOLs
- Given that `pyupgrade` can change imports, run it before `isort` runs in pre-commit
- Installing `toml` package is no longer necessary to run `isort` in `pre-commit`
- Instead of assuming knowledge about `codespell`'s usage of TOML (such as the fact it uses the `tomli` package), instruct pre-commit to install the `toml` extra for `codespell`
> Clarify imports that are dependent on the version of Python

- android/src/toga_android/widgets/webview.py
- changes/2261.misc.rst
This PR adds the pinch-to-zoom feature in WebView for Android (see bug #2258)
The on-screen zoom controls are deactivated because they are deprecated.
It can be tested in the Android emulator with the webview example by pressing and holding the CTRL button and dragging the mouse.
> Added pinch-to-zoom in WebView on Android

- changes/2267.misc.rst
- textual/pyproject.toml
- textual/src/toga_textual/app.py
- textual/src/toga_textual/dialogs.py
- textual/src/toga_textual/widgets/button.py
- textual/src/toga_textual/widgets/textinput.py
- textual/src/toga_textual/window.py
Some of the changes made late in 0.3.X development weren't fully reflected in the Textual backend. This corrects those oversights.
* The App impl needs to explicitly set the reference to self on the interface
* Event handlers no longer need the initial "self" argument
* Textual now appears to use `title` as a protected attribute on modal screens. 
* The name change of the `multiselect` argument on file dialogs has been made.
> Correct issues with event handlers and app startup in Textual backend

- .pre-commit-config.yaml
- changes/2269.misc.rst
Bumps `pre-commit` hook for `isort` from 5.12.0 to 5.13.0 and ran the update against the repo.
> Bump isort from 5.12.0 to 5.13.0

- android/src/toga_android/dialogs.py
- android/src/toga_android/widgets/webview.py
- changes/2264.misc.rst
- changes/2264.removal.rst
- cocoa/src/toga_cocoa/dialogs.py
- cocoa/src/toga_cocoa/widgets/webview.py
- core/src/toga/handlers.py
- core/src/toga/widgets/webview.py
- core/src/toga/window.py
- core/tests/test_handlers.py
- core/tests/test_window.py
- core/tests/widgets/test_webview.py
- dummy/src/toga_dummy/dialogs.py
- dummy/src/toga_dummy/widgets/webview.py
- gtk/src/toga_gtk/dialogs.py
- gtk/src/toga_gtk/widgets/webview.py
- iOS/src/toga_iOS/dialogs.py
- iOS/src/toga_iOS/widgets/webview.py
- testbed/tests/test_window.py
- testbed/tests/testbed.py
- testbed/tests/widgets/test_webview.py
- textual/src/toga_textual/dialogs.py
- web/src/toga_web/dialogs.py
- winforms/src/toga_winforms/dialogs.py
- winforms/src/toga_winforms/widgets/webview.py
Another discovery in the process of developing a Camera API.
Toga has an internal AsyncResult handler that is used for methods that need to operate in an async context, but need to retain synchronous calling semantics. Whenever an AsyncResult is defined, there is an on_result lurking nearby; however, everywhere that this is done, the "handle async result, then handle on_result" logic is duplicated.
This PR merges the on_result handler into the AsyncResult, so that any time a result is reported, it is passed to both the synchronous and asynchronous contexts.
This also:
* moves one of the safety catches that was present in the Android backend - preventing a future result being set if the future has been cancelled - into the core API.
* Begins the process of deprecating `on_result` entirely; …
> Merge the handling of on_result and async result handling

- .pre-commit-config.yaml
- changes/2283.misc.rst
Bumps `pre-commit` hook for `isort` from 5.13.0 to 5.13.2 and ran the update against the repo.
> Bump isort from 5.13.0 to 5.13.2

- .pre-commit-config.yaml
- changes/2284.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 23.11.0 to 23.12.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 23.11.0 to 23.12.0

- changes/1156.bugfix.rst
- cocoa/src/toga_cocoa/widgets/table.py
- examples/table/table/app.py
- examples/tutorial2/tutorial/app.py
macOS TableViews would crash if you initiated a drag operation from within the table's extents. This PR explicitly disables drag operations, thereby preventing the crash.
Fixes #1156.
Explicitly disabling the drag operation.
> Prevent drag operations (and thus crash) on macOS TableView

- changes/2294.misc.rst
- demo/toga_demo/app.py
- web/src/toga_web/app.py
Some minor bugs picked up during pre-release testing.
* toga-demo uses the deprecated TOGA_ICON.
* toga-web wasn't updated to use the new Separator handling.
> Prerelease bugs

- .pre-commit-config.yaml
- changes/2298.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 23.12.0 to 23.12.1 and ran the update against the repo.
> Bump black-pre-commit-mirror from 23.12.0 to 23.12.1

- .github/workflows/ci.yml
- .github/workflows/release.yml
- changes/2318.misc.rst
- RE: https://github.com/beeware/.github/issues/77
- Bump `upload-artifact` and `download-artifact` actions to v4
- To accommodate v4:
- Artifacts must have unique names since multiple uploads cannot contribute to a single artifact
- Use a wildcard pattern to download all artifacts and merge in to a single directory
- 🚨 Dependent on https://github.com/beeware/.github/pull/78 🚨
> Upgrade `upload-artifact` and `download-artifact` actions to v4

- .pre-commit-config.yaml
- changes/2331.misc.rst
Bumps `pre-commit` hook for `flake8` from 6.1.0 to 7.0.0 and ran the update against the repo.
> Bump flake8 from 6.1.0 to 7.0.0

- changes/2302.misc.rst
- docs/background/project/releases.rst
Clarifies the backwards incompatible change to OptionList introduced in #2359.
Once merged, the notes attached to the 0.4.1 release should be updated to also include this text.
Fixes #2302.
> Update release note for recent OptionList changes

- changes/2336.misc.rst
- testbed/tests/testbed.py
This monkey patch was to prevent the "avc: denied" log spam from #1962. It's now been incorporated into Chaquopy 15, so it can be removed from the testbed after https://github.com/beeware/briefcase-android-gradle-template/pull/78 is merged.
> Remove Android get_terminal_size monkey patch

- android/src/toga_android/widgets/detailedlist.py
- changes/2338.bugfix.rst
Reported via beeware/briefcase#1600
The padding around DetailedList on Android is a little too generous. With the recent Icon Button changes converging on "48px" as the default size for an icon, allowing for 8px padding on each side, the row need only be 56px tall. The icon was previously 50px, with 10px padding - but the row was 80px tall, so there's effectively 30 px between icons.
Old  | New
<image src="https://github.com/beeware/toga/assets/37345/5ed0b138-8d61-450a-a5fb-c2b08e7ee331" width=300><image src="https://github.com/beeware/toga/assets/37345/a6d4524f-d654-41a3-8e15-65b427c8d279" width=300>
Functionally, it means an extra 2 rows can be displayed on a standard phone.
> Tighten the spacing on Android DetailedList.

- changes/2347.bugfix.rst
- changes/2348.doc.rst
- core/src/toga/images.py
- core/tests/test_images.py
- docs/reference/api/resources/icons.rst
- docs/reference/api/resources/images.rst
- docs/reference/api/widgets/imageview.rst
Modifies the constructor for Image to better handle the backwards compatibility path, and provide a less confusing type annotation.
Also takes the opportunity to introduce canonical documentation on the difference between Image and Icon. I'm very slightly softening on the idea of adding an `on_press` handler to ImageView (to support the "Image Gallery" use case); in the meantime, these admonitions explain the status quo. If we add `ImageView.on_press` in the future, the admonitions will need to be updated to say that you *can* make ImageView interactive, but if what you're looking for is a fancy button, please don't.
Fixes #2347.
> Documentation and API cleanups on Image

- changes/2211.bugfix.rst
- gtk/src/toga_gtk/app.py
`App.current_window` on Gtk now returns `None` when all windows are hidden.
Fixes #2211 
Tested on Arch
> Fixed `App.current_window` on Gtk

- changes/2374.bugfix.rst
- winforms/src/toga_winforms/widgets/textinput.py
Reported via @ethindp on Discord.
Pressing enter in a TextInput under Winforms generates a system beep. This is the default behaviour for an Enter keypress in  a TextInput; however, in Toga's case, it's undesirable. 
This PR marks the event as processed when Enter is pressed, so that the event doesn't propagate any further, preventing the beep.
I can't think of any reliable way to test this, as we can't monitor for the existence of a system beep, and we don't have visibility on the processing of system events.
It wasn't detected previously (at least, in my case) because the VM I use to test Windows didn't have a speaker connected, so I didn't hear system beeps.
> Ensure that winforms doesn't beep when confirming content.

- changes/2381.bugfix.rst
- changes/2381.docs.rst
- docs/reference/api/hardware/camera.rst
- iOS/src/toga_iOS/hardware/camera.py
See #2381 - where GC seems to collect self.native.delegate instantly.
Keep a reference to avoid GC until class destroyed.
- Fixes #2381
> Fix GC on iOS Camera

- changes/2396.misc.rst
- testbed/tests/conftest.py
- testbed/tests/test_fonts.py
- testbed/tests/test_icons.py
- testbed/tests/test_images.py
- testbed/tests/test_window.py
This is another kind-of-frivolous-but-why-not PR. Due to the magic of copy & paste, there are a few places where `getattr` is used even thought the attribute isn't dynamic or a reserved word / other syntax error. I've switched them to normal attribute access.
> Simplifying static getattr calls

- changes/2400.misc.rst
- docs/how-to/contribute-docs.rst
- tox.ini
- Adds support to run `sphinx-autobuild` from `tox`
- Running `tox -e docs-live` will incrementally build any detected changes within the `docs` directory
- Running `tox -e docs-live-src` will include rebuilding for changes to docstrings in the source that are compiled in to the documentation....but this requires a full rebuild of the docs for any changes since Sphinx doesn't have a mapping of source files to docs files.
> Run `sphinx-autobuild` via `tox -e docs-live[-src]`

- .pre-commit-config.yaml
- changes/2406.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.1.1 to 24.2.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.1.1 to 24.2.0

- .pre-commit-config.yaml
- changes/2405.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.0 to v3.15.1 and ran the update against the repo.
> Bump pyupgrade from v3.15.0 to v3.15.1

- changes/2413.doc.rst
- core/src/toga/app.py
- docs/reference/api/app.rst
> Add `toga.App.app` to docs

- changes/2153.misc.rst
- winforms/src/toga_winforms/libs/proactor.py
python/cpython#110773 added some additional internal methods to factor out the event loop setup and teardown portions of run_forever. This change was included in Python 3.13.0a2.
> Incorporate the new run_forever integrations from python/cpython#110773

- android/tests_backend/app.py
- changes/2418.bugfix.rst
- cocoa/tests_backend/app.py
- gtk/src/toga_gtk/app.py
- gtk/tests_backend/app.py
- iOS/tests_backend/app.py
- testbed/src/testbed/app.py
- testbed/tests/app/test_app.py
- winforms/tests_backend/app.py
Modifies the handling of sections in menus under GTK.
In the old code, the "current section" was tracked, and section/submenu breaks caused the creation of a new section. However. this caused problems when a menu contained a submenu followed by a regular item, as the "current section" would be the section of the submenu.
This modifies the approach so that a menu section is created at the same time as a menu, and stored in the cache as part of the group->submenu mapping. The current submenu and section is looked up on every item insertion, so when the item is added after the submenu is added, it finds the section that *was* active when the submenu was added, rather than the section active inside the submenu. When an explicit section break is added, the group cache is updated to reflect the …
> Correct handling of menu sections in GTK

- changes/2433.feature.rst
- core/src/toga/command.py
- core/tests/command/test_command.py
- docs/reference/api/resources/command.rst
I added a property handler for ``action``, so that it is possible to specify what a Command does after it's been created.
Sometimes, you want to make the action depend on the current state of your application, and having global variables to indicate that state may not always be possible.
With this change, you can change the action to be another closure. But, because the handler needs to be wrapped in a ``wrapped_handler``, doing this from you app looks ugly:
```
self.removepodcast.action = wrapped_handler(self.removepodcast.action, self.showRemovePodcast(main_list_box, podcast_id)
```
After this change, it looks like this:
```
self.removepodcast.action = self.showRemovePodcast(main_list_box, podcast_id)
```
> Implement property for Command.action.

- .pre-commit-config.yaml
- changes/2457.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.2.0 to 24.3.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.2.0 to 24.3.0

- .pre-commit-config.yaml
- changes/2464.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.1 to v3.15.2 and ran the update against the repo.
> Bump pyupgrade from v3.15.1 to v3.15.2

- changes/2472.bugfix.rst
- cocoa/src/toga_cocoa/icons.py
- cocoa/src/toga_cocoa/images.py
Fixes #2468 by explicitly releasing any successfully create NSImage on __del__.
> Fix memory leak for toga.Icon and toga.Image on Cocoa

- changes/2474.bugfix.rst
- winforms/src/toga_winforms/dialogs.py
Fixes #2474 
The mechanism used to display the stack trace dialog wasn't correctly invoking the `ShowDialog()` method; it should be a blocking method, but it was completing and returning. I can't completely work out why, but my guess is that it's related to `ShowDialog` being a bound method on a Python.net object, rather than pure Python function. Wrapping the Python.net method in a Python callable results in the dialog being shown as expected. 
Testbed didn't catch this because showing dialogs always involves a bit of an end-run around the dialog display process.
> Correct the display of the stack trace dialog on winforms

- .github/workflows/ci.yml
- changes/2476.misc.rst
actions/runner-images#9591 has identified a problem with Xcode 15 and/or the iOS 17 simulators running under Github Actions. Reverting to Xcode 14.3.1 and iOS 16.4 is a workaround for this problem.
Refs #2476.
> Revert iOS CI testing to use Xcode 14.3.1/iOS 16.4.

- .pre-commit-config.yaml
- changes/2487.misc.rst
Bumps `pre-commit` hook for `pre-commit-hooks` from v4.5.0 to v4.6.0 and ran the update against the repo.
> Bump pre-commit-hooks from v4.5.0 to v4.6.0

- changes/2498.misc.rst
- core/pyproject.toml
Freezegun 1.4.0 has an incompatibility with 3.13.0a6; the issue [has been fixed upstream](https://github.com/spulec/freezegun/commit/d75458f3f691d0c2c35559872716d0ebab738817), but it isn't in a format release yet.
> Use a pre-release freezegun on Python 3.13.

- .pre-commit-config.yaml
- changes/2503.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.3.0 to 24.4.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.3.0 to 24.4.0

- android/src/toga_android/libs/events.py
- changes/2479.bugfix.rst
The Android event loop integration uses a stub implementation for `run_in_executor` that effectively disables the ability to run blocking code in a thread. This override doesn't appear to be necessary any more; this PR removes the override, restoring the default executor behavior.
The previous implementation was marked no-cover, so deleting that code increases code coverage. I used the example code from #2479 to verify that the default implementation worked as expected.
Fixes #2479.
> Remove the customization of run_in_executor for Android.

- changes/2472.bugfix.rst
- changes/2482.bugfix.rst
- cocoa/src/toga_cocoa/widgets/detailedlist.py
- cocoa/src/toga_cocoa/widgets/table.py
- cocoa/src/toga_cocoa/widgets/tree.py
In the process of exploring beeware/rubicon-objc#256, I found a couple of over-enthusiastic memory retentions. These will be causing memory leaks over time.
> Remove some over-enthusiastic memory retention.

- android/README.rst
- android/pyproject.toml
- changes/2510.doc.rst
- cocoa/README.rst
- cocoa/pyproject.toml
- core/README.rst
- core/pyproject.toml
- demo/pyproject.toml
- dummy/README.rst
- dummy/pyproject.toml
- gtk/README.rst
- gtk/pyproject.toml
- iOS/README.rst
- iOS/pyproject.toml
- nursery/curses/pyproject.toml
- nursery/qt/pyproject.toml
- nursery/tvOS/pyproject.toml
- nursery/uwp/pyproject.toml
- nursery/watchOS/pyproject.toml
- textual/README.rst
- textual/pyproject.toml
- toga/README.rst
- toga/pyproject.toml
- web/README.rst
- web/pyproject.toml
- winforms/README.rst
- winforms/pyproject.toml
- The Documentation link is updated to the default landing page configured in RTD...which is currently `stable`
- Previously, this was `latest` but that seems strange given these links only really show up on PyPI...and the code on PyPI usually isn't the "latest"
- Add a new "Changelog" link on PyPI for Toga's release history
- I had previously mentioned linking to the GitHub release page to advertise new releases but it was said that PyPI is the official source of releases
- That makes sense to me but I've been a little bothered that the release history isn't prominently made available to users on PyPI; this resolves that with a dedicated link
- The name "Changelog" for the link probably has room for debate...
- Update RTD link in READMEs to `latest` instead of `stable`
- If you're …
> Update PyPI project links

- changes/2509.misc.rst
- gtk/tests_backend/widgets/mapview.py
- winforms/tests_backend/widgets/mapview.py
Fixes #2509 
Increases the delay when waiting for map rendering updates. 
The test case passes consistently when run in slow mode; when running in fast mode, there's an appreciable "stutter" in rendering, which, depending on exact testing conditions, can result in a test failure. Increasing the delay gives the web view a little more time to complete rendering, which seems to avoid the problem. 
Not sure why this suddenly started being a problem 2 days ago - my guess would be a change in how leaflet is deployed, but that's difficult to verify.
I've speculatively made the same change to the Winforms implementation, since it's using same underlying implementation.
> Increased the delay when waiting for map rendering updates.

- changes/2527.bugfix.rst
- gtk/src/toga_gtk/libs/gtk.py
- With Ubuntu Noble 24.04 dropping support for GTK WebKit2 4.0, Toga now supports detecting 4.1
- If 4.1 is not available, Toga falls back to the previous behavior of detecting 4.0
```pycon
>>> import gi
>>> gi.require_version("WebKit2", "4.0")
File "<stdin>", line 1, in <module>
File "/tmp/venv/lib/python3.12/site-packages/gi/__init__.py", line 125, in require_version
raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace WebKit2 not available for version 4.0
>>> gi.require_version("WebKit2", "4.1")
>>> 
```
- RE: https://github.com/beeware/toga/discussions/2528 (Thanks @eichin!)
- RE: https://github.com/beeware/beeware/issues/333
- RE: https://github.com/beeware/briefcase/pull/1748
> Use GTK WebKit2 4.1; else fallback to 4.0

- changes/2532.bugfix.rst
- changes/2532.misc.rst
- examples/optioncontainer/optioncontainer/app.py
Fixes the `OptionContainer` example app. 
Currently when the `OptionContainer` example app is run and `Commands`=>`Next Tab` is pressed, the following TypeError is raised:
```
File "D:\optioncontainer_example_fix\examples\optioncontainer\optioncontainer\app.py", line 72, in set_next_tab
self.optioncontainer.current_tab += 1
TypeError: unsupported operand type(s) for +=: 'OptionItem' and 'int'
Error in handler: unsupported operand type(s) for +=: 'OptionItem' and 'int'
```
This PR fixes the above error.
> Fixed `OptionContainer` example app

- .pre-commit-config.yaml
- changes/2542.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.4.0 to 24.4.2 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.4.0 to 24.4.2

- changes/2514.bugfix.rst
- core/src/toga/window.py
- core/tests/test_window.py
- core/tests/window/test_window.py
Fixes #2514 
Fixed widget IDs to be reusable after window closes. Also added a new test to check the behavior.
> Fixed widget IDs to be reusable after window closes

- .github/workflows/ci.yml
- changes/2544.doc.rst
- docs/reference/api/containers/optioncontainer.rst
- docs/reference/api/widgets/mapview.rst
- docs/reference/api/widgets/webview.rst
- docs/reference/platforms/unix-prerequisites.rst
- gtk/src/toga_gtk/libs/gtk.py
- gtk/src/toga_gtk/widgets/mapview.py
- gtk/src/toga_gtk/widgets/webview.py
Updates the unix pre-requisites to accomodate the WebKit2 package changes, primarily for the benefit of Ubuntu 24.04.
WebKit2 has been removed from the general Linux requirements list, in favor of a base set of packages plus an explicit list of system requirements on widgets that require it. The error message raised when those system requirements can't be found now explicitly references the system requirements in the docs (although the anchor on the link won't be valid until a stable release is cut). 
Fixes #2544.
> Update WebKit2 dependencies

- changes/2546.misc.rst
- core/src/toga/platform.py
`get_platform_factory` currently requires the entry_points metadata to be installed, even when it's unnecessary because the backend is set manually using TOGA_BACKEND environment variable. This makes it impossible to run from source code which hasn't been installed with pip, which is something I often do to speed up Android development – avoiding re-running pip for every change by listing toga-android in pyproject.toml under `source` rather than `requires`. 
This is a minor rearrangement to make sure we check the entry_points only when necessary.
> Allow running without entry_points metadata

- changes/2549.doc.rst
- docs/how-to/contribute/code.rst
- docs/how-to/contribute/docs.rst
- docs/reference/api/widgets/mapview.rst
- docs/reference/api/widgets/webview.rst
- docs/reference/platforms/linux.rst
- docs/reference/platforms/unix-prerequisites.rst
- Add _all_ requirements for each distro
- `gcc` since it's a requirement to build `PyGObject`
- `git` since `pip` is going to need it....at a minimum
- `gtk3`....most distros are already going to have this installed but useful to explicitly list it for docker images
- `cmake` for FreeBSD since it needs to build `ninja` as PyPI doesn't have a FreeBSD wheel
- Add requirements for OpenSUSE Tumbleweed
- Drop documentation for Ubuntu 18.04 since it is no longer supported by recent versions of PyGObject
- 18.04 doesn't work: `Dependency gobject-introspection-1.0 found: NO found 1.56.1 but need: '>= 1.64.0'`
- If we agree, I should probably update the BeeWare Tutorial as well
> Update/clarify Linux system requirements

- changes/2558.bugfix.rst
- cocoa/src/toga_cocoa/icons.py
- core/src/toga/icons.py
- core/tests/test_icons.py
- docs/reference/api/resources/icons.rst
- dummy/src/toga_dummy/icons.py
If the macOS backend can't find the icon file, it is currently raised as a ValueError. This should be a FileNotFound error, so that fallback logic is activated.
It also modifies the icon lookup logic to ask specifically for a `.icns` resource, rather than relying on CFBundleIconFile to provide the extension.
Fixes #2558.
> Correct the fallback handling when an icon cannot be loaded.

- .github/workflows/publish.yml
- .github/workflows/release.yml
The release of v0.4.3 required 2 passes, because the use of a pre-release freezegun version wasn't picked up as a problem until the toga-core package was pushed to PyPI. However, by this point, toga-android had been successfully published.
As a result of this, any attempt to re-publish toga-android will fail, because the wheel already exists; but there's no way to make any other 0.4.3 artefact complete upload. 
This PR modifies the matrix tasks to *not* fail fast, and continue on error; this would allow a recovery from the 0.4.3 test release.
> Make releases resilient to failures.

- README.rst
- changes/2566.doc.rst
- docs/reference/platforms/linux.rst
- Yet more updates to Linux requirements....specifically that Ubuntu 20.04+ and Fedora 32+ is required
- The requirements for Toga on Linux are more complex now than GTK>=3.22
- The primary driver of Toga's base requirements for Linux is the oldest supported version of PyGObject: 3.46.0
- PyGObject 3.46.0 [requires](https://gitlab.gnome.org/GNOME/pygobject/-/blob/3.46.0/meson.build?ref_type=tags):
- glib >= 2.64.0
- GObject Introspection >= 1.64.0
- pycairo >=1.16.0
- pycairo 1.17.0 (i.e. Toga's minimum version) [requires](https://github.com/pygobject/pycairo/blob/v1.17.0/setup.py) cairo >= 1.13.1
- but more recent pycairo 1.26.0 [requires](https://github.com/pygobject/pycairo/blob/main/meson.build) cairo >= 1.15.10
- While experimenting with different distro releases, I hit issues for …
> Update README's supported Ubuntu/Fedora versions

- changes/2565.doc.rst
- docs/how-to/contribute/code.rst
The original text:
* had a very roundabout way to explain what the filename for the file in the `changes/` directory should look like.
* relied upon `towncrier`s doc to explain fragment types.
In my view this made first/drive by PRs more difficult to properly do, so I expanded the text a little so it's more explicit.
> Rewrite paragraphs about `towncrier`.

- android/tests_backend/window.py
- changes/2446.bugfix.rst
- cocoa/tests_backend/window.py
- gtk/src/toga_gtk/dialogs.py
- gtk/tests_backend/window.py
- iOS/tests_backend/window.py
- testbed/tests/test_window.py
- winforms/tests_backend/window.py
In Gtk it's necessary to explicitly make dialog boxes modal. Do this & add a test.
This was also manually tested at PyConUS 2024 on Debian.
Closes #2446
> tests: Add a test that a dialog is modal

- .github/workflows/ci.yml
- changes/2583.bugfix.rst
- testbed/tests/widgets/test_button.py
(Not sure if this needs documented?)
> Fixed test suite 'widgets/test_buttons.py' in Fedora 40, one pixel off

- README.rst
- changes/2588.doc.rst
- core/README.rst
The link for first-time contributors in the repo README is updated
> Update contribution link in README

- changes/2301.feature.rst
- core/src/toga/widgets/base.py
- core/tests/widgets/test_base.py
Added ``replace`` and ``index`` methods to base widget class and minimal test cases.
Added another test case to verify the functionality of children access/assignment via square bracket notation ``__setitem__``/ ``__getitem__``.
This allows users to replace a child widget with another with a single method, instead of needing to remove the old one, keep track of the index, and insert a new one.
Fixes #2301
> Add API to replace children #2301

- changes/2593.doc.rst
- changes/2593.misc.rst
- docs/tutorial/tutorial-0.rst
added instructions to make the helloworld file within the directory of the project
resolves potential confusion
> added clarifying language for file creation instructions

- .pre-commit-config.yaml
- changes/2602.misc.rst
- gtk/src/toga_gtk/widgets/multilinetextinput.py
- gtk/tests_backend/widgets/base.py
- pyproject.toml
- testbed/tests/widgets/test_webview.py
Bumps `pre-commit` hook for `codespell` from v2.2.6 to v2.3.0 and ran the update against the repo.
> Bump codespell from v2.2.6 to v2.3.0

- changes/2605.misc.rst
- docs/reference/api/resources/command.rst
Probably something was left behind after the change
> Change Command attribute to `text` instead label

- changes/2307.feature.rst
- core/src/toga/app.py
- core/src/toga/window.py
- core/tests/test_window.py
- testbed/tests/test_window.py
* Fixes #2307 
This change allows for initializing a window with content, rather than setting it after the window has been created.
```python
main_box = toga.Box()
main_window = toga.MainWindow(title="Window title!")
main_window.content = main_box
main_window = toga.MainWindow(
title="Window title!",
content=main_box
)
```
> Set Content When Initializing Window

- .github/workflows/ci.yml
- .github/workflows/release.yml
- changes/2604.misc.rst
- demo/pyproject.toml
- toga/pyproject.toml
- tox.ini
- Implement https://github.com/beeware/.github/pull/137
- Run `check-wheel-contents` during `tox -e package`
- Ensure package is attested during release
- Remove `tox -e package` target
> Use new create package action with attestation

- changes/2606.misc.rst
- testbed/pyproject.toml
With the introduction of beeware/briefcase#1812 and PEP 621 license handling, the testbed project now uses a deprecated format for the `license` field. This updates the project to use the new form, avoiding the build warning associated with the old format.
> Update testbed project to use new license format.

- .pre-commit-config.yaml
- changes/2625.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.15.2 to v3.16.0 and ran the update against the repo.
> Bump pyupgrade from v3.15.2 to v3.16.0

- changes/2629.misc.rst
- core/pyproject.toml
- docs/conf.py
A historical hangover - we no longer support NumPy/Google docstring format, so we can remove the Napoleon configuration.
We can also remove the sphinx-autodoc-typehints package as a dependency, as we're not using it any more.
Stemmed from [this discussion](https://github.com/beeware/toga/pull/2628#issuecomment-2156785292)
> Remove Napoleon from the documentation configuration.

- .github/workflows/ci.yml
- changes/2631.misc.rst
- changes/2632.misc.rst
- testbed/tests/test_window.py
Corrects the intermittent failure seen in macOS CI with the `test_secondary_window_with_content` test.
The underlying cause of the crash appears to be an issue with removal of constraints; since the test involves the addition of content in a window and then rapidly deleting that window, it's at least conceptually consistent that the issue is related to ObjC reference counting on the very-short-lived window.
The problem can't be reproduced with 100% reliability, so it's difficult to confirm with 100% reliability that the problem has been resolved; but I've re-run the macOS x86-64 test [multiple times](https://github.com/beeware/toga/actions/runs/9459283216/job/26056572628?pr=2637) with this fix in place, and it doesn't seem to be occurring any more. 
This isn't a very satisfying fix - this …
> Correct flakiness in macOS CI

- android/src/toga_android/app.py
- changes/2619.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- core/tests/app/test_app.py
- core/tests/command/test_commandset.py
- core/tests/window/test_window.py
- dummy/src/toga_dummy/app.py
- gtk/src/toga_gtk/app.py
- iOS/src/toga_iOS/app.py
- textual/src/toga_textual/app.py
- web/src/toga_web/app.py
- winforms/src/toga_winforms/app.py
The existing app startup sequence is inconsistent between platforms, as it doesn't guarantee:
1. That system-installed app commands are installed before `startup()` is invoked
2. That the change listener is added to the command list *after* commands have been fully created
3. That menus are created *after* the initial menu state has been established.
Derived from #2244.
> Ensure menu creation sequence is consistent.

- .github/workflows/ci.yml
- changes/2640.misc.rst
- core/pyproject.toml
- core/src/toga/__init__.py
- core/src/toga/images.py
- core/src/toga/platform.py
- core/src/toga/plugins/image_formats.py
- pyproject.toml
- tox.ini
- As was done for Briefcase in https://github.com/beeware/briefcase/pull/1262, Toga unit testing now supports conditional coverage for the Python version
- Closes #2640.
> Add support for conditional coverage rules during unit testing

- .github/workflows/ci.yml
- changes/2635.misc.rst
- The app can fail without Briefcase creating a log....so, always create the log so it can be uploaded as an artifact
- Example run: https://github.com/beeware/toga/actions/runs/9457851473/attempts/3
> Always create Briefcase log for testbed app for upload

- changes/2638.bugfix.rst
- core/src/toga/widgets/splitcontainer.py
- core/tests/widgets/test_splitcontainer.py
- docs/reference/api/containers/splitcontainer.rst
Discovered in the review of #2252. 
SplitContainer's `content` attribute was typed as a `tuple`. Correct usage of tuple vs list is a hill I will die on :-) - and while there's a possible interpretation where SplitContainer content is considered to be N-position-sensitive content items (which *would* be consistent with a tuple), IMHO it's more natural to think of a list of content. Each item in the list has the same type, and the only unusual restriction is the content *must* have a length of 2. 
As further supporting evidence - the existing documentation refers to "A sequence of 2 elements".
> Correct the typing of SplitContainer content to be list/Sequence

- changes/2647.misc.rst
- tox.ini
- Tox is apparently a bit aggressive in shutting down processes when it receives a CTRL+C; this can ultimately result in tox exiting and leaving the HTTP server still running requiring manual process kills.
- I think this results from ``sphinx-autobuild`` receiving the SIGINT and starting its shutdown...but tox then sends it [_another_](https://tox.wiki/en/4.15.1/config.html#execute) SIGINT that seems to abort the shutdown procedure for ``sphinx-autobuild``.
- So, this gives ``sphinx-autobuild`` a window of time to shutdown before tox starts trying to help.
> Allow ``sphinx-autobuild`` time to shutdown http server in tox

- .github/dependabot.yml
- changes/2382.misc.rst
- testbed/pyproject.toml
- testbed/tests/conftest.py
- Recent versions of pytest-asyncio introduced a lot of breaking changes. Notably, a session-wide event loop can no longer be specified via the ``event_loop()`` fixture. However, an event loop policy can be specified via the ``event_loop_policy()`` fixture.
- As such, this introduces a simple event loop policy that defers to the existing event loop proxy
- Closes #2382
- Also, allows Dependabot to manage the testbed's dependencies
> Use latest dependencies for Testbed testing

- changes/2657.misc.rst
- testbed/pyproject.toml
- Dependabot [doesn't like](https://github.com/beeware/toga/network/updates/842219497) relative dependencies apparently
> Fix testbed dependencies for Dependabot

- .pre-commit-config.yaml
- changes/2660.misc.rst
Bumps `pre-commit` hook for `flake8` from 7.0.0 to 7.1.0 and ran the update against the repo.
> Bump flake8 from 7.0.0 to 7.1.0

- changes/2648.misc.rst
- testbed/src/testbed/app.py
- testbed/tests/widgets/test_mapview.py
- testbed/tests/widgets/test_webview.py
- As outlined in the references below, allowing WebKit-based WebViews to be garbage collected on GTK while the tests are running risks crashing the tests from WebKit raising a SIGABRT
- This mitigates that crash occurring by maintaining a reference to the Toga WebView until testing has completed, thereby meaning the testing thread has joined, and subsequent garbage collection can _only_ run in the main Python thread
- Fixes https://github.com/beeware/toga/issues/2648
- RE: https://github.com/beeware/toga/pull/2655
> Prevent garbage collection of WebView during testbed testing

- changes/2665.misc.rst
- winforms/src/toga_winforms/widgets/table.py
Close inspection of a [CI run for the Winforms testbed](https://github.com/beeware/toga/actions/runs/9542502328/job/26297482563) shows the following:
```
tests\widgets\test_table.py::test_headerless_column_changes PASSED       [ 75%]
tests\widgets\test_table.py::test_remove_all_columns Traceback (most recent call last):
File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app_packages\toga_winforms\widgets\table.py", line 176, in _new_item
icon = icon(self._accessors[0])
File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app_packages\toga_winforms\widgets\table.py", line 90, in winforms_retrieve_virtual_item
e.Item = self._new_item(e.ItemIndex)
File "D:\a\toga\toga\testbed\build\testbed\windows\app\src\app_packages\toga_winforms\libs\wrapper.py", line 22, in __call__
return …
```
> Catch an error that is reported, but silently ignored during CI testing

- changes/2099.removal.rst
- changes/2678.feature.1.rst
- changes/2678.feature.2.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- core/src/toga/handlers.py
- core/src/toga/window.py
- core/tests/app/test_app.py
- core/tests/app/test_customized_app.py
- core/tests/test_handlers.py
- docs/reference/api/app.rst
- dummy/src/toga_dummy/app.py
- examples/statusiconapp/statusiconapp/app.py
- examples/window/window/app.py
- gtk/src/toga_gtk/app.py
- testbed/tests/app/test_desktop.py
- testbed/tests/testbed.py
- winforms/src/toga_winforms/app.py
* Modifies the handling of `on_exit` so that it can be defined by subclassing, in addition to assigning an `on_exit` attribute
* Modifies the `running` entry point added by #2651 to be named `on_running` (reflecting it's status as a lifecycle event), following the same pattern as `on_exit`.
* Deprecates `app.add_background_task()`.
Fixes #2099.
> Define application lifecycle events by subclassing

- changes/2682.misc.rst
- cocoa/pyproject.toml
- cocoa/src/toga_cocoa/constraints.py
- cocoa/src/toga_cocoa/container.py
- cocoa/src/toga_cocoa/widgets/internal/cells.py
- cocoa/src/toga_cocoa/widgets/internal/refresh.py
- cocoa/src/toga_cocoa/widgets/textinput.py
- iOS/pyproject.toml
- iOS/src/toga_iOS/constraints.py
- iOS/src/toga_iOS/widgets/multilinetextinput.py
- iOS/src/toga_iOS/widgets/textinput.py
- testbed/tests/conftest.py
- testbed/tests/testbed.py
With the fix for beeware/rubicon-objc#148 being introduced in Rubicon 0.4.9, we can now remove the unwieldy long lines when creating NSLayoutConstraint objects.
This was fixed in the process of trying to narrow down an intermittent segfault I was seeing in the testing for #2666. The underlying fix for that issue is included here (a window cleanup autouse fixture, with explicit GC passes in the app and window cleanup fixtures). That segfault was caused by garbage collection of NSWindow (and related) objects in the pytest thread; we previously added a GC pass in the *Window* tests to allow for this class of issue, but we've recently added app tests that also create windows; and the main window is also (sometimes) prone to this issue.
Updating the constraint syntax is mostly incidental to …
> Update syntax for ObjC constraint API usage to avoid long lines.

- changes/2701.feature.rst
- core/src/toga/command.py
- core/tests/command/test_commandset.py
- docs/reference/api/resources/command.rst
Fixes #2701.
Adds the methods needed to complete the MutableSet and MutableMapping interface on CommandSet. This allows removal of commands from a command set, by either instance or ID.
To satisfy the interface, this means we need to define  `__setitem__()` (so - `app.commands["some_id"] = my_command` must be legal. This isn't a *great* API, as there's a conflict when the ID the command is registered with doesn't match the command itself; I've opted to raise an error here and not draw attention to the possible usage in docs.
> Add delete/remove APIs to Commandset.

- changes/2703.bugfix.rst
- gtk/src/toga_gtk/widgets/optioncontainer.py
- testbed/tests/widgets/test_optioncontainer.py
Fixes #2703.
Under GTK, the `current_page()` API doesn't return the current value while still in the `on_select` handler; as a result, a user-space event handler trying to retrieve the current tab will get the wrong result.
This change defers the execution of the `on_select` handler so that `current_page()` is guaranteed to return the correct result.
> Defer firing on_select event in GTK OptionContainer

- changes/2689.misc.rst
- testbed/tests/testbed.py
I *believe* the issue reported by #2689 is that the log line that outputs the test termination condition is being dropped by log streaming. The long term fix is to make sure that Briefcase either doesn't lose the log stream, or remove the need for log streaming entirely; but in the meantime, this approach has proven reliable (so far) in #2666.
This approach outputs the log termination condition 6 times, 0.5s apart. This gives multiple opportunities for the log message to be caught by the stream; Briefcase will stop the stream as soon as it sees one of them. The process will still stop - it will just take a couple more seconds to do so - which isn't a big problem when the test is already taking 3 minutes to run.
Fixes #2689.
> Speculative workaround for macOS test reporting issue.

- .pre-commit-config.yaml
- changes/2733.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.16.0 to v3.17.0 and ran the update against the repo.
> Bump pyupgrade from v3.16.0 to v3.17.0

- .readthedocs.yaml
- changes/2745.doc.rst
- changes/2745.misc.rst
- core/pyproject.toml
- docs/how-to/contribute/docs.rst
- tox.ini
To ensure a consistent and repeatable build environment, use a hard version pin on the RTD environment.
Also adds a pin to Sphinx on Python 3.9, as Sphinx 8 deprecates Python 3.9 support.
It's worth noting that the Sphinx version is stuck at 7.3.7 at present because of an incompatibility with sphinx-csv-filter; see crate/sphinx_csv_filter#49 for details.
> Add explicit RTD version pin, and protect against Sphinx 8 deprecations

- .pre-commit-config.yaml
- changes/2755.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.4.2 to 24.8.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.4.2 to 24.8.0

- .pre-commit-config.yaml
- changes/2756.misc.rst
Bumps `pre-commit` hook for `flake8` from 7.1.0 to 7.1.1 and ran the update against the repo.
> Bump flake8 from 7.1.0 to 7.1.1

- .github/workflows/ci.yml
- changes/2771.misc.rst
With beeware/briefcase#1934 being merged, we're now using the official iOS package tags. However, we haven't published wheels for Pillow with the new tags, which prevents testbed CI from running successfully on iOS.
This temporarily reverts testbed to use the 0.3.19 *stable* release, which uses the older support packages, and thus has a Pillow binary wheel available on iOS.
This can be reverted as soon as binary wheels for the new tag format have been published.
> Temporarily use the stable version of Briefcase.

- changes/2777.misc.rst
- gtk/src/toga_gtk/app.py
- gtk/src/toga_gtk/libs/gtk.py
- gtk/src/toga_gtk/screens.py
- gtk/tests_backend/app.py
- gtk/tests_backend/probe.py
- gtk/tests_backend/screens.py
- gtk/tests_backend/widgets/canvas.py
- gtk/tests_backend/window.py
- Defer to PyGObject to detect whether Wayland is in use instead of checking `WAYLAND_DISPLAY` env var
- See https://github.com/beeware/toga/pull/2473#discussion_r1721084143
> Tweak Wayland detection for robustness

- changes/2779.bugfix.rst
- winforms/src/toga_winforms/widgets/mapview.py
- winforms/src/toga_winforms/widgets/slider.py
- winforms/src/toga_winforms/widgets/webview.py
- When the WebView fails to initialize, an error dialog is now presented to the user
- Closes #2779
> Show error dialog if WebView fails to load

- changes/2792.doc.rst
- changes/2792.misc.rst
- docs/reference/api/resources/command.rst
- docs/reference/api/resources/statusicons.rst
Just a small doc fix to fix runtime errors in the Status Icon code example
As an aside, the docs also refer to "icons/green" and "icons/blue"; are these expected to exist in the source somewhere?
> fix: Copy/paste typos in Menu status icon docs

- changes/2799.misc.rst
- testbed/tests/testbed.py
- Prevent pytest-asyncio [complaining](https://github.com/beeware/toga/actions/runs/10636771863/job/29489543747#step:6:165) when [`asyncio_default_fixture_loop_scope`](https://pytest-asyncio.readthedocs.io/en/stable/reference/configuration.html) is not set
> Resolve pytest-asyncio deprecation warning

- changes/2807.misc.rst
- testbed/tests/app/test_document_app.py
> Avoid Testbed failures for `test_save_as_document`

- changes/2796.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/src/toga_cocoa/window.py
- cocoa/tests_backend/app.py
- testbed/tests/app/test_desktop.py
Fixed cocoa window content visibilty in app full screen. 
The bug was caused since in cocoa, widgets are not added to `window.content._impl.native`, but rather to `window._impl.container.native`. However, this PR uses `NSWindow.contentView` to remain internal-implementation independent and less likely to break with any future changes.
#2796 
```python
"""
My first application
"""
import toga
def handle_exit(self, widget, **kwargs):
self.exit_full_screen()
def handle_press(self, widget, **kwargs):
self.set_full_screen(self.main_window)
self.main_window.content.add(toga.Label(text="We are in App Full Screen mode"))
"""Construct and show the Toga application.
Usually, you would add your application to a main content box.
We then create a main …
```
> Fixed cocoa window content visibilty in app full screen

- changes/2812.bugfix.rst
- gtk/src/toga_gtk/app.py
- If the About Dialog's X button was clicked, a `TypeError` for the number of arguments for `_close_about()` was thrown
- Now, an arbitrary number of positional arguments is accepted; it should be noted that pressing Escape does not send an extra pos arg...
> Ensure Gtk about dialog is destroyed

- android/src/toga_android/app.py
- changes/2809.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/src/toga_cocoa/dialogs.py
- core/pyproject.toml
- core/src/toga/app.py
- core/src/toga/handlers.py
- core/tests/app/test_app.py
- core/tests/test_handlers.py
- Partially addresses #2809 
- Any asyncio Task directly created by Toga now has a strong reference throughout its life-cycle
- Users are still left to their own devices to avoid this issue in their code
> Hold strong references to asyncio Tasks until they complete

- changes/2811.bugfix.rst
- core/src/toga/handlers.py
- Previously, generator handlers would only sleep if the iteration's return value was truthy
- Now, `asyncio.sleep()` is always invoked for each generator iteration
> Always sleep between iterations of generator handlers

- android/src/toga_android/app.py
- android/tests_backend/dialogs.py
- changes/2809.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- cocoa/src/toga_cocoa/dialogs.py
- core/pyproject.toml
- core/src/toga/app.py
- core/src/toga/handlers.py
- core/tests/app/test_app.py
- core/tests/conftest.py
- core/tests/test_handlers.py
- testbed/src/testbed/app.py
- testbed/tests/conftest.py
- testbed/tests/window/test_dialogs.py
- winforms/tests_backend/dialogs.py
- This reverts and re-implements #2810
- Now, the asyncio task factory is wrapped so that Toga tracks _all_ tasks created for asyncio
- In this way, Toga and its users can call `asyncio.create_task()` with abandon
- Closes #2809
> Hold strong references to asyncio Tasks until they complete (redux)

- changes/2822.bugfix.rst
- textual/src/toga_textual/app.py
- textual/src/toga_textual/widgets/base.py
- textual/src/toga_textual/window.py
- Closes #2816 
- Closes #2817
- https://github.com/beeware/toga/pull/2823
- https://github.com/beeware/briefcase/pull/1992
> Revive textual backend

- changes/2715.misc.rst
- docs/conf.py
Fixes #2715.
I set the Sphinx [toc_object_entries_show_parents](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-toc_object_entries_show_parents) config option to "hide" to fix the bad wrapping on longer element names.
Before:
After:
> Hide right-sidebar element's parents.

- changes/2708.misc.rst
- docs/conf.py
- docs/extra/robots.txt
Fixes #2708.
Added a robots.txt file in a new folder to disallow older version docs to show up in search engines. I used Sphinx config option [html_extra_path](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_extra_path) to add the new folder.
I think it makes sense to create a new folder for this, since it can also hold a custom sitemap file, if we decide to add one in the future. However I am open to suggestions on this.
I tested the docs locally and it serves the robots.txt just fine.
> Added robots.txt to disallow older version docs.

- changes/2834.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- examples/handlers/handlers/app.py
- winforms/src/toga_winforms/app.py
Modifies the startup sequence of Windows and macOS apps so that the event loop is guaranteed to be running at the point startup is invoked. This ensures it is possible to call `asyncio.create_task()`.
This isn't an issue on other platforms:
* On GTK, startup is triggered by the GTK app's `activate` message, which requires the app loop is running
* On iOS, startup is triggered by the receipt of the `application:didFinishLaunchingWithOptions:` selector on the AppDelegate, which requires the app loop is running
* On Android, startup is triggered explicitly when the main loop is started; but the main loop is cooperative, based on the Java context handling events.
* On Web, there's no explicit event loop creation; asyncio works as soon as the interpreter has started.
* On Textual, the app …
> Modify startup on Windows and macOS so event loop is running when startup is called

- changes/2729.bugfix.rst
- testbed/tests/window/test_window.py
- winforms/src/toga_winforms/window.py
Fixes #2729.
Followed the solution outlined on the issue discussion and added a new test to verify it works.
> Window size stays the same after minimizing and unmizing the window

- changes/2849.bugfix.rst
- iOS/src/toga_iOS/widgets/box.py
- iOS/src/toga_iOS/widgets/divider.py
- iOS/src/toga_iOS/widgets/switch.py
- testbed/tests/widgets/test_divider.py
- testbed/tests/widgets/test_switch.py
The Switch and Divider widgets on iOS  were keeping hard references to the underlying impl/interface, causing leaks.
The same fix *should* be possible on Box as well... but making the change causes a segfault on OptionContainer and ScrollContainer tests. The fix wasn't obvious; I figured it's better to live with the existing leak for now, and fix the leak where we know it exists. There's likely some overlap with the consequences of beeware/rubicon-objc#256.
Refs #2849.
> Correct leaks on Switch and Divider on iOS.

- android/tests_backend/window.py
- changes/2836.bugfix.rst
- iOS/src/toga_iOS/container.py
- iOS/tests_backend/window.py
- testbed/tests/app/test_mobile.py
As part of the introduction of simple apps in #2649, the handling of containers on iOS was refactored to introduce NavigationContainer (which has a navigation bar) as distinct from RootContainer (which doesn't). However, this refactor inadvertently altered the calculation of the available height of the container in the NavigationContainer case to *not* include the height of the navigation bar itself. The mechansim to compute the top bar height was present - but due to inheritance, the top bar height wasn't subtracted from the container height.
This restores the use of top bar height in container calculations, and adds a testbed test to ensure that content fits in the available area in mobile layouts.
Fixes #2836.
> Ensure that the top bar size is included in iOS layout calculations.

- changes/2860.bugfix.rst
- cocoa/src/toga_cocoa/app.py
- core/src/toga/app.py
- core/tests/app/test_document_app.py
- pyproject.toml
Apps that specify both `document_types` and a `main_window` no longer display the "Document Selection" dialog on startup in macOS.
Fixes #2860
> Fix document mode on macOS

- .pre-commit-config.yaml
- changes/2884.misc.rst
Bumps `pre-commit` hook for `pre-commit-hooks` from v4.6.0 to v5.0.0 and ran the update against the repo.
> Bump pre-commit-hooks from v4.6.0 to v5.0.0

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- android/pyproject.toml
- changes/2888.removal.rst
- cocoa/pyproject.toml
- core/README.rst
- core/pyproject.toml
- core/src/toga/command.py
- core/src/toga/documents.py
- core/src/toga/handlers.py
- core/src/toga/sources/tree_source.py
- core/src/toga/statusicons.py
- core/src/toga/window.py
- demo/pyproject.toml
- dummy/pyproject.toml
- gtk/pyproject.toml
- iOS/pyproject.toml
- pyproject.toml
- textual/pyproject.toml
- toga/pyproject.toml
- tox.ini
- web/pyproject.toml
- winforms/pyproject.toml
Python 3.8 is EOL at the end of this month, and #2886 highlights that we've reached the point where maintaining dependencies for 3.8 is becoming increasingly problematic.
This PR bumps the minimum Python requirement for Toga to 3.9, and removes the Python 3.8 compatibility workarounds.
As part of this change, the CI matrix for core has been modified slightly. 
It turns out that we *do* need to run the test matrix on every version of Python - because we have conditional branches that are conditional on every version of Python on every platform. The "min and max only" testing approach was masking the fact that one of the conditional branches was using a "< 3.9" check, when it should have been a "< 3.10" check, because of a windows-specific issue.
However, we *don't* need to test core on …
> Deprecate Python 3.8

- .github/workflows/ci.yml
- changes/2893.misc.rst
- Closes https://github.com/beeware/toga/issues/2871
- When I use a newer version of mutter locally, the issue goes away...
- Seven [successful runs](https://github.com/beeware/toga/actions/runs/11245617170/job/31267033524) with Ubuntu 24.04
> For Wayland, run testbed on Ubuntu 24.04

- .pre-commit-config.yaml
- changes/2898.misc.rst
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.8.0 to 24.10.0 and ran the update against the repo.
> Bump black-pre-commit-mirror from 24.8.0 to 24.10.0

- .pre-commit-config.yaml
- changes/2897.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.17.0 to v3.18.0 and ran the update against the repo.
> Bump pyupgrade from v3.17.0 to v3.18.0

- android/src/toga_android/libs/events.py
- changes/2907.bugfix.rst
Update the Android event loop integration to replace the use of an internal API that has changed in Python 3.13 with the underlying (also internal) API that has been backing the API that was removed all along.
Fixes #2907.
> Update Android event loop integration for Py3.13.

- changes/2912.misc.rst
- core/src/toga/images.py
- core/src/toga/platform.py
Now that Toga's dropping 3.8 support, I remembered a spot in `images` where I used `functools.lru_cache` because `cache` wasn't added until 3.9.
From the [docs](https://docs.python.org/3/library/functools.html#module-functools) on `cache`:
> Returns the same as `lru_cache(maxsize=None)`, creating a thin wrapper around a dictionary lookup for the function arguments. Because it never needs to evict old values, this is smaller and faster than `lru_cache()` with a size limit.
So in that case it's a one-to-one swap. But I noticed one other place too, in `platform`. There it's `maxsize=1` instead of `None`, which *could* behave differently — only keeping the most recent call instead of all calls — except that `get_platform_factory()` accepts no arguments, so it can only ever cache one value …
> Replacing lru_cache with cache, post-3.8

- changes/2918.bugfix.rst
- core/src/toga/app.py
Running the entire core test suite completes successfully. But at least one test (and probably others), when run individually, fail. Running `tests/style/pack/layout/test_rtl.py` by itself gets six instances of this:
```
@pytest.fixture(autouse=True)
def no_dangling_tasks():
"""Ensure any tasks for the test were removed when the test finished."""
yield
>       if toga.App.app:
E       AttributeError: type object 'App' has no attribute 'app'
tests/conftest.py:22: AttributeError
```
This is fine if a previous test has created an app instance, which is why it only fails in isolation. Changing it to a `hasattr` check fixes it, but then it still needs an additional truthiness or `None` check to avoid failing `test_window_created_without_app`, which sets `App.app` to `None`. At that point, why …
> Set App.app to initial value of None  to avoid AttributeError in teardown

- .pre-commit-config.yaml
- changes/2934.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.18.0 to v3.19.0 and ran the update against the repo.
> Bump pyupgrade from v3.18.0 to v3.19.0

- changes/2939.misc.rst
- core/src/toga/widgets/base.py
- docs/reference/style/pack.rst
- docs/tutorial/tutorial-0.rst
In non-web-related contexts, terms such as "DOM" and "element" are potentially confusing to users with no web development experience. Replace with the terminology used elsewhere in the docs.
> Rephrase web-specific language in docs

- changes/2949.bugfix.rst
- textual/src/toga_textual/window.py
When trying to create a dialog using the Textual backend, I get a TypeError warning about too many inputs 
The code used works on GTK.
This change solves that error
> Update window.py to be able to create dialogs in Textual

- changes/2951.misc.rst
- docs/reference/platforms/android.rst
Removes usage of the `new` keyword in an example of using Java APIs in Python.
> Remove Java idiom from example code.

- changes/2950.bugfix.rst
- core/src/toga/style/pack.py
- core/tests/style/pack/test_apply.py
- core/tests/style/pack/utils.py
- testbed/tests/widgets/test_base.py
Descendants of hidden widgets should always be visually hidden, regardless of what their style is set to. The testbed appears to test for this, in `tests/widgets/test_base.py::test_visibility`:
```python
widget.style.visibility = HIDDEN
await probe.redraw("Widget should be hidden again")
assert probe.is_hidden
assert child_probe.is_hidden
assert grandchild_probe.is_hidden
child.style.visibility = VISIBLE
await probe.redraw("Child style of widget should be visible")
assert probe.is_hidden
assert child_probe.is_hidden
assert grandchild_probe.is_hidden
```
However, it's accidentally testing a coincidence. The child widget is already set to visible (or rather its visibility hasn't been set yet, but that's the initial value, so it's essentially the same thing). Therefore setting it to VISIBLE …
> Fix visibility for descendants of hidden widgets

- android/tests_backend/widgets/table.py
- changes/2956.bugfix.rst
- cocoa/tests_backend/widgets/base.py
- cocoa/tests_backend/widgets/table.py
- gtk/tests_backend/widgets/table.py
- testbed/tests/widgets/test_table.py
- winforms/src/toga_winforms/widgets/table.py
- winforms/tests_backend/probe.py
- winforms/tests_backend/widgets/table.py
This introduces the ability to perform first-letter keyboard navigation in tables and lists on windows. In the majority of native lists and tables, it is possible to type the first couple of letters of an item that exists in the list to instantly scroll to that item. As a completely blind computer programmer, this method of list navigation is invaluable to me and other visually impaired computer users when navigating a list containing content we are already somewhat familiar with. I am creating a Toga application with a list containing hundreds of items, and discovered that, though it already works on MacOS with the Voice Over screen reader, I was unable to navigate to list items by letter on windows, making my large list much more difficult to navigate, as now I must use page up/down to …
> Add a handler for ListView.SearchForVirtualItem in winforms backend for keyboard navigation in tables and detailed lists

- changes/2991.misc.rst
- testbed/tests/conftest.py
- testbed/tests/hardware/test_camera.py
When using `briefcase dev --test` on the test bed, the Camera tests fail on macOS.
This is because the `Python.app` bundle does not include `NSCameraUsageDescription` in its `Info.Plist`.
`pyproject.toml` is configured to emit this with `permission.camera`, but `briefcase dev` does not use this. To use this permission we must call `briefcase run` instead, which emits a .xcodeproj file and builds a full macOS application.
This PR skips the test when using `briefcase dev` and instructs the user to test under `briefcase run` instead.
> Skip failing camera tests on macOS when using 'briefcase dev'

- android/src/toga_android/window.py
- changes/3016.misc.rst
- cocoa/tests_backend/window.py
- testbed/tests/conftest.py
Fixes #3016 
The testbed test was failing since the test assertion was being done even before the window state change was completed. The failure only affected macOS-arm64, since a longer delay before assertion is required on macOS-arm64 for fullscreen transition. Since, we cannot differentiate between macOS-x86_64 and macOS-arm64, so on the cocoa backend the delay for fullscreen is 1s now.
I apologise for causing any inconveniences.
> Fix `test_window_state_assignment` testbed on macOS-arm64

- changes/3020.misc.rst
- examples/hardware/hardware/app.py
- examples/hardware/pyproject.toml
- examples/simpleapp/pyproject.toml
- examples/simpleapp/simpleapp/app.py
- examples/tutorial0/pyproject.toml
- examples/tutorial0/tutorial/app.py
- examples/tutorial1/pyproject.toml
- examples/tutorial1/tutorial/app.py
- examples/tutorial2/pyproject.toml
- examples/tutorial2/tutorial/app.py
- examples/tutorial3/pyproject.toml
- examples/tutorial3/tutorial/app.py
- examples/tutorial4/tutorial/app.py
Modifies the example code to use `org.beeware.toga.examples` as a consistent bundle definition.
This is partially for consistency, but also because the inconsistency in bundle ID naming between ``pyproject.toml`` and the app code in tutorial 4 led to [this change](https://github.com/beeware/briefcase/pull/802#issuecomment-1195795545), which added a Flatpak security default which was a little more liberal than was needed.
Refs beeware/briefcase#2074.
> Use a consistent bundle ID for all examples.

- changes/3035.bugfix.rst
- web/src/toga_web/factory.py
- web/src/toga_web/fonts.py
- web/src/toga_web/static/toga.css
This fixes the issue mentioned at https://github.com/beeware/briefcase-web-static-template/pull/16#issuecomment-2408411025:
> Style appears to have been lost from dialogs. The about dialog in Tutorial 0 displays in "browser default serif", not the Shoelace sans-serif default.
It looks like the style sheet simply never set a font on the top-level element, so the browser default was used on any elements which didn't specify their own font. This affected not only dialogs, but also Toga labels. 
Also added a dummy Font implementation class, to fix the following error, which I guess may have been introduced by #2937:
```
File "/lib/python3.12/site-packages/tutorial/app.py", line 9, in build
box = toga.Box()
^^^^^^^^^^
File "/lib/python3.12/site-packages/toga/widgets/box.py", line 25, in …
```
> Web backend font fixes

- changes/1943.feature.rst
- core/src/toga/style/pack.py
- core/tests/style/pack/layout/test_gap.py
- core/tests/style/pack/test_css.py
- docs/reference/style/pack.rst
- docs/tutorial/tutorial-1.rst
- examples/colors/colors/app.py
- examples/tutorial1/tutorial/app.py
* Fixes #1943
This PR is stacked on top of #3033, which should be merged first. To view only the relevant changes on the "Files changed" page, open the commits menu at the top left and use shift-click to select a range of commits.
I haven't updated all the examples that could benefit from this, but I've done one each with a row and a column layout.
> Add `gap` style

- .pre-commit-config.yaml
- changes/3058.misc.rst
Bumps `pre-commit` hook for `pyupgrade` from v3.19.0 to v3.19.1 and ran the update against the repo.
> Bump pyupgrade from v3.19.0 to v3.19.1

- changes/3062.misc.rst
- core/src/toga/style/pack.py
There's no functional difference, but I noticed I was returning the value from `__setitem__` and `__delitem__`, which doesn't make any sense.
Refs #3033, #3044, #3048
I can't seem to stop amending this one PR...
> Removed superfluous returns in compat section

- changes/1194.feature.rst
- core/src/toga/style/pack.py
- core/tests/style/pack/layout/test_justify_content.py
- core/tests/style/pack/test_css.py
- docs/reference/style/pack.rst
- examples/layout/layout/app.py
* Refs #1194
This PR implements the main axis alignment property discussed in the above issue. I'll leave cross-axis alignment changes to a separate PR, because it looks like it'll require some changes in how the min/available/actual sizes are passed up and down the layout hierarchy.
> Add `justify_content` style

- android/pyproject.toml
- changes/3089.misc.rst
- cocoa/pyproject.toml
- core/pyproject.toml
- demo/pyproject.toml
- dummy/pyproject.toml
- gtk/pyproject.toml
- iOS/pyproject.toml
- textual/pyproject.toml
- toga/pyproject.toml
- web/pyproject.toml
- winforms/pyproject.toml
Fixes #3089.
Moves to a pinned, formally published version of setuptools-dynamic-dependencies. This should slightly speed up builds.
> Move to a pinned, formally published version of setuptools-dynamic-dependencies

- changes/3103.misc.rst
- testbed/tests/widgets/test_webview.py
#3068 added an API to retrieve cookies from WebView; however, the test for this feature has been flaky on iOS and macOS. This appears to be due to a race condition in the testbed - the `on_load` signal isn't a 100% reliable mechanism to prove that the webview is fully initialised and ready to accept Javascript calls. 
You can overcome this by adding a short delay before setting the cookie. This PR adds a retry strategy to setting the cookie so that the delay is as short as is practical.
> Add a retry for setting the cookie in webview tests.

- changes/3104.misc.rst
- iOS/src/toga_iOS/widgets/base.py
A bug has slipped past me in #3009. The current implementation sets `backgroundColor = None` as the default background color. The docs also mentions that `None` or `nil` gets the default background color, which is the transparent background color: https://developer.apple.com/documentation/uikit/uiview/backgroundcolor?language=objc:
>Changes to this property can be animated. The default value is nil, which results in a transparent background color.
However, contrary to the docs, when `backgroundColor = None` is set as the default background color for `UILabel`, then it displays a black background color instead:
On further testing, I have found that the default background color(default value of `native.backgroundColor`) which the system assigns to `UILabel` on initialization is not …
> Fix #3009 (iOS default widget background color)

- changes/3105.bugfix.rst
- gtk/src/toga_gtk/window.py
- testbed/tests/window/test_window.py
Currently, on all platforms except on gtk, when the window is hidden using `hide()`, the `window.state` getter continues to report the same state as it did when the window was last visible. But on gtk, when the window is hidden, `window.state` getter always reports it as `WindowState.NORMAL`. This PR fixes the bug on gtk. 
This bug was identified in #2096. Since, it would take some time to accommodate the other inconsistencies identified on gtk for implementation of visibility events(i.e., `on_show` and `on_hide`), I have created this fix as a separate PR, independent of the other PRs.
> Fix gtk `window.state` getter when window is hidden

- android/src/toga_android/window.py
- changes/3109.removal.rst
- core/src/toga/window.py
- core/tests/window/test_window.py
- dummy/src/toga_dummy/window.py
- iOS/src/toga_iOS/window.py
- testbed/tests/window/test_window.py
As identified in #2096, the behavior of hiding a window while in MINIMIZED, FULLSCREEN or PRESENTATION state, is inconsistent on macOS:
|From state|Result on calling `window.hide()`|Result of then calling `window.show()`|
|--|--|--|
|`NORMAL`|Window is not visible and window icon is not visible in the dock|Window becomes visible and window icon becomes visible in the dock|
|`MINIMIZED`|Window is not visible and window icon is not visible in the dock|Window becomes visible & un-minimized, and window icon becomes visible in the dock|
|`MAXIMIZED`|Window is not visible and window icon is not visible in the dock|Window becomes visible and window icon becomes visible in the dock|
|`FULLSCREEN`|Screen becomes black|Window becomes visible in fullscreen like before|
|`PRESENTATION`|window content …
> Disable hiding window while in `MINIMIZED`, `FULLSCREEN` or `PRESENTATION` state and ignore no-op visibility requests

- changes/3111.feature.rst
- core/src/toga/style/mixin.py
- core/src/toga/style/pack.py
- core/tests/style/pack/__init__.py
- core/tests/style/pack/test_aliases.py
- core/tests/style/pack/test_deprecated_properties.py
- core/tests/style/test_mixin.py
- docs/reference/style/pack.rst
> Add "horizontal" and "vertical" aliases for align_items and justify_content

- changes/3117.misc.rst
- gtk/src/toga_gtk/colors.py
- gtk/src/toga_gtk/widgets/button.py
Originally identified in #2484. However, since these changes are not directly related to #2484, so I have separated these changes from that PR.
This PR caches the decoded toga color on gtk, and also includes a minor cleanup.
> Cache decoded toga color on gtk

- changes/3125.misc.rst
- iOS/src/toga_iOS/widgets/base.py
While working on #2484, I noticed that the setting of `_default_background_color` attribute on iOS is not correct:
https://github.com/beeware/toga/blob/25891f05aba1b25a7a81e056ced24a0be76f7818/iOS/src/toga_iOS/widgets/base.py#L8-L18
Although, currently no widget on iOS is setting a different `_default_background_color`, but if any widget did override it, then `_default_background_color` would be overridden during the `create()` call. 
But we are unconditionally setting the `_default_background_color ` on line 18, which would discard any custom `_default_background_color` that may be specified by a widget. 
This PR was fixing this behavior by:
https://github.com/beeware/toga/blob/29d0fd553c27ffe59cf9efa34e22d8b1d0b82fc6/iOS/src/toga_iOS/widgets/base.py#L8-L19
However, since no widget is …
> Remove erroneous note about `_default_background_color` override behavior on iOS

- .pre-commit-config.yaml
- changes/3133.misc.rst
- core/tests/window/test_window.py
- gtk/src/toga_gtk/widgets/detailedlist.py
Bumps `pre-commit` hook for `codespell` from v2.3.0 to v2.4.0 and ran the update against the repo.
> Bump codespell from v2.3.0 to v2.4.0

- changes/3131.removal.rst
- core/src/toga/window.py
- core/tests/window/test_window.py
- dummy/src/toga_dummy/window.py
Related PR: #2364 
Currently, all resize requests are passed down to the `impl` layers, even when the same window size as the current size is requested. Although this is a no-op on most backends, but on some backends(like on gtk), this results in firing of window resize events at wrong times. 
Hence, this PR ignores such no-op window resize requests at the core, preventing them from being transmitted to the `impl` layer.
> Ignore no-op window resize requests

- changes/3115.misc.rst
- core/src/toga/style/pack.py
- travertino/src/travertino/declaration.py
- travertino/tests/test_choices.py
- travertino/tests/test_declaration.py
- travertino/tests/test_node.py
While we're switching over to the dataclass-based Pack properties — and haven't put out a release yet with them — I'd like to propose a tweak to how they're instantiated.
The [first commit](https://github.com/beeware/toga/pull/3115/commits/8535a03e93f7ea7e1438eac1644cbdbf68dc80a6) is a stylistic one; I'm not sure if there was a particular reason for defining all the Choices objects at the top in #311; I suspect it was because the actual property creation had to be buried way down at the bottom of the file, due to the class method implementation? I've inlined them into the property definitions. It makes for a little bit of repetition in some of them, but the information's all in one place.
```python
SIZE_CHOICES = Choices(NONE, integer=True)
...
width: str | int = …
```
> Proposal: Change to validated property API

- .pre-commit-config.yaml
- changes/3148.misc.rst
Bumps `pre-commit` hook for `isort` from 5.13.2 to 6.0.0 and ran the update against the repo.
> Bump isort from 5.13.2 to 6.0.0

- .pre-commit-config.yaml
- changes/3146.misc.rst
Bumps `pre-commit` hook for `codespell` from v2.4.0 to v2.4.1 and ran the update against the repo.
> Bump codespell from v2.4.0 to v2.4.1

- changes/3151.bugfix.rst
- changes/3151.misc.rst
- core/src/toga/compat/collections/abc.py
- travertino/src/travertino/declaration.py
- travertino/tests/test_declaration.py
Ran into a moderately scruffy yak. My main motivation for adding the union operators to BaseStyle was to be able to compose styles, and I just realized one thing currently works very counterintuitively for that.
This works as expected:
```python
>>> p = Pack(gap=1) | Pack()
>>> p.gap
1
```
But I'd call this a bug:
```python
>>> p = Pack(gap=1) | Pack(gap=0)
>>> p.gap
1
```
Especially since this behaves differently:
```python
>>> other_p = Pack(gap=1)
>>> other_p.gap = 0
>>> p = Pack(gap=1) | other_p
>>> p.gap
0
```
The root cause is that explicitly setting a property to its initial value does nothing — in other words, doesn't assign to the underscore attribute — if the property is currently not set. On the other hand, setting it to something else first and *then* to its initial value …
> Consistently handle style properties that are explicitly set to initial value

- changes/2721.removal.rst
- core/src/toga/handlers.py
- core/tests/test_handlers.py
- demo/toga_demo/app.py
- examples/handlers/handlers/app.py
- examples/textinput/textinput/app.py
- examples/tutorial2/tutorial/app.py
- examples/window/window/app.py
Fixes #2721.
Deprecates the use of generators as event handlers.
> Deprecate use of generators as handlers.

- android/src/toga_android/widgets/base.py
- changes/3165.misc.rst
The [comment](https://github.com/beeware/toga/pull/3160#pullrequestreview-2594637936) about Android needing to reapply styles after a widget's constructed piqued my curiosity... Does it?
I'm pretty sure this is just a holdover from before #2942, when all backends had to do this.
> Remove reapply from Android Widget.__init__

- changes/3186.misc.rst
- core/src/toga/style/mixin.py
- travertino/src/travertino/declaration.py
In #3086 and #3151, I found once I submitted to CI that I was running up against limitations of MicroPython's syntax in `style_mixin()` and `BaseStyle.keys()`, respectively. There's nothing *wrong* with what I ended up using instead... but I think my first drafts read better, and we're no longer bound by MicroPython.
While I was making stylistic cleanups, I also simplified a couple of lines in `validated_property.__get__()`.
> Switch to Micropython-incompatible syntax

- changes/3170.doc.rst
- core/src/toga/widgets/base.py
- core/src/toga/window.py
- docs/background/project/philosophy.rst
- docs/how-to/topics/api-design.rst
- docs/how-to/topics/index.rst
- docs/spelling_wordlist
@ntoll asked me to summarize the principles we follow for naming things in Toga, so I added an API design page to the documentation.
> Add API design document

- android/src/toga_android/__init__.py
- changes/3183.misc.rst
- cocoa/src/toga_cocoa/__init__.py
- core/src/toga/__init__.py
- dummy/src/toga_dummy/__init__.py
- gtk/src/toga_gtk/__init__.py
- iOS/src/toga_iOS/__init__.py
- textual/src/toga_textual/__init__.py
- travertino/src/travertino/__init__.py
- web/src/toga_web/__init__.py
- winforms/src/toga_winforms/__init__.py
Now that Toga is pinned to a specific version of Travertino, we can consolidate the two copies of this code.
> Move _package_version to travertino

- changes/3160.removal.rst
- core/src/toga/style/pack.py
- core/tests/style/pack/test_apply.py
- core/tests/widgets/test_base.py
- travertino/src/travertino/declaration.py
- travertino/src/travertino/node.py
- travertino/tests/test_choices.py
- travertino/tests/test_declaration.py
- travertino/tests/test_layout.py
- travertino/tests/test_node.py
- travertino/tests/utils.py
The name of `BaseStyle.reapply()` doesn't really reflect what it does. The presence of `apply()` and `reapply()` implies they do at least roughly the same thing, except one is for the first time and the other is for subsequent uses — whereas the actual difference is that `apply()` applies a single property, while `reapply()` applies all of them. Ironically, it's the *first* of the two methods to be (successfully) called, once the applicator is assigned.
~~I'd like to rename `reapply` to `apply_all`. I'm also all ears to alternate spellings, if you think something else would be preferable.~~
EDIT: Based on discussion, this now modifies `apply()` such that calling it with no arguments replaces the use of `reapply()`.
> Replace reapply() with bare apply()

- changes/3212.misc.rst
- travertino/src/travertino/properties/shorthand.py
- travertino/tests/test_style.py
Because I wrote `hasattr(obj, name)` rather than `hasattr(obj, f"_{name}")`, the `is_set_on` method for `directional_property` currently looks for the existence of the descriptors themselves rather than the private stored values, and thus always returns `True`.
But even better than `hasattr(obj, f"_{name}")` is `name in obj`, to leverage the `is_set_on` method of each individual property in question.
> Fix __contains__ check for directional_property

- changes/3216.misc.rst
- core/src/toga/style/mixin.py
- travertino/src/travertino/style.py
One more bit of MicroPython compatibility that's no longer needed, from #3086. Why not be five lines shorter? : )
Also fixes a typo in the comment below, which I could swear I'd already done. Maybe that was in an unmerged PR back in the old repository.
> Restore __init_subclass__

- changes/3257.misc.rst
- travertino/src/travertino/style.py
An oversight in #3160: the signature in `BaseStyle.apply()` was never updated to match the new signature of `Pack.apply()`.
> Update BaseStyle.apply() signature

- changes/3268.bugfix.rest
- core/src/toga/style/pack.py
- core/tests/style/test_applicator.py
Some style properties trigger a widget refresh / layout recalculation when changed, and some don't. `text_direction` has, until now, been one of the latter. However, now that we have `align_items` and `justify_content`, changing `text_direction` can, in fact, alter how children are aligned.
I don't think there was an existing test of specifically which properties trigger a refresh and which didn't, so I've added those. At first I had an issue, in that `assert_action_not_performed(widget, "refresh")` always failed; this was because `refresh` was getting called in the fixture, before my test even received the widget. This also means that `test_refresh` could get a false positive:
```python
def test_refresh(widget):
"""Refresh requests are passed to the widget."""
widget.applicator.refresh() …
```
> Refresh widget layout on text_direction change

- changes/3266.bugfix.rst
- winforms/src/toga_winforms/app.py
- winforms/src/toga_winforms/libs/proactor.py
When a Winforms app shuts down, it doesn't appear to be triggering the end-of-life loop handling. As a result, if PYTHONDEVMODE=1 is enabled (or, if warnings are enabled and/or asyncio debug mode is enabled), an app will raise errors about unclosed event loops, unclosed sockets, and pending operations at deallocation.
The Winforms Proactor is essentially a deconstructed version of `asyncio.loop.run_forever()` - it pulls out the "run once" logic to invoke each iteration on a timer callback. In the old implementation, the "loop cleanup" logic (the code contained in the `finally` block of the original `run_forever()` method) was being invoked as part of the "run once" logic, presumably on the basis that on the last tick, the loop will have been stopped, and cleanup logic could be invoked. …
> Correct end-of-life handling for Winforms Proactor.

- changes/3269.bugfix.rst
- winforms/src/toga_winforms/widgets/table.py
The current Windows behaviour differs from that of other platforms (eg MacOS), where selected rows are highlighted.  This change allows Toga on Windows to highlight a selected row in a table after the table has lost the focus.
For example, the upper table in this screenshot has the focus, but the row selection in the lower table now shows the grey highlight. Previously, the lower table would have given no indication of the row selection.
This provides a similar visual indication of row selection to that provided on other (ie non-Windows) platforms.
Fixes #3269.
I'm aware I need to add a change note file. I'll add that when I've figured out how (first PR).
> Enable highlighting of a selected table row in Winforms

- changes/3296.bugfix.rst
- gtk/src/toga_gtk/app.py
Gio.ApplicationFlags.DEFAULT_FLAGS does not exist for Gtk 3 and errors out into an AttributeError failing to create the application. Reverting back to FLAGS_NONE fixes this issue.
> Fixes an issue that causes linux applications to crash on Gtk 3.

- changes/3302.misc.rst
- core/src/toga/widgets/canvas/context.py
I just missed it before you merged it, but I didn't re-add `anticlockwise` and mark it as deprecated after I changed it to `counterclockwise` in the docstrings.
> Re-add anticlockwise parameter to docstrings (and mark as deprecated)

- changes/3321.feature.rst
- examples/canvas/canvas/app.py
I've made some changes to the Canvas example app, primarily in the controls.
- Additional labels and spacing
- The line height slider is now with the rest of the text controls, and it enables and disables along with them.
- Line width is re-labeled to stroke width, to be less ambiguous alongside text line height
- Fill rule moves down to the second line, alongside the stroke settings. These now enable and disable based on the current context.
I also made some minor / stylistic code tweaks, while I was here:
- Condensed `get_weight` / `get_style` to one-liners
- Removed the unnecessary `canvas` parameter to `get_context`
- Changed two cases of `list(dictionary.keys())` to `list(dictionary)`, since it already takes the keys
- Condensed the hard-coded coordinates in `draw_triangles()` to a …
> Canvas example app UI improvements

- changes/3346.misc.rst
- examples/hardware/pyproject.toml
- examples/mapview/pyproject.toml
- examples/passwordinput/pyproject.toml
- examples/simpleapp/pyproject.toml
- examples/statusiconapp/pyproject.toml
Adds in a dependency on travertino for 5 example apps that were missing it.
I'm not sure how these 5 were missed in previous updates, but they clearly were.
> Add some missing travertino dependencies.

- changes/3342.bugfix.rst
- textual/pyproject.toml
- textual/src/toga_textual/app.py
If an app is run with Textual 3.0, it generates log messages on output due to textualize/textual#5091. 
This was discovered in the context of #3299. The existing version pin was open ended, and allowed for major version changes to be required in by Toga codebase without testing.
This PR bumps the minimum Textual version to 3.0, and imposes a 4.0 upper bound to avoid similar problems emerging.
It also changes the way that the Textual app is started (effectively reproducing `textual.App.run()`) so that the log messages on exit are captured.
Fixes #3343.
> Correct textual app execution to prevent stray log messages

- changes/3394.bugfix.rst
- core/src/toga/app.py
- core/tests/conftest.py
Fixes #3394 
Python 3.13.3 ensured that the `name` argument was passed down to task factories; this exposed a bug in Toga's task factory wrapper, as it didn't accomodate the `name` argument. A task factory is documented as having the prototype `factory(loop, coro, **kwargs)`; this modifies the Toga definitions to match that prototype. It can be assumed that the arguments passed to the factory will be internally compatible with Task, as they should be version locked with respect to features.
> Use the documented prototype for task factories.

- changes/3396.bugfix.rst
- core/src/toga/style/pack.py
Added correct type annotations to `Path.margin` (and deprecated `Path.padding`).
Fixes #3396.
> Fix type annotation on Pack.margin

- changes/2854.feature.rst
- core/src/toga/widgets/webview.py
- core/tests/widgets/test_webview.py
> Add a write-only property in WebView to set the contents without an annoying empty string.

- changes/2851.feature.rst
- core/src/toga/widgets/webview.py
- core/tests/widgets/test_webview.py
> Support instantializing WebView w/ static content.

- changes/3404.misc.rst
- docs/reference/api/widgets/numberinput.rst
`min` and `max` are the current keywords. They _were_ previously documented incorrectly as `min_value` and `max_value`.
Note that the syntax highlighting is a little funny, I guess since these are Python function names:
> NumberInput documentation fix

- changes/3447.misc.rst
- docs/reference/api/widgets/slider.rst
Update Slider widget documentation as requested in #3447 , replacing the `range` keyword with `min` and `max`.
Fixes #3447.
> Update Slider docs to use min and max instead of range.

- README.rst
- android/README.rst
- changes/3439.misc.rst
- cocoa/README.rst
- core/README.rst
- gtk/README.rst
- iOS/README.rst
- textual/README.rst
- toga/README.rst
- travertino/README.rst
- web/README.rst
- winforms/README.rst
Noticed this after publishing the Toga 0.5.1 wheels.
> Correct version number reference.

- changes/3451.bugfix
- changes/3451.bugfix.rst
- web/src/toga_web/widgets/button.py
Use addEventListener("click", ...) to correctly attach button press handlers in Toga Web.
Fixes buttons in the Web backend not triggering on_press callbacks when clicked.
Fixes #3451
> Fix button click handling in Toga Web backend to correctly trigger event

- changes/3444.bugfix.rst
- core/src/toga/app.py
- core/src/toga/window.py
- core/tests/app/test_app.py
Add a raise ValueError to the startup method
Ensure the startup method returns valid content by raising a ValueError when None is returned
Fixes #3444
> Ensure the startup method returns valid content by raising a ValueError when None is returned

- changes/3472.bugfix.rst
- cocoa/tests_backend/widgets/base.py
- cocoa/tests_backend/widgets/table.py
- cocoa/tests_backend/widgets/tree.py
- testbed/tests/widgets/test_table.py
- winforms/src/toga_winforms/widgets/table.py
Add additional event handler dedicated for `ListViewVirtualItemsSelectionRangeChanged` events, so `winforms_item_selection_changed` method no longer handles both the `ListViewItemSelectionChanged` and `ListViewVirtualItemsSelectionRangeChanged` event. 
For single selection tables, only `ListViewItemSelectionChanged` event is being handled when new items are being selected. 
For multiple selection tables, only `ListViewVirtualItemsSelectionRangeChanged` event is being handled when multiple items' selection states are changed.
Fix #3265
> Correct event firing on Winforms tables

- changes/3525.bugfix.rst
- gtk/src/toga_gtk/app.py
- gtk/src/toga_gtk/libs/gtk.py
Support slightly older GTK4 by checking Glib version instead.
Fixes #3524.
> Check DEFAULT_FLAGS based on Glib version, not GTK version.

- cocoa/pyproject.toml
- cocoa/src/toga_cocoa/app.py
- iOS/pyproject.toml
- iOS/src/toga_iOS/app.py
Python 3.14 deprecates the concept of an asyncio EventLoopPolicy; asyncio events should now create their own event loop that implements the policy directly. 
Rubicon 0.5.1 includes the code to support the new API, and provides a backwards-compatibility shim - but raises a warning on older Pythons to advise an upgrade to use the new shim.
This PR implements that upgrade.
> Upgrade usage of Rubicon event loop to use Python 3.14-compatible API.

- changes/3236.feature.rst
- core/src/toga/paths.py
- docs/reference/api/resources/app_paths.rst
- docs/spelling_wordlist
- testbed/tests/test_paths.py
Updated `Paths` properties `config`, `data`, `cache`, and `logs`, to create the path if it does not already exist.
This eliminates the need for the user to verify the existence of and potentially create the paths when using this feature.
Fixes #3236
> Updated paths properties to create a non-existent path.

- changes/3546.bugfix.rst
- cocoa/src/toga_cocoa/widgets/multilinetextinput.py
- gtk/tests_backend/widgets/base.py
- testbed/tests/widgets/test_multilinetextinput.py
- testbed/tests/widgets/test_textinput.py
This disables the macOS default smart quotes behavior in the MultilineTextField widget. Smart quotes are enabled by default in macOS, and without this fix, double quotes are converted to smart quotes in the widget, which breaks using it to write to code or config files. 
As debugging this was difficult, this change was suggested as an immediate fix.
It was initially suggested to use `isAutomaticQuoteSubstitutionEnabled`, however this did not work in testing. The instance method implemented here was linked in the docs for the suggested fix, and in testing, it resolves the issue.
This is an immediate solution for #3546. Leaving the issue open as there was mention of a potential feature to allow the user to enable or disable this feature.
> Disable smart quotes on macOS for MultilineTextInput

- android/src/toga_android/app.py
- changes/3554.bugfix.rst
Referencing the `Build.VERSION_CODES.Q` symbol directly causes crashes when you run on pre-Q versions, as the symbol doesn't exist. Replace the use of the symbol with the numeric equivalent, matching what is done elsewhere in Toga's Android backend.
Fixes #3554.
> Replace symbolic reference to Q with numeric value.

- changes/3570.bugfix.1.rst
- changes/3570.bugfix.2.rst
- changes/3570.feature.1.rst
- core/src/toga/app.py
- core/src/toga/documents.py
- core/tests/app/test_document_app.py
- core/tests/test_fonts.py
- core/tests/test_icons.py
- gtk/src/toga_gtk/app.py
- gtk/src/toga_gtk/dialogs.py
In the process of upgrading Podium, a number of minor issues were identified:
* On macOS, initial document handling didn't work because `startup()` is now guaranteed to run when the app loop has started, preventing `run_until_complete()` from working.
* On GTK, current window handling didn't work if there are no windows. There was logic to handle this case, but it assumed the existence of an `_impl` that won't exist.
* A number of asyncio tests appeared in testing - this is likely due to #3562; not sure why that didn't get picked up by CI there. Some of them may be because once *an* async test has run, an event loop *exists*, so the test passes; it's only if that test is run in isolation that a "no event loop" problem is found.
* On GTK, I've added a file filter for 'all file types'. This …
> Fixes identified by Podium upgrade

- .github/workflows/ci.yml
- changes/3588.misc.rst
We used to use both `min_python_version` and `max_python_version` in the CI configuration, but we don't use the `max` anymore. (I believe it was removed once we started testing on the whole matrix, rather than just the lowest and highest.) `max_python_version` has also never been updated from 3.12 to 3.13. We might as well just remove it, and we can always add it back in if and when we need it for something.
> Remove unused max_python_version env var in ci.yml

- changes/3592.misc.rst
- travertino/src/travertino/colors.py
I saw a thing my brain couldn't parse. Reasonable people adjust to the world, unreasonable people make the world adjust to them, I'm unreasonable, etc. etc.
> Reformat / minimize some color-related math

- changes/2975.misc.rst
- core/src/toga/documents.py
This was broken in #2993. It doesn't appear that any similar breakages happened at the same time.
> Fix `Document.extensions` docstring

- changes/3688.misc.rst
- travertino/src/travertino/colors.py
Fixes an oversight in #3665
It was functionally fine, simply because the order was *consistently* wrong in this section. Not sure how I managed that.
> Fix RGB order

- changes/3658.bugfix.rst
- gtk/src/toga_gtk/widgets/base.py
- gtk/src/toga_gtk/widgets/multilinetextinput.py
- testbed/tests/widgets/test_multilinetextinput.py
This is necessary to make scroll_to_bottom() after text change to work.
Fix #3658
> multilinetextinput: wait until the text change is fully completed on Gtk

- changes/3667.bugfix.rst
- cocoa/src/toga_cocoa/screens.py
- cocoa/src/toga_cocoa/window.py
- testbed/tests/app/test_screens.py
- testbed/tests/window/test_window.py
On macOS, the native screen origin is a the bottom left of the screen. As a result, if you have multiple screens, and those screens are not the same size, or the screens are not vertically aligned, the origin of the non-primary screens (and thus the value of `screen_position`) is incorrect.
This can't be easily tested in testbed because we don't have multiple screens on the testbed environment.
Thanks to @passportjal for the report and prototype fix.
Fixes #3677.
> Correct macOS screen origin calculation.

- changes/3613.feature.rst
- core/src/toga/sources/list_source.py
- examples/table/table/app.py
Fixes #3613
Problems fixed:
- Attempting to restore the Genre column called `add_column`, which no longer works and should be `append_column`.
- Neither clearing nor resetting the data reset the labels showing what's currently selected.
- Resetting the data uncoupled the two tables, so that only the left table would receive further updates.
- The font selection buttons (in addition to not working on most platforms) called into the private `_impl` API; I removed them.
Other changes/improvements:
- I don't think we gain much by having two side-by-side tables, especially when some buttons (like scrolling and deleting the selection) are tied to only one of them. I've cut it to one, which allows multiple selection.
- Maybe it's just me, but I don't think we need the movies repeated a …
> Improve table example

- changes/3686.bugfix.rst
- core/src/toga/app.py
- core/tests/app/test_app.py
When running as a single file under PDB (e.g., `python -m pdb myapp.py`), `app_name` logic fails because `__package__` isn't defined (as opposed to *existing*, but having a value of `None` when run outside PDB). This PR adds a fallback to ensure that if `__package__` doesn't exist on the main module, a fallback to app ID-based logic is still possible.
Thanks to @JustCommitRandomness for the report and draft fix.
Fixes #3686.
> Add handling for the non-existence of __package__ under PDB.

- changes/3693.misc.rst
- docs/reference/api/widgets/table-values.rst
- examples/README.md
If accessors in a tree or table  aren't unique, columns will display duplicated data. While this may be obvious when you understand how the internals work, it's not necessarily obvious from the outside, so a clarification in the docs is called for.
Also adds a clarification about running the examples.
Fixes #3693.
Refs #3692.
> Clarify uniqueness requirement for table/tree accessors.

- changes/3724.misc.rst
- testbed/tests/app/test_desktop.py
This ensures the window don't just flash and the user can visualize the state change in slow mode; in addition, this is required for proper functioning of the still-unofficial Qt backend.
> Add Waits for Window Show and Hide Before Checking for Current

- changes/3735.misc.rst
- winforms/tests_backend/widgets/textinput.py
In TextInput, the method for positioning the cursor to the end in the testing probe is now implemented.
> Implement Winforms Cursor Positioning Probe

- changes/3744.misc.rst
- testbed/src/testbed/app.py
https://docs.python.org/3.13/library/asyncio-eventloop.html#asyncio.loop.set_task_factory
The new specification specifies that we must pass on ALL kwargs, since the older if doesn't error if you pass in context in <3.11 anyways, I assume that extra args is not a concern here, so I simplified the entire if out.
This inconsistency was discovered when using Python 3.13 to run unofficial Qt backend tests on Ubuntu 25.04 container because of missing PySide6 in earlier versions.
> Update Signature of Task Factory
