docs/internals/contributing.rst, docs/internals/platforms.rst, docs/philosophy.rst, docs/tutorial/tutorial-0.rst, setup.py, src/core/README.rst, src/core/toga/__init__.py
And what the (really) high level plan for a test suite would be.
(More documentation PRs! Yay!)
=> Doc updates / Python 2 removal

src/cocoa/toga_cocoa/widgets/selection.py, src/core/toga/interface/widgets/selection.py, src/gtk/toga_gtk/widgets/selection.py
=> Move the adding items into selection's interface

docs/index.rst, docs/internals/contributing.rst, docs/internals/platforms.rst
Small corrections to current documentation, solving issues I came across.
=> General documentation fixes

src/gtk/toga_gtk/widgets/webview.py
Signed-off-by: Francis Gauthier `<francisgauthier1 at gmail dot com>`
=> Get rid of hardcoded version number

src/iOS/toga_iOS/container.py
I followed your lead and updated ios to the new colosseum layout.
=> Migrate ios to new Colosseum layout.

src/core/toga/interface/widgets/button.py, src/winforms/toga_winforms/widgets/button.py
=> Fixed Windows Button enabled error

src/django/toga_django/django/templates/toga/base.html, src/django/toga_django/impl/button.py
This PR contains a partial fix to issue #126. The Button widget is set; the Label and TextInput widgets are yet to be done.
=> Fix widget layout implementations for Django

docs/reference/widgets/optioncontainer.rst
import toga rather than python
=> import toga

docs/tutorial/tutorial-1.rst
=> Correct documentation is best documentation

src/winforms/toga_winforms/dialogs.py
info, question, confirm and error are implemented.
Thanks to @freakboy3742 and @clokep for their help!
=> First cut of dialogs using WinForms backend.

README.rst
(Hopefully) closes #145 
@glasnt, I appear to have broken the heading sizes a bit - does it still look okay to you?
=> Clarify prerequisites in README

src/gtk/toga_gtk/__init__.py, src/winforms/toga_winforms/__init__.py, src/winforms/toga_winforms/widgets/passwordinput.py
Added WinForms implementation and re-enabled the GTK implementation.
=> Working password input widgets for WinForms and GTK

src/winforms/toga_winforms/__init__.py, src/winforms/toga_winforms/command.py, src/winforms/toga_winforms/window.py
I don't expect this to be merged - at the moment it's implemented but for some reason the toolbar (Winforms ToolStrip) doesn't show up on the form itself.
=> RFC: WinForms Command/Toolbar

docs/tutorial/tutorial-2.rst
this should make the icons downloadable
does behave a little different locally to what i would expect from the web.
single click takes me to the file in my file system
right click and select download does nothing
=> Tutorial 2 icons download fix

README.rst
=> Correct name for Debian/Ubuntu webkit package in README

src/winforms/toga_winforms/__init__.py, src/winforms/toga_winforms/libs.py, src/winforms/toga_winforms/widgets/numberinput.py
Mostly working. Having trouble with set_value - how does casting from the CLR to Python and back work?
=> WinForms: NumberInput

src/cocoa/toga_cocoa/widgets/multilinetextinput.py
``self.layout`` from ``Widget`` base class is an instance from ``Layout`` class.
=> Fix error #187 [Core] [Cocoa]

src/cocoa/toga_cocoa/widgets/multilinetextinput.py, src/core/toga/interface/widgets/multilinetextinput.py
This feature was mentioned at #203 . Example code: https://gist.github.com/Dayof/33efe6016ceac410044d469abbb2db3c
=> Clear method to MultilineTextInput widget [Core] [Cocoa]

src/cocoa/toga_cocoa/widgets/splitcontainer.py, src/core/toga/interface/widgets/splitcontainer.py
=> Fix apply style to a SplitContainer [Cocoa]

src/cocoa/toga_cocoa/widgets/multilinetextinput.py, src/core/toga/interface/widgets/multilinetextinput.py
Example code : https://gist.github.com/Dayof/ad86b0d01c9f0e266c3684d2995af0ed
=> Readonly and placeholder for MultilineTextInput widget [Core] [Cocoa]

src/winforms/toga_winforms/__init__.py, src/winforms/toga_winforms/widgets/multilinetextinput.py
Code tested with:
```
import toga
def build(app):
box = toga.Box()
text = toga.MultilineTextInput(initial = 'Hello world',
readonly = True,
)
def button_handler(widget):
print(text.value)
button = toga.Button('Hello world', on_press=button_handler)
button.style.set(margin=50)
box.add(text)
box.add(button)
return box
def main():
return toga.App('First App', 'org.pybee.helloworldmultiline', 
startup=build)
if __name__ == '__main__':
main().main_loop()
```
=> MultilineTextInput for WinForms

src/winforms/toga_winforms/__init__.py, src/winforms/toga_winforms/widgets/table.py
Code to Test:
```
import toga
def build(app):
left_container = toga.Table(['Hello', 'World'])
left_container.insert(None, 'root1', 'value1')
left_container.insert(None, 'root2', 'value2')
left_container.insert(None, 'root3', 'value3')
left_container.insert(1, 'root4', 'value4')
for i in range(0, 100):
left_container.insert(None, 'root%s' % (i+5), 'value%s' % (i+5))
return left_container
def main():
return toga.App('Table Sample App', 'org.pybee.f_to_c', startup=build)
if __name__ == '__main__':
main().main_loop()
```
=> Added toga Winform Table

.gitignore, examples/tutorial2/tutorial/app.py, src/cocoa/toga_cocoa/widgets/table.py, src/core/toga/interface/widgets/table.py
create an on_select callback, and put in a new value selectedRow
update tutorial2, to showcase this new callback :)
I'm new to git/github. I don't know how to hide the gitIgnore commit, you probably don't want that commit.
=> Table widget now has a callback on_select

src/cocoa/toga_cocoa/utils.py
=> Fix for naming issue https://github.com/pybee/toga/issues/226

examples/tutorial2/tutorial/app.py
=> small fix of toga tutorial2

docs/tutorial/tutorial-1.rst, docs/tutorial/tutorial-3.rst
Thanks for the project, it sounds really interesting. I'm going through the tutorials, and I noticed a typo.
=> Fix a typo

src/gtk/toga_gtk/widgets/splitcontainer.py
=> Fix get_allocation() typo

src/core/toga/widgets/icon.py, src/gtk/toga_gtk/widgets/base.py, src/gtk/toga_gtk/widgets/icon.py
Fixes two Attribute Errors I was getting when trying to run tutorial 2. May also fix issue #71.
=> Fix Tutorial 2 for GTK+

src/gtk/toga_gtk/app.py
Signed-off-by: Ratan Kulshreshtha <ratan.shreshtha@gmail.com>
=> Added gi_system_install_path for Fedora.

src/dummy/toga_dummy/container.py
=> updated dummy-backend for container

src/core/tests/widgets/test_webview.py
First PR for toga so just added some (fairly trivial) unit tests to bring coverage of webview up to 100% and get a feel for the project.
=> Test get/set user agent, get dom and evaluate method for webview

docs/tutorial/source/tutorial-4.py, examples/tutorial4/tutorial/app.py, src/gtk/toga_gtk/widgets/canvas.py
=> Implement quadratic_curve_to for GTK+

src/core/tests/test_command.py
Added a few tests for the Group class in toga.command
=> Added tests for toga.command.Group

src/gtk/toga_gtk/widgets/table.py
Apply same fix from #290 to GTK+ Table.
=> Fix GTK+ Table row selection

docs/how-to/contribute.rst
Also added a list of advanced contribution topics.
=> Added a description of factory usage.

src/core/tests/test_command.py, src/core/toga/command.py
Added partial testing for toga.CommandSet
=> Increased toga.command test coverage

.github/issue_template.md, .github/pull_request_template.md, README.rst
=> Add issue/PR templates, link to Toga contrib/setup docs

README.rst
Fixes https://github.com/pybee/toga/issues/329
=> Fixes formatting error in README file

src/core/tests/sources/test_tree_source.py
Resolves one line of test coverage in Tree_Source
=> Added a test for children on the leaf node

docs/how-to/contribute.rst
=> Added Windows instructions to the How To Contribute guide.

docs/how-to/contribute.rst, src/core/tests/test_window.py, src/core/tests/widgets/test_box.py, src/core/tests/widgets/test_image.py, src/core/tests/widgets/test_multilinetextinput.py, src/core/tests/widgets/test_numberinput.py, src/core/tests/widgets/test_passwordinput.py, src/core/tests/widgets/test_progressbar.py, src/core/tests/widgets/test_selection.py, src/core/tests/widgets/test_textinput.py
I have tried to add some tests for the following widgets: 
- box
- multilinetextinput
- numberinput
- passwordinput
- progressbar
- selection
- textinput
Also, I added a line missing from the instructions for Windows contributors. 
How should I document?
=> Widget tests updated

src/iOS/toga_iOS/widgets/button.py
Only import needed objects from toga_iOS.libs
=> Refined import

.github/issue_template.md
Rename OS X to macOS, remove Ubuntu since it is a distro of Linux, add to format to include distro name for Linux, and add to format to include versions.
=> Update operating system choices in issue template

src/core/toga/widgets/icon.py
fixes https://github.com/pybee/toga/issues/347
=> Removed redifinition of method 'filename'

src/gtk/toga_gtk/widgets/textinput.py
Fixes https://github.com/pybee/toga/issues/349
=> Fixes input text field readonly issue on Ubuntu

src/iOS/toga_iOS/app.py, src/iOS/toga_iOS/widgets/button.py, src/iOS/toga_iOS/widgets/detailedlist.py, src/iOS/toga_iOS/widgets/image.py, src/iOS/toga_iOS/widgets/imageview.py, src/iOS/toga_iOS/widgets/label.py, src/iOS/toga_iOS/widgets/navigationview.py, src/iOS/toga_iOS/widgets/numberinput.py, src/iOS/toga_iOS/widgets/selection.py, src/iOS/toga_iOS/widgets/slider.py, src/iOS/toga_iOS/widgets/switch.py, src/iOS/toga_iOS/widgets/webview.py
=> refine toga_iOS.libs imports to only include needed imports

src/winforms/toga_winforms/app.py, src/winforms/toga_winforms/color.py, src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/libs.py, src/winforms/toga_winforms/widgets/button.py, src/winforms/toga_winforms/widgets/numberinput.py, src/winforms/toga_winforms/window.py
I added some winforms changes to button widget, window widget and added winforms color.py file.
At this point the button example works, buttons can have background colors, window can be resized. This is how button example now in winforms:
=> Added details to button widget on winforms

src/core/tests/widgets/test_icon.py
Added a test case for the bind method of the Icon widget interface. It increases the test coverage by 4 lines.
=> Added test case for Icon.bind method

src/iOS/toga_iOS/app.py
I believe these are the missing imports @maranas was talking about when trying to build an iOS application.
=> Added missing imports to app.py

src/core/tests/widgets/test_detailedlist.py, src/core/toga/widgets/detailedlist.py
I've added a test case for detailedlist.py to test on the data setter and getter methods. Since I have not written any unit test before and unit testing was new to me so kindly point me to the right direction if I'm in the wrong path. Thanks 😃
=> Added test_detailedlist_property case

src/android/toga_android/widgets/passwordinput.py
=> added PasswordInput widget for android, to be tested

src/core/tests/test_font.py, src/core/toga/font.py
Fixed `__init__` method of `toga.font`
Added tests for changes
Fixed indentation of previous tests
Required fix for #397
=> Fixed bug in toga's font interface

src/cocoa/toga_cocoa/widgets/imageview.py, src/iOS/toga_iOS/libs/uikit.py, src/iOS/toga_iOS/widgets/base.py, src/iOS/toga_iOS/window.py
* Corrects ImageView size hinting on macOS
* Accounts for the status bar on iOS layouts.
=> Miscellaneous corrections and improvements

src/core/toga/__init__.py
Fixed typo leading to missing import with `import *`.
=> Fix import symbol list of __all__

docs/background/roadmap.rst
Updates Roadmap. Doesn't conflict with master. Previously in PR #425
=> Updated and formatted roadmap.rst

docs/tutorial/tutorial-0.rst
=> Typo fix in tutorial

src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/libs.py, src/winforms/toga_winforms/widgets/image.py, src/winforms/toga_winforms/widgets/imageview.py
I added image and imageview implementation for winforms, testing it using the imageview app in the examples. The images show, but alignment and scaling don't work yet. There is also a border on imageview for testing purposes.
=> Added image and imageview implementation for winforms

docs/background/roadmap.rst
Updated Toga roadmap: removed all widgets that are implemented in core and some of the backends. Added possible Winforms implementations.
=> Update Toga roadmap

src/dummy/toga_dummy/command.py
Added `__init__.py` method to `command.py` in dummy backend to help testing for binding.
It was impossible to test command.bind method without initializing dummy command.
=> Update dummy command.py to improve bind testing

docs/background/architecture.rst, docs/background/index.rst, docs/background/layout.rst, docs/background/philosophy.rst, docs/reference/platforms.rst
Added documentation on the broad architecture of Toga, and the widget layout process.
=> Architecture docs

src/core/tests/test_command.py
=> Increase the coverage

src/core/tests/test_command.py
=> remove the unused line

docs/how-to/contribute.rst
Found some minor typos in the documentation
Makes the Toga contribute document better
No
- [ x] All new features have been tested
=> Fix minor typos in contribute.rst

docs/tutorial/tutorial-2.rst
I added changes to describe where the icon folder should go in the local directory
It clarifies the tutorial for new people.   I would recommend being clearer for extremely new people.
=> Tutorial2 update

src/core/tests/test_command.py
=> Increase test coverage

src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/widgets/tree.py
=> Stubbed Tree in Winforms.widgets with not_implemented.

src/core/tests/widgets/test_tree.py
=> Add test for data setter with dict

docs/tutorial/tutorial-0.rst, docs/tutorial/tutorial-1.rst, docs/tutorial/tutorial-2.rst, docs/tutorial/tutorial-3.rst, docs/tutorial/tutorial-4.rst, docs/tutorial/tutorial-issues-note.rst
Provide some information related to wrapped handler and windows loop as expected current behavior.
Executing a wrapped handler in windows causes the app to crash.
It provides some additional details in the troubleshooting section.
=> Troubleshooting Windows Crash Tut1

src/core/tests/test_window.py
I went through the contribution guide and improved some coverage of the window tests using mocking.
=> add more window tests

src/core/tests/widgets/test_base.py, src/core/toga/widgets/base.py
=> Add multiple children

docs/background/index.rst, docs/background/success.rst
=> Add a success stories page.

src/core/setup.py
=> Include the .ico file for Tiberius

src/winforms/toga_winforms/factory.py
With this in place, winforms can actually run the demo, although the tree widget is blank.
=> Import tree widget

src/django/package.json
https://nvd.nist.gov/vuln/detail/ CVE-2018-14042
=> Upgrade boostrap to mitigate CVE-2018-14042

src/core/toga/icons.py, src/winforms/toga_winforms/colors.py, src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/icons.py, src/winforms/toga_winforms/widgets/button.py
Corrected imports and paths related to recent code reorganisations
=> Winforms fix paths

src/core/tests/widgets/test_progressbar.py, src/core/toga/widgets/progressbar.py
I am Khaled Alqenaei from DjangoCon sprint and I improved the test cases coverage to be 100% for the progress bar widget.
=> Making the progress bar widget coverage to be 100%

src/core/tests/widgets/test_canvas.py
I added 3 test cases to test colorless strokes and fills and now the coverage is 100%.
=> Making the canvas coverage to be 100%

src/core/tests/widgets/test_datepicker.py, src/core/toga/__init__.py, src/core/toga/widgets/datepicker.py, src/dummy/toga_dummy/factory.py, src/dummy/toga_dummy/widgets/datepicker.py, src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/libs.py, src/winforms/toga_winforms/widgets/datepicker.py
This PR implements a Date picking widget on windows. There are a few different options which can be added on but for now just implementing the basic functionality. 
This is my first open source contribution ever so let me know of any feedback!.
=> Add windows DatePicker Widget

docs/reference/api/widgets/table.rst
Table widget refrenced nonexistent methods on the table widget and
called include(None) instead of append. This has been corrected the
example is now working code.
=> Corrects example in Table widget documentation

docs/tutorial/tutorial-0.rst
At the moment you cannot install toga with python3.7 from pypi, so I included a workaround that worked for me.
=> Temporary update for python3.7

README.rst
=> Fix logo link for new site domain

README.rst
=> Update beeware shield link

docs/reference/api/index.rst, docs/reference/api/resources/fonts.rst, docs/reference/api/resources/icons.rst, docs/reference/api/resources/images.rst, docs/reference/api/resources/index.rst
=> Fixes for documentation markup.

src/core/tests/test_documents.py
=> Adding coverage to documents.py. First contribution to toga! :)

src/core/tests/test_app.py
Improved the coverage for test_app.py in toga.
Test contents:
1. Test set_full_screen and exit_full_screen
2. Test set_full_screen for both triggering and exiting
=> Add full screen tests for test_app.py

.gitignore
Introduce Pipenv and Pipenv.lock to .gitignore
Extremely trivial, but some people prefer to use Pipenv to manage dependencies. This is just another nice-to-have in the development process.
N.A
=> Add Pipfile to gitignore

src/core/tests/widgets/test_table.py
Added test_multiple_select function to test_table.
=> Test read only multiple select property on Table Widget

docs/tutorial/tutorial-0.rst
Better fix for the Windows pythonnet.whl command.
Added a paragraph highlighting differences between calling this as a module vs running a typical script.
A few minor text edits.
The main impact is reducing the chance that someone (like me!) runs the script without realizing the need to treat it as a module, which results on macOS in an AttributeError.
=> Tutorial 0 edits

src/curses/README.rst
Signed-off-by: Nehar Arora <gh@nehar.net>
Replaces some leftover pybee references with beeware.
=> remove some pybee references

src/core/toga/widgets/table.py
=> fix typo in comment

src/gtk/toga_gtk/widgets/button.py
You are now able to enable and disable buttons in GTK.
=> Implement GTK button.enabled

docs/tutorial/tutorial-0.rst
=> Remove extraneous parenthesis

src/core/tests/widgets/test_optioncontainer.py, src/dummy/toga_dummy/utils.py
Added test function for refresh_sublayout
increases test coverage
=> Added test code for optioncontainer.py being test_refresh_sublayer

src/cocoa/toga_cocoa/app.py
Corrects the call to hide the cursor.
=> Correct call to hide cursor.

docs/tutorial/tutorial-0.rst
Improved the documentation for getting the tutorial going under Linux.
=> Improved the tutorial 0 installation docs.

src/winforms/toga_winforms/app.py
Adds error handlers for exceptions in Winforms.
Uncaught exceptions are raised to the user with a Window system dialog box. This isn't very convenient, and the error message masks the underlying source of the error.
This adds a try-catch block around the run method for the app, and installs an exception handler that can provide a more helpful traceback.
=> Add exception handling for main winforms event loop.

demo/README.rst
Remove repeated information in demo README, along with broken links to the archived toga-demo repo.
=> Update demo README

docs/how-to/contribute.rst, docs/tutorial/tutorial-0.rst
Add packages to install for Debian 10
=> Debian 10 install docs

src/android/toga_android/app.py, src/cocoa/toga_cocoa/app.py, src/core/toga/app.py, src/django/toga_django/app.py, src/dummy/toga_dummy/app.py, src/gtk/toga_gtk/app.py, src/iOS/toga_iOS/app.py, src/win32/toga_win32/app.py, src/winforms/toga_winforms/app.py
Toga apps needed a background task interface. Now we have one!
This PR also includes some import sorting, because VS Code. If we care deeply, I will fix.
=> Add a background task interface for Toga

docs/how-to/contribute.rst
Simplifies the installation instructions, collapsing two code blocks into one.
=> Simplify installation instructions.

src/django/package.json, src/django/setup.py
Apply recommended security updates.
These almost certianly don't work, but then, neither does the rest of the Django backend at the moment... 😢
=> Apply recommended security updates.

src/core/tests/test_window.py
First time contributor here : )
This PR adds tests for the close(), question_dialog(), confirm_dialog() and error_dialog() methods.
It increases the code coverage from 90% to 92% for `window.py`
=> Added tests for close(), question_dialog(), confirm_dialog() and error_dialog()

docs/reference/style/pack.rst
=> Fix simple typo: simliar -> similar

docs/reference/api/containers/box.rst
Thanks to @BrendanSimon for the report.
Corrected the documentation related to the use of styles on Box.
=> Fixes #761 - Corrected style-related documentation.

src/iOS/toga_iOS/icons.py
=> Added missing attributes on iOS Icon.

src/cocoa/toga_cocoa/libs/appkit.py, src/cocoa/toga_cocoa/widgets/imageview.py
Fixed enumeration values for NSImageAlignment in `toga_cocoa.lib`.
=> fix NSImageAlignment enumeration values

.github/workflows/build_status.yml, .github/workflows/ci.yml
We're seeing CI failures on Windows; this is an attempt to fix those problems.
=> Tweak CI configuration around pip and setuptools installs

examples/tree_source/tree_source/app.py, src/cocoa/toga_cocoa/widgets/internal/cells.py, src/core/toga/widgets/base.py, src/core/toga/widgets/optioncontainer.py, src/core/toga/widgets/scrollcontainer.py, src/core/toga/widgets/splitcontainer.py, src/gtk/toga_gtk/widgets/tree.py
Makes some miscellaneous fixes to test and demo apps.
* Ensures the Tree demo works on GTK
* Only attempts to handle content on widgets that have content (and handles that content in a way appropriate for the widget)
* Corrects some missing imports.
=> Fixes #806 - Miscellaneous fixes for demo and test apps

src/cocoa/toga_cocoa/widgets/internal/cells.py
Signed-off-by: Ignacio Cabeza <ignaciocabeza@gmail.com>
This is a small fix for #700. I used the recommendation mention in: https://stackoverflow.com/questions/7076317/multiline-text-wordwrap-with-drawatpoint
=> Fix cell rendering to avoid overflow of text

examples/box/README.rst, examples/box/box/__init__.py, examples/box/box/__main__.py, examples/box/box/app.py, examples/box/pyproject.toml, src/cocoa/toga_cocoa/colors.py, src/winforms/toga_winforms/colors.py, src/winforms/toga_winforms/widgets/box.py, src/winforms/toga_winforms/widgets/button.py
Added the ability to set Box background color in winforms
- [V ] All new features have been tested
- [ X] All new features have been documented
- [V ] I have read the **CONTRIBUTING.md** file
- [ V] I will abide by the code of conduct
=> Add background color to Box in windows

src/winforms/toga_winforms/widgets/table.py
fixes #842
Table example hasn't been working for windows. fixed that.
- [V ] All new features have been tested
- [V ] I have read the **CONTRIBUTING.md** file
- [ V] I will abide by the code of conduct
=> Fix bug in Table for windows

examples/selection/selection/app.py, src/winforms/toga_winforms/widgets/selection.py
fixes #854
Fixed the bug described in the linked issue.
=> Fix bug in Selection in windows

src/core/tests/test_app.py
I tried to improive the tests suggested in the pull request #631 for is_full_window.
Now a list of windows is tested (represented by strings) and if no windows are passed as arguments for set_full_screen() is tested.
PS:
i did a first pull request with the same mistakes, i did not checked befor. I am sorry for this wast of your time. I hope you will forgive my beginer mistake.
=> Improvement to the tests suggested in pull request 631

examples/progressbar/progressbar/app.py, src/winforms/toga_winforms/widgets/progressbar.py
Changed value and max in the example to integers in order to support windows
Fixes #504
=> Fixed progressbar for Windows platform.

src/core/tests/test_image.py, src/core/toga/app.py
Fixes #862 test_image cannot pass when no previous test created an App
=> Fix image test

examples/canvas/canvas/app.py
* fill/unfill shapes
* show traingle/ellipse
=> Canvas example now includes more options

examples/canvas/canvas/app.py
This is done in order to show all the different abilities of the `Canvas` widget
=> More canvas examples

src/winforms/toga_winforms/widgets/canvas.py
This solves a bug with rendering text with stroke in windows:
(This didn't work before this fix)
=> Windows Canvas should always use GraphicsPath

src/android/toga_android/factory.py, src/android/toga_android/libs/android_widgets.py, src/android/toga_android/widgets/base.py, src/android/toga_android/widgets/numberinput.py, src/android/toga_android/widgets/selection.py
This PR, along with the other ones I have in queue, all together, allows TravelTips to launch. Here's what it looks like.
I'm having some trouble using the app. I don't know if it's an app bug, or a Toga bug. :( Maybe we can discuss.
=> Add NumberInput and Selection widgets

examples/canvas/canvas/app.py, src/gtk/toga_gtk/widgets/slider.py, src/winforms/toga_winforms/libs/__init__.py, src/winforms/toga_winforms/libs/winforms.py, src/winforms/toga_winforms/widgets/canvas.py
Finally, Windows has all the `Canvas` main features!
=> Implement windows canvas translate, rotate and scale

src/winforms/toga_winforms/widgets/canvas.py
When trying to write multiline text in `Canvas` in *Windows*, The size of the text is miscalculated
1. Open the `Canvas` example in *Windows*
2. See that the instructions text is too bug
=> Fix bug in measuring multiline text in Windows Canvas

src/winforms/toga_winforms/widgets/canvas.py
I implemented the mouse events in `Canvas` for windows.
The `Canvas` example is working now completely!
=> Canvas mouse events in windows

src/core/tests/widgets/test_tree.py
=> coverage: line 74 of tree.py file, creates tree with TreeSource data

docs/tutorial/tutorial-0.rst
Updated Official Documentation with Note for Windows Installation issue with python 3.8
Clarification in Installation
#903 
- [ x] All new features have been tested
=> Docs update

src/winforms/toga_winforms/libs/proactor.py
Python 3.8 made a small change to the asyncio event loop, altering where the initial call to stage `_loop_self_reading` occurs. This caused apps to lock up, as there wasn't anything in the proactor queue when the first call to select() was made.
This wasn't detected until recently because Python.NET didn't release a Python 3.8 compatible version until mid June.
=> Fixes the Winforms event loop under Python3.8.

README.rst
Aligns Linux installation instructions with the BeeWare tutorial.
=> Aligned Linux install instructions with BeeWare tutorial.

docs/reference/api/widgets/activityindicator.rst, docs/reference/data/widgets_by_platform.csv, src/gtk/toga_gtk/factory.py, src/gtk/toga_gtk/widgets/activityindicator.py
This PR adds a Gtk implementation of ActivityIndicator (Gtk.Spinner).
=> Add a Gtk implementation of ActivityIndicator

src/core/toga/style/applicator.py, src/core/toga/widgets/base.py
Fix to problem #176.
Fix:
Bug:
=> Resize Widget when Text Size is Changed

src/core/toga/widgets/table.py
=> Don't have Table warn on the empty string as a missing_value

docs/tutorial/tutorial-0.rst
=> Drop the warning about Python 3.8 not working on Windows

examples/tutorial3/tutorial/app.py
=> Have tutorial 3 point at pybee.org by default

docs/reference/data/widgets_by_platform.csv
@nicolaivds came to Gitter to find out why his Android WebView wasn't working. This is a minimal docs fix to explain the current status.
=> Update Android WebView status in docs

src/winforms/toga_winforms/widgets/webview.py
Under Windows, WebView.set_content() did not work as documented
This PR fixes this problem
=> Fix for the not correctly working set_content method.

docs/how-to/contribute.rst
Update dependencies on this page, in line with the Readme.
=> Update dependencies for Ubuntu 20.04

src/core/toga/widgets/table.py
changed the table.py docstring so it is rendered correctly in the docs
#992
=> added empty line between text and code blocks for correct rendering

src/winforms/toga_winforms/window.py
=> Added filetypes filter to save_file_dialog

examples/box/box/app.py, src/winforms/toga_winforms/widgets/base.py
A first implementation of the `insert_child` method in Winforms.
Added a simple usage example in the *Box* example. If you think it deserves a separate example, let me know.
=> Implement insert child in index in Windows platform

src/winforms/toga_winforms/app.py, src/winforms/toga_winforms/keys.py
=> Add the ability of toga.Commands to use shortcuts in Windows

src/winforms/toga_winforms/app.py, src/winforms/toga_winforms/window.py
When opening a new window in Winforms, it doesn't have an icon as in the main window. Fixed that.
=> All windows should have icon in Winform

docs/background/architecture.rst
Enhancing architecture section in the toga documentation.
=> Enhancing architecture section in the toga documentation.

examples/focus/README.rst, examples/focus/focus/__init__.py, examples/focus/focus/__main__.py, examples/focus/focus/app.py, examples/focus/pyproject.toml, src/android/toga_android/widgets/base.py, src/cocoa/toga_cocoa/widgets/base.py, src/core/tests/widgets/test_button.py, src/core/tests/widgets/test_datepicker.py, src/core/tests/widgets/test_numberinput.py, src/core/tests/widgets/test_passwordinput.py, src/core/tests/widgets/test_selection.py, src/core/tests/widgets/test_slider.py, src/core/tests/widgets/test_switch.py, src/core/tests/widgets/test_textinput.py, src/core/tests/widgets/test_timepicker.py, src/core/toga/widgets/base.py, src/dummy/toga_dummy/widgets/base.py, src/gtk/toga_gtk/widgets/base.py, src/iOS/toga_iOS/widgets/base.py, src/web/toga_web/widgets/base.py, src/winforms/toga_winforms/widgets/base.py
Implement programmatic focus change in Winform
=> Support change focus in Winform and Mac

docs/reference/data/widgets_by_platform.csv, src/core/toga/widgets/divider.py, src/gtk/toga_gtk/factory.py, src/gtk/toga_gtk/widgets/divider.py
This PR implements the Divider widget for the Gtk backend.
=> Implement Divider for Gtk backend

docs/background/success.rst
Add *Eddington* to success stories.
=> Add Eddington to success stories.

src/android/toga_android/widgets/selection.py
=> fixed incorrect class reference

src/core/toga/widgets/scrollcontainer.py, src/gtk/toga_gtk/widgets/scrollcontainer.py
This PR fix the issue of the horizontal scrolled window
=> Fix horizontal scrollbar

src/winforms/toga_winforms/window.py
=> Fix bug selecting multiple files in Winforms open_file_dialog

README.rst
=> Add Codecov badge to README.rst

.gitignore, src/winforms/toga_winforms/libs/proactor.py
Fixed a memory leak in windows implementation
FIxes #1108 
Before fix:
After fix:
=> Fix windows memory leak

examples/examples_overview/examples_overview/app.py
This PR replaces the ugly path traversal in `example_overview` with a more elegant pathlib solution.
=> Replace ugly path traversal in `example_overview`

docs/reference/style/pack.rst
=> Remove doubled word "value value" from pack.rst

src/core/tests/widgets/test_base.py
Increases core/toga/widgets/base.py test coverage from 72 to 79%.
If this is on the right track I will add tests for the base widget's insert method next.
=> Adds tests for the base widget's remove method

src/winforms/toga_winforms/window.py
Fixed a bug in Windows question dialog.
=> Fix bug in windows question dialog

src/core/tests/widgets/test_base.py
Increases core/toga/widgets/base.py test coverage from 79 to 88%.
=> Adds tests for the base widget's insert and add methods

docs/reference/data/widgets_by_platform.csv
Updates the Android widget compatibility chart to reflect current status.
=> Update Android widget compatibility.

examples/layout/layout/app.py, src/gtk/toga_gtk/widgets/base.py
=> Add implementation of set_hidden to GTK backend.

src/cocoa/toga_cocoa/widgets/webview.py, src/gtk/toga_gtk/widgets/webview.py, src/iOS/toga_iOS/widgets/webview.py
=> GTK WebView.set_user_agent

docs/reference/api/resources/images.rst
=> Fixed rST for numbered list

examples/button/button/app.py, examples/switch_demo/switch_demo/app.py, src/android/toga_android/widgets/button.py, src/android/toga_android/widgets/switch.py
This PR implements setting fonts for the `Button` and `Switch` in Android
=> Implement setting font in Android for Button and Switch

.github/workflows/ci.yml, setup.cfg, src/android/setup.cfg, src/cocoa/setup.cfg, src/core/setup.cfg, src/django/setup.cfg, src/dummy/setup.cfg, src/flask/setup.cfg, src/gtk/setup.cfg, src/iOS/setup.cfg, src/web/setup.cfg, src/winforms/setup.cfg, tox.ini
Finally, dropping support for Python 3.5, as discussed in #1199
=> Drop python 3.5 support

src/gtk/toga_gtk/widgets/label.py
Resolves `DeprecationWarning: Gtk.Misc.set_alignment is deprecated`
Refs #1167
=> Gtk.Label Alignment

src/winforms/toga_winforms/widgets/table.py
This PR fixes issue #1130 (incorrect table display on scrolling on Windows)
=> Fix for the incorrect scrolling of Table on Windows (Toga issue #1130)

docs/reference/style/pack.rst
=> pack.rst: Fix typos

README.rst, docs/index.rst, docs/reference/platforms.rst, nursery/curses/README.rst, nursery/falcon/README.rst, nursery/pyramid/README.rst, nursery/qt/README.rst, nursery/starlette/README.rst, nursery/tornado/README.rst, nursery/tvOS/README.rst, nursery/uwp/README.rst, nursery/watchOS/README.rst, src/android/README.rst, src/cocoa/README.rst, src/core/README.rst, src/django/README.rst, src/dummy/README.rst, src/flask/README.rst, src/gtk/README.rst, src/iOS/README.rst, src/web/README.rst, src/winforms/README.rst
* Replaces references to Gitter with Discord
* Adds references to Github Discussions
=> Replace references to Gitter with Discord

examples/multilinetextinput/multilinetextinput/app.py, src/winforms/toga_winforms/widgets/multilinetextinput.py
This PR implements the set_font() method in MultilineTextInput on Winforms
=> Implement set_font() for MultilineTextInput on Winforms

src/gtk/toga_gtk/widgets/webview.py
This PR will remove unused widget `Gtk.ScrolledWindow`. The scrolling ability is already provided by `WebKit2` widget.
=> Webview enhancement

src/core/toga/widgets/detailedlist.py
In response to discord chat
updated comments explaining data type required to update DetailedList data param/attr
prevent further issues and questions when figuring out how to implement DetailedList
=> update docstrings explaining type and key requirements for data param/attr

src/cocoa/toga_cocoa/libs/appkit.py
Signed-off-by: layday <layday@protonmail.com>
=> cocoa: fix platform architecture check

docs/how-to/contribute.rst
A very small change for correct grammar.
Changed "and" to "an"
Just a micro typo. In the context of the sentence, the author was describing a single object - an "error" that one might see.
n/a
=> Microscopic grammar correction

docs/reference/data/widgets_by_platform.csv
Adds DateInput and TimeInput to the compatibility tables.
=> Add missing Date/Time inputs to compat tables.

src/winforms/toga_winforms/keys.py
Added fixes for Python.net 3.0 compatibility.
=> Python.net 3.0 compatibilty fix.

.github/workflows/ci.yml, src/winforms/toga_winforms/widgets/multilinetextinput.py
This PR fixes following problems with the placeholder in MultilineTextInput on Winforms:
* endless recursion on clear() with placeholder=None
* get_value() returned the placeholder when placeholder was shown
* placeholder was not shown on app start
=> Fix for placeholder problems in MultilineTextInput on Winforms

src/android/toga_android/widgets/canvas.py
Testing done
With this sample app -- https://github.com/paulproteus/toganvas/blob/ff76c50d768461237f4bcdfea88cc7622d77dc2a/toganvas/src/toganvas/app.py#L135
macOS:
Android:
=> Implement rotate on Android Canvas

src/android/toga_android/widgets/canvas.py
Sample code: https://github.com/paulproteus/toganvas/blob/b0e19abff98578987e05971650aea8ee540a80e3/toganvas/src/toganvas/app.py#L177
macOS screenshot:
Android screenshot:
=> Implement translate on Android canvas

src/android/toga_android/widgets/canvas.py
Today, I set out to implement `fill`. In the process, I noticed two problems:
* The `arc` implementation would not get filled, merely stroked.
* The lifecycle of an Android `Path` didn't make much sense.
I fixed all these problems with the following changes:
* Use `canvas=` and `path=` keyword arguments everywhere in Android Canvas. In Core Graphics, the path currently being-drawn is state on the "drawing context"; to mimic that on Android, we now create a `Path()` object that we mutate until it gets painted onto the Canvas. In Core Graphics, the path is cleared when it is drawn; to mimic that on Android, we now reset the Path when we draw. This allows us to remove two strange calls to `self.moveTo` which only existed to ensure there was a `Path`.
* I changed the Android `arc` to use …
=> Android Canvas: Add fill; change lifecycle of Path; fix arc bug

README.rst, docs/reference/platforms.rst
Clarified the Python version requirements for Windows.
=> Clarified the requirements on Windows.

src/gtk/toga_gtk/widgets/base.py
=> [Gtk] add support of focus() on widgets

src/android/toga_android/widgets/base.py
=> [Android] add support of focus() on widgets

src/android/toga_android/widgets/base.py, src/android/toga_android/widgets/box.py
This PR implements Widget.remove_child() for Android.
There is a demo app to test this PR:
https://bitbucket.org/TomArn/demoapp.git
Branch: remove_widget
=> Implemented Widget.remove_child() for Android

examples/table/table/app.py, src/android/toga_android/widgets/table.py, src/core/toga/widgets/table.py, src/winforms/toga_winforms/widgets/table.py
This PR allows us to apply font settings to Table on Winforms and Android
It also fixes the problem that the table example did not work on Android anymore.
=> Table.set_font for Android and Winforms

.github/workflows/ci.yml, README.rst, demo/setup.cfg, docs/index.rst, docs/tutorial/tutorial-0.rst, nursery/curses/setup.cfg, nursery/falcon/setup.cfg, nursery/pyramid/setup.cfg, nursery/qt/setup.cfg, nursery/starlette/setup.cfg, nursery/tornado/setup.cfg, nursery/tvOS/setup.cfg, nursery/uwp/setup.cfg, nursery/watchOS/setup.cfg, setup.cfg, src/android/setup.cfg, src/cocoa/setup.cfg, src/core/setup.cfg, src/django/setup.cfg, src/dummy/setup.cfg, src/flask/setup.cfg, src/gtk/setup.cfg, src/iOS/setup.cfg, src/web/setup.cfg, src/winforms/setup.cfg
Deprecates support for Python 3.6.
=> Fixes #1376 - Deprecate Python 3.6

docs/how-to/contribute.rst
=> docs: add link to talk by Dan Yeaw to contribute.rst

.github/workflows/ci.yml, src/iOS/toga_iOS/widgets/multilinetextinput.py
This PR fixes the multilinetextinput example on iOS
=> Fix for multilinetextinput example on iOS

docs/tutorial/tutorial-0.rst
The tutorial recommended the use of a base `pip install`, which can cause hilarity on some platforms.
=> Recommend the use of python -m pip in the tutorial

src/winforms/toga_winforms/window.py
Resizeable argument was having no impact on MainWindow whether set True or False. This allows for fixed window on MainWindow creation. Also, I disabled Maximizebox if resizeable set to false.
=> [WinForms] Window resizeable argument change

examples/tutorial0/tutorial/app.py
Restores the tutorial example code to a state consistent with the example text.
=> Fixes #1453 - Remove some code not required in the initial tutorial.

src/winforms/toga_winforms/dialogs.py
=> Revert "Fix select folder dialog on Windows"

src/android/toga_android/window.py
This PR implements window.get_title() and window.set_title() for Android
The PR can be tested with the Toga 'window' example
=> implementation of window.get_title() and window.set_title() for Android

examples/dialogs/dialogs/app.py, src/winforms/toga_winforms/dialogs.py
Adds a Winforms stack trace dialog. Also adds a test case to exercise the retry version of the dialog.
=> Add a Winforms stack trace dialog

examples/colors/README.rst, examples/colors/colors/__init__.py, examples/colors/colors/__main__.py, examples/colors/colors/app.py, examples/colors/colors/resources/README, examples/colors/pyproject.toml, src/winforms/toga_winforms/widgets/multilinetextinput.py
Adding background and foreground color support to multilinetextinput.
This makes it possible to change colors. Only color that is still fixed is the placeholder text color (SystemColors.GrayText). Tried to make placeholder text transparent, but this is not supported by winforms.richtextbox.
=> Windows - Adding background and for color to mulititextinput

src/winforms/toga_winforms/widgets/canvas.py
This is a continuation of the fixes made in #1558 in order to solve beeware/toga-chart#16.
Fixes #1559
=> Fix canvas winform implementation with `np.float64`

src/winforms/toga_winforms/factory.py, src/winforms/toga_winforms/widgets/detailedlist.py
Finally I got the time handling this, so now we have `DetailedList` in winforms 😃:
=> Implemented detailed list in winforms

examples/table/table/app.py, src/winforms/toga_winforms/widgets/table.py
2 things done in this PR:
1. First, winforms now supports double clicks on Table
2. Fixed bug with table multiselect in winforms
=> Winforms table on double click

src/core/toga/widgets/multilinetextinput.py
This PR fixes the documentation of MultilineTextInput
=> Fixed MultilineTextInput documentation

src/android/toga_android/widgets/scrollcontainer.py, src/android/toga_android/window.py
Uses the approach described at https://github.com/beeware/toga/issues/1624#issuecomment-1282276953.
Tested with:
* The app in #1624
* The app in #1604 
* examples/layout
* examples/scrollcontainer
=> Android: refresh content layout when container size changes

.pre-commit-config.yaml, changes/1663.misc.rst
=> Bump pyupgrade from 2.38.2 to 3.2.0 and black from 22.8.0 to 22.10.0

.github/workflows/ci.yml, android/setup.cfg, android/tox.ini, changes/1677.feature.rst, cocoa/setup.cfg, cocoa/tox.ini, core/setup.cfg, core/tox.ini, demo/setup.cfg, dummy/setup.cfg, gtk/setup.cfg, gtk/tox.ini, iOS/setup.cfg, iOS/tox.ini, toga/setup.cfg, tox.ini, web/setup.cfg, web/tox.ini, winforms/setup.cfg, winforms/tox.ini
With the release of 3.12.0a1, we can start testing for 3.12 support.
=> Add Py3.12 support.

android/src/toga_android/widgets/base.py, changes/1686.feature.rst, cocoa/src/toga_cocoa/widgets/base.py, core/src/toga/widgets/base.py, core/tests/widgets/test_base.py, dummy/src/toga_dummy/widgets/base.py, examples/focus/focus/app.py, gtk/src/toga_gtk/widgets/base.py, iOS/src/toga_iOS/widgets/base.py, web/src/toga_web/widgets/base.py, winforms/src/toga_winforms/widgets/base.py
Fixes #1650
Now one can control the tab index order via code. In this PR I implemented it only for windows.
The decision for the API syntax is explained in the linked issue.
=> Add tab index

changes/1725.bugfix.rst, gtk/src/toga_gtk/app.py, gtk/src/toga_gtk/dialogs.py
Refs #1718 
It fixes the warnings that are caused due to python 3.11
=> Modifiled event loop

README.rst, changes/1726.doc.rst
Correct link for `guide for first time contributors`
=> Update README.rst: Correct link

changes/1741.misc.rst, docs/background/success.rst
This PR adds some Toga based apps to the success stories
=> Added some success stories

changes/1743.misc.rst, docs/reference/platforms.rst
This PR just fix the references to the stale branch `master`.
There are failing references to some links and this PR fixes them.
=> Update stale branch references in the project

.github/workflows/pre-commit-update.yml, changes/1764.misc.rst
=> Add GitHub workflow to keep `pre-commit` hooks up-to-date

.readthedocs.yaml, changes/1777.misc.rst
Note: PDFs not built for PRs; only built on default branch.
=> Build docs as PDF on readthedocs

changes/1817.feature.rst, examples/textinput/textinput/app.py, gtk/src/toga_gtk/widgets/textinput.py
Implemented the following TextInput methods:
-  set_alignment
- set_on_gain_focus
- set_on_lose_focus
- set_error
- clear_error
- is_valid
The above methods are now implemented
=> Text input

README.rst, android/README.rst, attic/django/README.rst, attic/falcon/README.rst, attic/flask/README.rst, attic/pyramid/README.rst, attic/starlette/README.rst, attic/tornado/README.rst, attic/win32/README.rst, changes/1822.misc.rst, cocoa/README.rst, core/README.rst, demo/README.rst, docs/index.rst, docs/reference/platforms.rst, dummy/README.rst, gtk/README.rst, iOS/README.rst, nursery/curses/README.rst, nursery/qt/README.rst, nursery/tvOS/README.rst, nursery/uwp/README.rst, nursery/watchOS/README.rst, toga/README.rst, web/README.rst, winforms/README.rst
Per the call out at https://fosstodon.org/@beeware/110053388972910487, this PR updates the project's discussion forum and social media links in the documentation. 
I also did a tiny amount of cleanup and reorganizing, mostly moving the 'footer' style links to just after their sections. That made it easier to ensure consistency between the different README docs.
=> Update discussion and social media links.

changes/1851.doc.rst, changes/1852.doc.rst, core/src/toga/app.py
Added Documentation for `toga.App.widgets`.
=> Added Documentation for `toga.App.widgets`.

core/src/toga/app.py, docs/background/releases.rst, docs/background/roadmap.rst, docs/reference/api/widgets/progressbar.rst
=> Documentation cleanups

changes/1872.feature.rst, core/src/toga/app.py, winforms/src/toga_winforms/app.py
Added support for `toga.App.current_window` in WinForms.
=> Added support for `current_window` in WinForms.

changes/1881.bugfix.rst, core/src/toga/app.py
Changed spelling to prevent any Sphinx spelling error.
=> Changed spelling to prevent any Sphinx spelling error

android/tests_backend/widgets/base.py, changes/1847.feature.rst, cocoa/tests_backend/widgets/base.py, gtk/tests_backend/widgets/base.py, iOS/tests_backend/widgets/base.py, testbed/tests/testbed.py, testbed/tests/widgets/conftest.py, testbed/tests/widgets/properties.py, testbed/tests/widgets/test_activityindicator.py, testbed/tests/widgets/test_base.py, testbed/tests/widgets/test_button.py, testbed/tests/widgets/test_divider.py, testbed/tests/widgets/test_label.py, testbed/tests/widgets/test_multilinetextinput.py, testbed/tests/widgets/test_progressbar.py, testbed/tests/widgets/test_slider.py, testbed/tests/widgets/test_switch.py, winforms/tests_backend/widgets/base.py
Modified version of #1896.
Thanks to @sammyfung for the bulk of this PR.
Fixes #1847.
=> Redraw debug

changes/1876.feature.rst, iOS/src/toga_iOS/widgets/multilinetextinput.py
=> Scrolling to top and bottom fix in iOS

android/src/toga_android/libs/android/graphics.py, android/src/toga_android/libs/android/text.py, android/src/toga_android/widgets/label.py, android/tests_backend/widgets/base.py, android/tests_backend/widgets/label.py, android/tests_backend/widgets/properties.py, changes/1878.bugfix.rst
=> Android: give all justification code a minimum API level

changes/2055.misc.rst, core/src/toga/__init__.py, core/src/toga/app.py, core/src/toga/handlers.py, core/tests/test_handler.py, core/tests/test_handlers.py, pyproject.toml
Adds test coverage for handlers, plus a couple of other easy coverage wins.
=> Test coverage for handlers

changes/2118.misc.rst, examples/tutorial0/static
#1838 inadvertently merged a symlink that was used for some prototyping of the web backend. 
Thanks to @t-arn for the report.
=> Purge a stray symlink to nowhere.

changes/2201.misc.rst, docs/reference/api/resources/app_paths.rst
I removed what seems to have been an accidental repetition of a word.
=> Removed stray repeated word in Paths usage

.github/workflows/config-file-deps-bump.yml, android/pyproject.toml, changes/2445.misc.rst, cocoa/pyproject.toml, core/pyproject.toml, demo/pyproject.toml, dummy/pyproject.toml, gtk/pyproject.toml, iOS/pyproject.toml, textual/pyproject.toml, toga/pyproject.toml, tox.ini, web/pyproject.toml, winforms/pyproject.toml
- Implements https://github.com/beeware/.github/pull/106
=> Add CI workflow to bump config file dependencies

android/pyproject.toml, changes/2458.misc.rst, cocoa/pyproject.toml, core/pyproject.toml, demo/pyproject.toml, dummy/pyproject.toml, gtk/pyproject.toml, iOS/pyproject.toml, textual/pyproject.toml, toga/pyproject.toml, web/pyproject.toml, winforms/pyproject.toml
Bumps versions for dependencies in pyproject.toml and tox.ini.
=> Bump dependencies in pyproject.toml and tox.ini

README.rst, changes/2491.doc.rst
- See https://github.com/github/markup/issues/1801
- Closes https://github.com/beeware/toga/issues/2491
- Live version: https://github.com/rmartin16/toga/tree/readme-badges
=> Ensure README badges are aligned instead of stacked

changes/2560.misc.rst, docs/reference/api/widgets/table.rst
corrected the commas on the code examples to colons
=> Fixed 2 typos on docs

changes/2617.doc.rst, docs/reference/api/widgets/mapview.rst
=> Correct typo in `MapPin` example usage docs

README.rst, changes/2913.misc.rst
Noticed it still says 3.8. Is there anyway to set this to update dynamically? It's easy to miss.
=> Fixed Python version Requirement in Readme

changes/2954.doc.rst, docs/reference/platforms/terminal.rst
Super minor detail, but it did trip me up for a minute.
=> Fixed dash to underscore in Textual environment variable name

.github/workflows/ci.yml, changes/2893.misc.rst
Follow up to #2893
See the discussion in this PR, and follow up in the linked thread: https://github.com/beeware/toga/pull/2893\#discussion_r1862904875
=> Remove unneeded dependency

changes/3045.bugfix.rst, examples/hardware/hardware/app.py
Refs #2999
See this discussion in the linked PR for context: https://github.com/beeware/toga/pull/2999\#issuecomment-2540229149
=> Fix manual location update in hardware example app

.github/workflows/ci.yml, changes/3051.misc.rst
- ref: https://github.com/beeware/toga/issues/3051
=> Install build-essential package for testbed textual-linux

changes/3141.misc.rst, changes/changes/3141.misc.rst, docs/background/project/success.rst
Add Patent Toolkit (patenttk.com) to Success Stories.
- [ -] All new features have been tested
- [ -] All new features have been documented
- [ X] I have read the **CONTRIBUTING.md** file
- [ X] I will abide by the code of conduct
=> Docs: Add to Success Stories.

.pre-commit-config.yaml, changes/3147.misc.rst, core/src/toga/widgets/button.py, core/src/toga/widgets/label.py, core/src/toga/widgets/switch.py, core/tests/widgets/test_button.py, core/tests/widgets/test_label.py, core/tests/widgets/test_switch.py, iOS/src/toga_iOS/widgets/label.py, iOS/tests_backend/widgets/label.py, travertino/src/travertino/colors.py, winforms/src/toga_winforms/widgets/button.py, winforms/src/toga_winforms/widgets/switch.py, winforms/tests_backend/widgets/button.py, winforms/tests_backend/widgets/switch.py
Bumps `pre-commit` hook for `black-pre-commit-mirror` from 24.10.0 to 25.1.0 and ran the update against the repo.
=> Bump black-pre-commit-mirror from 24.10.0 to 25.1.0

testbed/tests/widgets/test_webview.py
Fixes #3163.
The fix is in 2 parts:
1. Uses github.com, rather than example.com as a test domain. I don't know why, but I get very reliable DNS failures locally trying to load `https://example.com`. I don't have that problem with `github.com`. Regardless, presumably Github has a better staffed ops team to make sure the page stay up.
2. Applies a retry approach to testing for web storage. This has the added benefits of making the test faster if the DOM is ready sooner; and more robust if it takes time (as the retries will continue for 2 seconds).
=> Fix for intermittent SecurityError in Webview DOM storage tests.

README.rst, changes/3210.misc.rst
Add a block to the README recognizing financial members.
Also adds the updated logo location after the refactor from beeware/beeware.github.io#578
URL for Anaconda logo will not be valid until beeware/beeware.github.io#597 lands. Leaving as a draft for that, plus final approval from Anaconda of their blurb.
=> Add recognition of financial members.

changes/3243.misc.rst, docs/reference/api/window.rst
Full screen support was added for mobile platforms in #2473.
=> Update mobile full screen documentation

changes/3258.misc.rst, travertino/src/travertino/style.py
Y'know, sometimes you just look at something and think "Why on Earth did I make that so unnecessarily complicated?"
Added a couple clarifying comments while I was in there.
=> Simplify compatibility check in BaseStyle union operators

changes/3272.misc.rst, docs/reference/platforms/unix-prerequisites.rst
=> Add missing word in Linux docs

changes/3301.bugfix.rst, web/src/toga_web/window.py
Not sure how these fell through testing; but the web backend currently isn't rendering the titlebar on a MainWindow because of a couple of argument and attribute name errors.
=> Correct some argument errors on the web backend.

changes/3419.misc.rst, winforms/src/toga_winforms/libs/WebView2/README.md
=> Fix Link for LICENSE of WebView2

changes/3418.misc.rst, travertino/README.rst
Fix an extra comma. Hope you do not mind merging this trivial PR.
=> Remove Extra Comma in Travertino README

changes/3441.misc.rst, docs/how-to/topics/layout.rst
=> Tweak grammar in layout.rst

android/src/toga_android/app.py, changes/2841.feature.rst
https://github.com/beeware/toga/issues/2841
=> Added night mode detection function for android.

changes/3420.misc.rst, winforms/src/toga_winforms/app.py
modified to new dialog api in winforms
should address warn issues during initial template build in windows
issue 3420
=> updated winforms dialog api to new version

changes/3138.misc.rst, docs/how-to/contribute/docs.rst, docs/reference/api/resources/fonts.rst, docs/reference/api/widgets/divider.rst, docs/tutorial/tutorial-4.rst
Resolves https://github.com/beeware/toga/issues/3138 for updating the style syntax.
=> Update docs for style change

changes/3486.misc.rst, iOS/src/toga_iOS/widgets/numberinput.py
=> A Trivial Comment Fix

changes/3509.misc.rst
=> Add a missing __init__.py to Travertino.

changes/1688.doc.rst, docs/tutorial/tutorial-0.rst
=> Extract Platform-Specific Dependencies into Separate Step

.readthedocs.yaml, changes/3523.misc.rst
=> Remove PDF support.

changes/3533.misc.rst, iOS/src/toga_iOS/widgets/dateinput.py
Told you there was a reason in using ``IntFlag``... but forgot to do the actual code simplification.
=> Simplify iOS DateInput bitmask calculation for date components.

changes/3557.misc.rst, testbed/tests/widgets/test_webview.py
=> Fix Intermittent WebView failures on Apple Platforms

changes/3556.misc.rst, winforms/src/toga_winforms/widgets/activityindicator.py
Else there's a white square which is bad.
=> Make ActivityIndicator Transparent on Winforms by default

changes/3604.misc.rst, testbed/tests/testbed.py
The PR associated with the issue referenced has long been merged and released.
=> Remove obsolete workaround for Android

.github/workflows/ci.yml, README.rst, android/README.rst, changes/3603.misc.rst, cocoa/README.rst, core/README.rst, demo/README.rst, docs/conf.py, dummy/README.rst, gtk/README.rst, iOS/README.rst, positron/README.md, textual/README.rst, toga/README.rst, web/README.rst, winforms/README.rst
=> Change Github to GitHub

changes/3605.doc.rst, docs/how-to/contribute/code.rst
Updates macOS and Linux venv commands to use `python3` per https://github.com/beeware/toga/pull/3597#discussion_r2181269169
=> Update macOS and Linux venv commands.

changes/3591.misc.rst, core/pyproject.toml, tox.ini
- Adds `fast` option to `tox`, including adding `pytest-xdist` dependency to `dev`.
- Updates bare `tox` command to run all tests, like `ci` target.
- Removes `ci` target.
=> `tox` config update: add `test-fast`, remove `-ci` target.

changes/3625.misc.rst, examples/webview/webview/app.py
Webview example fixing DeprecationWarning
Fixes #3625
=> Webview example fixing DeprecationWarning

changes/3659.misc.rst, docs/about/success.rst, docs/spelling_wordlist
=> Add success story for Beanquick

changes/3716.misc.rst, docs/reference/api/index.rst
=> Fix typo in Selection widget description in the API reference index

changes/3717.misc.rst, testbed/tests/window/test_window.py
=> Remove a redundant unsupported check as MINIMIZED is not parameterized.
